### ISSUE TITLE
Need Help with RunReactants() -- Never get any products 

### ISSUE THREAD

**Issue by tylerautera** [rdkit/rdkit#5765] opened 2022-11-15 16:38 UTC
**Configuration:**

- RDKit Version: 2022.3.4
- Operating system: OSX
- Python version (if relevant): 3.9
- Are you using conda? Yes 
- If you are using conda, which channel did you install the rdkit from? Installed from pip
- If you are not using conda: how did you install the RDKit? pip

**Description:**

I have a list of mapped reactions (in SMILES) that I am attempting to utilize with RunReactants. However, the method never returns any results. In some cases (during troubleshooting), the reactant(s) passed into the RunReactants method are _the same_  as the reaction template itself, yet still no results. 

```
targ_smiles = "C(CCC(=O)O)CC(=O)O"
targ_mol = Chem.MolFromSmiles(targ_smiles)

template = '[O:1]=[C:2]([O-:3])[CH2:4][CH2:5][CH2:6][CH2:7][C:8](=[O:9])[O-:10]>>[OH2:3].[O:1]=[CH:2][CH2:4][CH2:5][CH2:6][CH2:7][C:8](=[O:9])[O-:10]'
reaction = AllChem.ReactionFromSmarts(template) 
products = reaction.RunReactants([targ_mol])
# Returns no products

template = '[O:1]=[CH:2][CH2:3][CH2:4][CH2:5][CH2:6][C:7](=[O:8])[O-:9]>>[OH:1][CH2:2][CH2:3][CH2:4][CH2:5][CH2:6][C:7](=[O:8])[O-:9]'
reaction = AllChem.ReactionFromSmarts(template) 
products = reaction.RunReactants([targ_mol])
# Returns no products

template = '[CH3:1][CH2:2][CH2:3][CH2:4][CH2:5][C:6](=[O:7])[O-:8].[CH3:9][NH3+:10]>>[CH3:1][CH2:2][CH2:3][CH2:4][CH2:5][C:6](=[O:7])[NH:10][CH3:9].[OH2:8]'
reaction = AllChem.ReactionFromSmarts(template) 
products = reaction.RunReactants([targ_mol, Chem.MolFromSMiles('[CH3:9][NH3+:10]')])
# Returns no products

template = ''[CH3:1][CH2:2][CH2:3][CH2:4][CH2:5][CH2:6][CH2:7][CH2:8][CH2:9][CH2:10][CH2:11][CH2:12][CH2:13][CH2:14][CH2:15][C:16](=[O:17])[O-:18]>>[CH3:1][CH2:2][CH2:3][CH2:4][CH2:5][CH2:6][CH2:7][CH2:8][CH2:9][CH2:10][CH2:11][CH2:12][CH2:13][CH2:14][CH2:15][CH:16]=[O:17].[OH2:18]''
reaction = AllChem.ReactionFromSmarts(template) 
products = reaction.RunReactants([targ_mol])
# Returns no products



```

**Comment by greglandrum** [comment] 2022-11-15 16:40
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.

**Closed by greglandrum** 2022-11-15 16:40 UTC

**Comment by tylerautera** [comment] 2022-11-15 16:43
Apologies @greglandrum I have reposted in discussions. Thank you
