### ISSUE TITLE
Reindex atom index based on AtomMapNum

### ISSUE THREAD

**Issue by jungsdao** [rdkit/rdkit#5756] opened 2022-11-14 12:42 UTC
**Configuration:**

 2021.03.2
- RDKit Version: '2021.03.2'
- Operating system: Linux Ubuntu
- Python version (if relevant): 3.7+
- Are you using conda? Yes
- If you are using conda, which channel did you install the rdkit from? I don't know
- If you are not using conda: how did you install the RDKit?

**Description:**

I have SMILES with atom index encoded as following 
`[C:1]=[C:2]([H:5])[H:6].[O:0]([H:3])[H:4]`

I want to preserve this atom index after converting SMILES into RDkit Mol object. 
However, I find this atom index is saved in `AtomMapNum` property but not in `AtomIdx` which makes confusion. 
Is there any way I can reassign atom index of mol object based on `AtomMapNum`?
That would make my life way more easier. 

```
rxnsmiles = "[C:1]=[C:2]([H:5])[H:6].[O:0]([H:3])[H:4]>>[H:3].[O:0]([C:1]=[C:2]([H:5])[H:6])[H:4]"
reactant_smiles, product_smiles = rxnsmiles.split(">>")

rxn = rdChemReactions.ReactionFromSmarts(reactionsmiles, useSmiles=True)
rdkit_reactants = Chem.CombineMols(*rxn.GetReactants())
                                   
AtomMapNum = [atom.GetAtomMapNum() for atom in m.GetAtoms()]
AtomIdx = [atom.GetIdx() for atom in m.GetAtoms()]
print("reorder_idx : ", reorder_idx)
print("AtomIdx : ", AtomIdx)
```

**Comment by bp-kelley** [comment] 2022-11-14 13:35
Atom index and the atom map are two very different things.  In general, the atom map is preserved while the atom index is essentially arbitrary.  It's not clear what you are trying to do, but here are some suggestions.

If you really must do reorder atoms, see Chem.RenumberAtoms, but I highly suggest this is not the right approach as the act of writing a smiles string will not necessarily preserve the atom index.

```
RenumberAtoms(...)
    RenumberAtoms( (Mol)mol, (object)newOrder) -> Mol :
        Returns a copy of a molecule with renumbered atoms
        
          ARGUMENTS:
        
            - mol: the molecule to be modified
        
            - newOrder: the new ordering the atoms (should be numAtoms long)
              for example: if newOrder is [3,2,0,1], then atom 3 in the original 
              molecule will be atom 0 in the new one
```

It looks like you should just use a reaction object:

```
rxn = rdChemReactions.ReactionFromSmarts(rxnsmiles)
reactants = [Chem.Mol(reactant) for reactant in rxn.GetReactants()] 
```

If you need to use atom maps, I suggest a lookup:
```
lookup = {}
for atom in reactant.GetAtoms():
     atom_map = atom.GetAtomMapNum()
     if atom_map: lookup[atom_map] = atom
```

Then you can easily go from atom map to atom.

**Comment by jungsdao** [comment] 2022-11-14 16:59
Thank you for the comment, 
Although you discouraged using `Chem.RenumberAtoms`, that was the exactly what I needed and it solved my issue. 
I really appreciate for your answer :)

**Comment by greglandrum** [comment] 2022-11-15 05:38
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.

**Closed** 2022-11-15 05:39 UTC
