### ISSUE TITLE
Chem.SplitMolByPDBChainId() broken

### ISSUE THREAD

**Issue by samoturk** [rdkit/rdkit#738] opened 2016-01-19 16:13 UTC
I recently tried to re-run he notebook I presented at RDKit UGM but it doesn't work anymore. The problem is in Chem.SplitMolByPDBChainId(). Steps to reproduce:
```python
from rdkit import Chem
import gzip

cont = gzip.open('4WA9.pdb.gz','rb').read()
pdb = Chem.MolFromPDBBlock(cont, sanitize=False, removeHs=True)
Chem.SplitMolByPDBChainId(pdb)
```
Error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-d6346a0c87f2> in <module>()
----> 1 Chem.SplitMolByPDBChainId(pdb)

TypeError: No to_python (by-value) converter found for C++ type: boost::shared_ptr<RDKit::ROMol>
```
Chem.SplitMolByPDBResidues() also seems to not work.

**Comment by samoturk** [comment] 2016-01-19 16:30
Update: The problem seems to be specific to running latest RDKit on python2.7 with boost 1.60.0. There is no problem if I use latest RDKit version on Anaconda with boost 1.56.0.

**Comment by bp-kelley** [comment] 2016-01-27 20:44
Could you send me your OS and build info so I can take a look at it?

**Comment by samoturk** [comment] 2016-02-01 13:23
I get the same error with RDKit 2015_09_2 and git master version pulled today.  
OS is 64 bit Arch Linux with following:
```
bison 3.0.4
boost 1.60.0
boost-libs 1.60.0
cmake 3.4.1
flex 2.6.0
python2 2.7.11
python2-numpy 1.10.2
```
Build scrips are here: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=rdkit and https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=rdkit-git

**Comment by ericksonla** [comment] 2016-02-10 00:08
I'm having the same issue with OS X 10.11.3, boost 1.60, and python 2.7.10

**Comment by bp-kelley** [comment] 2016-02-10 00:23
Thanks.  I'll have to investigate boost 60 in particular.  When you did a build, did you run the tests?  I expect more might actually be broken in this case.

**Comment by ericksonla** [comment] 2016-02-10 00:46
No, I installed with Homebrew. Based on [this](https://github.com/rdkit/homebrew-rdkit/issues/27), it looks like that might not work with build tests?

**Comment by ericksonla** [comment] 2016-02-17 17:04
Any estimates on when this may be addressed? Just trying to decide how much time to dedicate to a workaround.

**Comment by greglandrum** [comment] 2016-03-23 05:37
There seems to be a general problem with boost 1.60 and, at least, python2.7
Many of the tests fail.

Investigating today.

**Comment by greglandrum** [comment] 2016-03-23 05:42
Ah, that was quick. It's a bug in boost 1.60:
https://github.com/boostorg/python/pull/59
Since this is going to be fixed in the next version of boost and would require a large amount of redundant code to fix it in the RDKit, I'm going to pass on fix it.
Please use boost 1.59 or earlier.

**Closed** 2016-03-23 05:46 UTC
Labels: wontfix

**Comment by bp-kelley** [comment] 2016-03-23 12:07
that explains a lot, boost 1.60 has never really worked for me.  Good catch @greglandrum

**Comment by greglandrum** [comment] 2016-05-30 14:03
A followup on this one: I have confirmed that boost v1.61 works fine with the RDKit.
