### ISSUE TITLE
BCUT_CHGX has issues with some atoms

### ISSUE THREAD

**Issue by bp-kelley** [rdkit/rdkit#5990] opened 2023-01-19 15:25 UTC
```
>>> Descriptors.BCUT2D_CHGHI(Chem.MolFromSmiles("[Na+]"))
nan
```

```
>>> Descriptors.BCUT2D_CHGHI(Chem.MolFromSmiles("[Cl-]"))
-1.0
```

**Comment by bp-kelley** [comment] 2023-01-19 15:27
This was raised in #5824

**Comment by bp-kelley** [comment] 2023-01-19 16:06
So the problem is that the gasteiger charges used don't have an entry for [Na+] and this error is not being reported to python.

**Comment by greglandrum** [comment] 2023-01-27 05:56
I don't think this is a bug. The descriptors calculators do not generally throw exceptions when they cannot compute a value (for whatever reason). It's generally the responsibility of client code to detect these situations and handle them.

**Comment by greglandrum** [comment] 2023-01-28 04:24
Closing this because I think it's expected behavior. Please reopen if you think that's wrong.

**Closed by greglandrum** 2023-01-28 04:24 UTC
Labels: not a bug
