### ISSUE TITLE
MolStandardize.rdMolStandardize BUG

### ISSUE THREAD

**Issue by gentle1999** [rdkit/rdkit#7218] opened 2024-03-07 10:06 UTC
**Describe the bug**
`MolStandardize.rdMolStandardize.StandardizeSmiles` is described in the [documentation](https://www.rdkit.org/docs/source/rdkit.Chem.MolStandardize.rdMolStandardize.html#rdkit.Chem.MolStandardize.rdMolStandardize.StandardizeSmiles) as "Convenience function for standardizing a SMILES". So I think the function should output a simplified but isomorphic form of the input SMILES, which works well in most of my scenarios (organic small molecules not involving metals). However in a recent application I noticed an unusual example, "C=C[CH-]C=C". This SMILES would be incorrectly output as "C=[C-]CC=C" when the two molecules are not equivalent at all.

**To Reproduce**
```python
from rdkit import Chem
from rdkit.Chem.MolStandardize import rdMolStandardize

smiles = "C=C[CH-]C=C"
smiles_with_H = "[H]C([H])=C([H])[C-]([H])C([H])=C([H])[H]" # Same as above
print(rdMolStandardize.StandardizeSmiles(smiles))
print(rdMolStandardize.StandardizeSmiles(smiles_with_H))
```
```
C=[C-]CC=C
C=[C-]CC=C
[17:54:20] Initializing MetalDisconnector
[17:54:20] Running MetalDisconnector
[17:54:20] Initializing Normalizer
[17:54:20] Running Normalizer
[17:54:20] Moved proton from sp2-carbon hydrogen to sp3-carbon hydrogen
[17:54:20] Initializing MetalDisconnector
[17:54:20] Running MetalDisconnector
[17:54:20] Initializing Normalizer
[17:54:20] Running Normalizer
[17:54:20] Moved proton from sp2-carbon hydrogen to sp3-carbon hydrogen
```
Confusingly the log has `Moved proton from sp2-carbon hydrogen to sp3-carbon hydrogen`, which in my opinion destroys the isomorphism between the two

**Expected behavior**
```python
from rdkit import Chem
from rdkit.Chem.MolStandardize import rdMolStandardize

smiles = "C=C[CH-]C=C"
smiles_with_H = "[H]C([H])=C([H])[C-]([H])C([H])=C([H])[H]"
print(rdMolStandardize.StandardizeSmiles(smiles)) # Output as "C=C[CH-]C=C"
print(rdMolStandardize.StandardizeSmiles(smiles)) # Output as "C=C[CH-]C=C"
```

**Screenshots**
![PixPin_2024-03-07_18-03-24](https://github.com/rdkit/rdkit/assets/50197885/dfcdd05e-297c-426e-9986-8344c1190498)

**Configuration (please complete the following information):**
 - RDKit version: 2023.9.5 & 2023.9.4
 - OS: [Ubuntu 22.04 with WSL2
 - Python version (if relevant): 3.10.13
 - Are you using conda? No
 - If you are using conda, which channel did you install the rdkit from?
 - If you are not using conda: how did you install the RDKit? PyPi

**Additional context**
I'm not sure of the inner workings of the bug, but I'm able to do what I need for the time being in the form of `Chem.MolToSmiles(Chem.MolFromSmiles(smiles_with_H))`, so hopefully the officials can fix this to bring us a more elegant experience. Thank you very much for your contributions!

**Comment by greglandrum** [comment] 2024-03-08 05:49
> `MolStandardize.rdMolStandardize.StandardizeSmiles` is described in the [documentation](https://www.rdkit.org/docs/source/rdkit.Chem.MolStandardize.rdMolStandardize.html#rdkit.Chem.MolStandardize.rdMolStandardize.StandardizeSmiles) as "Convenience function for standardizing a SMILES". So I think the function should output a simplified but isomorphic form of the input SMILES

This is not, in fact, what the function does. The idea of standardization is that it transforms the molecule to get it into a "standard" form. Part of that standardization is, potentially, re-arranging charges. 

We can (and should) do a better job of documenting exactly what these functions do.

I'm going to close this because it's not a bug: the software is doing what it was designed to do.

**Closed by greglandrum** 2024-03-08 05:49 UTC
Labels: bug
