### ISSUE TITLE
cannot convert molecule from smiles

### ISSUE THREAD

**Issue by Crispae** [rdkit/rdkit#3601] opened 2020-11-30 16:52 UTC
This error occur while i am trying to rdkitmol object frome smiles ,The smile is ("O=N([O-])C1=C(CN=C1NCCSCc2ncccc2)Cc3ccccc3")

Python argument types in
    rdkit.Chem.rdmolfiles.MolFromSmiles(str)
did not match C++ signature:
    MolFromSmiles(class boost::python::api::object SMILES, bool sanitize=True, class boost::python::dict replacements={})
    MolFromSmiles(class boost::python::api::object SMILES, struct RDKit::SmilesParserParams params)

**Comment by ptosco** [comment] 2020-11-30 17:33
@Crispae When I run your SMILES though `MolFromSmiles` I get:

```
Chem.MolFromSmiles("O=N([O-])C1=C(CN=C1NCCSCc2ncccc2)Cc3ccccc3")
RDKit ERROR: [18:24:28] Explicit valence for atom # 1 N, 4, is greater than permitted
```

which is expected, as the SMILES for the nitro group is incorrect (missing positive charge on the nitrogen).
If I add the positive charge, the command succeeds:

```
Chem.MolFromSmiles("O=[N+]([O-])C1=C(CN=C1NCCSCc2ncccc2)Cc3ccccc3")
```
![image](https://user-images.githubusercontent.com/5244385/100642979-c8cd9200-3339-11eb-8b6f-d53227af9061.png)

I cannot reproduce the error message that you report. What Python version and RDKit version are you using?

**Comment by Crispae** [comment] 2020-12-01 06:43
I am using conda environment 
--> Python version - Python 3.6.12 |Anaconda, Inc.|
--> Rdkit version - '2017.09.1'
-->Rdkit boost version - '1_59'

When i run **Chem.MolFromSmiles("O=([O-])C1=C(CN=C1NCCSCc2ncccc2)Cc3ccccc3")** without correcting the SMILES  it doesnot give any error but it return none 

After correcting the SMILES it give the result.

**Comment by ptosco** [comment] 2020-12-01 06:58
You are using an outdated version of RDKit; the current release is 2020.09 and it will report error messages in your Jupyter Notebook.
`MolFromSmiles` returns `None` if it fails to parse the SMILES due to a syntax error, so you should always check that the returned molecule is not `None` prior to using it.
I have relabeled this issue as "question" and I am now closing it as I believe the question is answered.

**Closed by ptosco** 2020-12-01 06:58 UTC
Labels: question

**Comment by Crispae** [comment] 2020-12-01 07:13
thanks
