### ISSUE TITLE
Issue generating MQNs from mol that is read from XYZ

### ISSUE THREAD

**Issue by gianmarco-terrones** [rdkit/rdkit#6226] opened 2023-03-22 05:33 UTC
When I read a Mol from a SMILES, I can generate MQNs with it. When I read a Mol from an XYZ file, I cannot.

I use two files to test this: `mqn_generation.py` and `my_geo.xyz`. I pasted the contents of each of those two files below.

`mqn_generation.py`
```
from rdkit import Chem
from rdkit.Chem.rdmolfiles import MolFromXYZFile, MolFromSmiles
from rdkit.Chem import rdMolDescriptors

mol_1 = MolFromXYZFile('my_geo.xyz')

# SMILES string corresponding to the XYZ file.
corresponding_smiles = '[C]O[Al]12([O])(O[C])O[C]O[Al](O2)(O[C]O1)([O])[O]'
mol_2 = MolFromSmiles(corresponding_smiles)

print('checking if file is read correctly')
# The for loops below both print the same atoms for mol_1 and mol_2 (different order though)
for idx, atom in enumerate(mol_1.GetAtoms()):
	print(f'mol_1 idx is {idx} and element is {atom.GetSymbol()}')
print()
for idx, atom in enumerate(mol_2.GetAtoms()):
	print(f'mol_2 idx is {idx} and element is {atom.GetSymbol()}')

# https://xinhaoli74.github.io/blog/rdkit/2021/01/06/rdkit.html#Molecular-Quantun-Numbers-(MQN)-Descriptors
mqn_ds_2 = rdMolDescriptors.MQNs_(mol_2)
print(f'len(mqn_ds_2) is {len(mqn_ds_2)}')
print(f'mqn_ds_2 is {mqn_ds_2}')
# Can generate MQNs from the Mol read from SMILES.

print()
print('Now, attempting with mol object read from an XYZ file')
mqn_ds_2 = rdMolDescriptors.MQNs_(mol_1)
# The above line gives the error below:
"""""
****
Pre-condition Violation
getNumImplicitHs() called without preceding call to calcImplicitValence()
Violation occurred on line 299 in file /Users/runner/miniforge3/conda-bld/rdkit_1678104751770/work/Code/GraphMol/Atom.cpp
Failed Expression: d_implicitValence > -1
****

Traceback (most recent call last):
  File "/Users/gianmarcoterrones/Downloads/mqn_generation.py", line 25, in <module>
    mqn_ds_2 = rdMolDescriptors.MQNs_(mol_1)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Pre-condition Violation
	getNumImplicitHs() called without preceding call to calcImplicitValence()
	Violation occurred on line 299 in file Code/GraphMol/Atom.cpp
	Failed Expression: d_implicitValence > -1
	RDKIT: 2022.09.5
	BOOST: 1_78
"""""
```

_**So, the error looks like**_
```
****
Pre-condition Violation
getNumImplicitHs() called without preceding call to calcImplicitValence()
Violation occurred on line 299 in file /Users/runner/miniforge3/conda-bld/rdkit_1678104751770/work/Code/GraphMol/Atom.cpp
Failed Expression: d_implicitValence > -1
****

Traceback (most recent call last):
  File "/Users/gianmarcoterrones/Downloads/mqn_generation.py", line 25, in <module>
    mqn_ds_2 = rdMolDescriptors.MQNs_(mol_1)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Pre-condition Violation
	getNumImplicitHs() called without preceding call to calcImplicitValence()
	Violation occurred on line 299 in file Code/GraphMol/Atom.cpp
	Failed Expression: d_implicitValence > -1
	RDKIT: 2022.09.5
	BOOST: 1_78
```

`my_geo.xyz`

```
16

O       4.62       5.93       1.89
O       6.95       5.32       0.78
O       7.07       5.26       2.96
C       5.22       7.62      -1.78
O       5.24       3.61       0.78
O       5.26       7.07       3.66
C       7.62       5.22       1.79
Al       5.28       5.28       0.00
Al       5.28       5.28       3.30
C       2.94       5.34      -1.78
O       5.30       3.49       2.96
O       5.32       6.95      -0.77
O       3.49       5.30       3.66
C       5.34       2.94       1.79
O       3.61       5.24      -0.77
O       5.93       4.62      -1.88

```

I used rdkit version 2022.09.1, downloaded with conda using the channel conda-forge. I am using a Mac with macOS Ventura 13.1. The version of python in my conda environment is 3.11.0.

**Comment by ptosco** [comment] 2023-03-22 11:35
@gianmarco-terrones This is not a bug.
Regarding `mol_1`: when you read a molecule from a XYZ file, the molecule will simply be a collection of atoms with no bonds in between. Since the descriptor you are attempting to compute requires connectivity, it is bound to fail.
Regarding `mol_2`: that SMILES does not look correct, as all heavy atoms are specified as having no bonded hydrogens, which I doubt is the case. This also suggests that the XYZ file that you are loading should have hydrogens, but it doesn't.
So it looks like your molecules both have several issues that you should address.
I am closing this as this is not a bug. Please use the Discussions tab in the future before submitting a bug - if the topic of the Discussion turns out to involve an actual bug, it can always be moved to the Issues section.

**Closed by ptosco** 2023-03-22 11:35 UTC
Labels: bug
