### ISSUE TITLE
Removing radical electrons isn't applied well if there are atom mapping numbers

### ISSUE THREAD

**Issue by iwyoo** [rdkit/rdkit#7651] opened 2024-07-23 06:06 UTC
**Describe the bug**
Removing radical-electrons in a mol works differently between with and without atom-mapping numbers.

**To Reproduce**
```python3
from rdkit import Chem

# Baseline example
smiles = "N(OC)C"
mol = Chem.MolFromSmiles(smiles)
print(mol.GetAtomWithIdx(0).GetSymbol(), mol.GetAtomWithIdx(0).GetNumRadicalElectrons())  # N, 0

# Radical example
smiles = "[N](OC)C"  # [N](OC)C
mol = Chem.MolFromSmiles(smiles)
print(mol.GetAtomWithIdx(0).GetSymbol(), mol.GetAtomWithIdx(0).GetNumRadicalElectrons())  # N, 1

# Remove radical electrons
smiles = "[N](OC)C"  # [N](OC)C
mol = Chem.MolFromSmiles(smiles)
[atom.SetNumRadicalElectrons(0) for atom in mol.GetAtoms()]
print(mol.GetAtomWithIdx(0).GetSymbol(), mol.GetAtomWithIdx(0).GetNumRadicalElectrons())  # N, 0
print(mol.GetAtomWithIdx(0).GetImplicitValence())  # 0
print(mol.GetAtomWithIdx(0).GetNumImplicitHs())  # 0
print(mol.GetAtomWithIdx(0).GetNumExplicitHs())  # 0
print(Chem.MolToSmiles(mol))  # CNOC

# With atom mapping number
smiles = "[N:1]([O:2][C:3])[C:4]"  # [N](OC)C
mol = Chem.MolFromSmiles(smiles)
print(mol.GetAtomWithIdx(0).GetSymbol(), mol.GetAtomWithIdx(0).GetNumRadicalElectrons())  # N, 1

# Remove radical electrons, but keep atom mapping number
smiles = "[N:1]([O:2][C:3])[C:4]"  # [N](OC)C
mol = Chem.MolFromSmiles(smiles)
[atom.SetNumRadicalElectrons(0) for atom in mol.GetAtoms()]
print(mol.GetAtomWithIdx(0).GetSymbol(), mol.GetAtomWithIdx(0).GetNumRadicalElectrons())  # N, 0
print(mol.GetAtomWithIdx(0).GetImplicitValence())  # 0
print(mol.GetAtomWithIdx(0).GetNumImplicitHs())  # 0
print(mol.GetAtomWithIdx(0).GetNumExplicitHs())  # 0
print(Chem.MolToSmiles(mol))  # [N:1]([O:2][C:3])[C:4]
# The correct result should be [NH:1]([O:2][C:3])[C:4]

# Adding atom mapping number from scratch
smiles = "N(OC)C"
mol = Chem.MolFromSmiles(smiles)
[atom.SetAtomMapNum(i) for i, atom in enumerate(mol.GetAtoms(), 1)]
print(Chem.MolToSmiles(mol))  # [NH:1]([O:2][C:2])[C:3]
```

**Expected behavior**
The second from the last should give the same result with the last.

**Configuration (please complete the following information):**
 - RDKit version: 2024.3.3
 - OS: [e.g. Ubuntu 24.04]
 - Python version (if relevant):
 - Are you using conda? No
 - If you are not using conda: The current RDKit library is installed by PIP

**Comment by greglandrum** [comment] 2024-07-23 06:12
This is not a bug.
When you put an atom in square brackets in a SMILES that says that the atom is not allowed to have implicit Hs added to it and it fundamentally changes the chemistry of the atom.
If you want to see if others can suggest ways to do what you are trying to accomplish, feel free to open a discussion item for it, but I am going to close this since it's not a bug.

**Closed by greglandrum** 2024-07-23 06:12 UTC
Labels: bug

**Comment by iwyoo** [comment] 2024-07-23 07:44
@greglandrum Thanks for the quick reply. However, if you look at the result of the third block from the top, even if there is a square bracket, the bracket disappears when I remove the radical electron. I think MolToSmiles gives different results only when there is an 'atom-mapping number'. (I guess the only difference between these examples is atom-mapping number.) Is it intentionally designed that it does not automatically calculate and add H when there is an atom mapping number?

**Comment by greglandrum** [comment] 2024-07-23 08:02
I'm not sure which example you mean, but if it's this one:
```
smiles = "[N](OC)C"  # [N](OC)C
mol = Chem.MolFromSmiles(smiles)
[atom.SetNumRadicalElectrons(0) for atom in mol.GetAtoms()]
```
then the problem is that you have gone out of your way to create a non-physical situation and the RDKit just can't catch every possible strange thing users do to molecules.

Let me explain: the `[N]` in the SMILES indicates that the N atom has no implicit Hs. This is the information you've provided.
The chemistry perception then infers that a neutral N with no implicit Hs and a total valence of 2 must have one radical electron.
You then set the radical electron count to zero, creating an impossible situation: a neutral two-valent N with no implicit Hs has to have a radical.
This non-physical situation confuses the SMILES writing code and it outputs something incorrect.

The only way we could possible catch things like this while writing SMILES is to validate the chemistry *again* while writing the SMILES; that's not a price that we're willing to pay.

I assume that you are trying to solve a particular problem; the weird chemistry manipulations you are doing are not helping solve that problem. If you describe what you are trying to do in a Discussion topic, people may be able to help you to figure out a solution for it.
