### ISSUE TITLE
How can i count the number of the functional group of the molecule?

### ISSUE THREAD

**Issue by Yoko1030** [rdkit/rdkit#4522] opened 2021-09-16 03:09 UTC
Rdkitconfig has provided a text which named FunctionalGroups.txt, if i want to count the number of the functional group of the molecule, what should i do?

**Comment by greglandrum** [comment] 2021-09-16 04:23
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.

**Closed by greglandrum** 2021-09-16 04:23 UTC
