### ISSUE TITLE
How can i calculate logD rdkit?

### ISSUE THREAD

**Issue by cgh2797** [rdkit/rdkit#3718] opened 2021-01-12 02:07 UTC
How can i calculate logD in rdkit?

**Comment by greglandrum** [comment] 2021-01-12 04:35
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.

**Closed by greglandrum** 2021-01-12 04:35 UTC
Labels: enhancement

**Comment by UnixJunkie** [comment] 2025-11-14 18:22
Probably not possible because RdKit does not have a pKa model (logD is logP at a given pH; you would need a pKa model to protonate the molecule correctly for the given pH).
