### ISSUE TITLE
particular mol file fails in rdkit but works in cdk and indigo

### ISSUE THREAD

**Issue by LegacyOfKain** [rdkit/rdkit#6426] opened 2023-06-01 23:23 UTC
Below mol file fails to render in rdkit but works in cdk and indigo

[_problematic.mol.txt](https://github.com/rdkit/rdkit/files/11630528/_problematic.mol.txt)

**Comment by ptosco** [comment] 2023-06-02 10:27
Closing as this is not a bug.
Please ask questions in the Discussions tab when unsure rather than filing a bug straightaway.

The nitrogen atom bearing the _N_-oxide functional group is missing a `+1` charge. Neutral tetravalent nitrogen is chemically wrong, hence RDKit will fail to generate a molecule. This is the expected behavior.
You can either fix your CTAB by adding a `+1` charge:
```
from rdkit import Chem
from rdkit.Chem.Draw import rdMolDraw2D
from IPython.display import SVG

moldata = """\

  ACD/Labs05262313092D

 38 42  0  0  1  0  0  0  0  0 41 V2000
    2.2895   -3.9955    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.2895   -2.6337    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.4568   -1.9903    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.6389   -2.6337    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.7463   -1.9903    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    6.9285   -2.6337    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    6.9285   -3.9955    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.7463   -4.6389    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.6389   -3.9955    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    8.0358   -4.6389    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    9.2180   -3.9955    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    9.2180   -2.6337    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   10.3254   -4.6389    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   10.3254   -5.9857    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    9.2180   -6.6292    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    8.0358   -5.9857    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    9.2180   -7.9760    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    8.1555   -8.7392    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    8.5745  -10.0410    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    9.8615  -10.0410    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   10.2655   -8.7392    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   11.5674   -8.3351    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   11.5075   -3.9955    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   11.5075   -2.6337    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   12.6748   -1.9903    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   13.7971   -2.6337    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   13.7971   -3.9955    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   14.9643   -4.6389    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   14.9643   -5.9857    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   13.7971   -6.6292    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   12.6748   -5.9857    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   12.6748   -4.6389    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.4568   -0.6435    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.6389    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.2895    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.1672   -0.6435    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.1672   -1.9903    0.0000 N   0  3  0  0  0  4  0  0  0  0  0  0
    0.0000   -2.6337    0.0000 O   0  5  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  2  3  2  0  0  0  0
  2 37  1  0  0  0  0
  3  4  1  0  0  0  0
  3 33  1  0  0  0  0
  4  5  2  0  0  0  0
  4  9  1  0  0  0  0
  5  6  1  0  0  0  0
  6  7  2  0  0  0  0
  7  8  1  0  0  0  0
  7 10  1  0  0  0  0
  8  9  2  0  0  0  0
 10 11  1  0  0  0  0
 11 12  2  0  0  0  0
 11 13  1  0  0  0  0
 13 14  1  1  0  0  0
 13 23  1  0  0  0  0
 14 15  1  0  0  0  0
 15 16  2  0  0  0  0
 15 17  1  0  0  0  0
 17 18  2  0  0  0  0
 17 21  1  0  0  0  0
 18 19  1  0  0  0  0
 19 20  2  0  0  0  0
 20 21  1  0  0  0  0
 21 22  1  0  0  0  0
 23 24  1  1  0  0  0
 23 32  1  0  0  0  0
 24 25  1  0  0  0  0
 25 26  1  0  0  0  0
 26 27  1  0  0  0  0
 27 28  2  0  0  0  0
 27 32  1  0  0  0  0
 28 29  1  0  0  0  0
 29 30  2  0  0  0  0
 30 31  1  0  0  0  0
 31 32  2  0  0  0  0
 33 34  1  0  0  0  0
 33 35  2  0  0  0  0
 35 36  1  0  0  0  0
 36 37  2  0  0  0  0
 37 38  1  0  0  0  0
M  END
"""

mol = Chem.MolFromMolBlock(moldata)
assert mol
mol
```
![image](https://github.com/rdkit/rdkit/assets/5244385/5ee58e49-695b-4752-acb8-702ed7f25122)

or, if you are just interested in visualization, leave the chemically invalid neutral tetravalent nitrogen as is and load it with `sanitize=False`:
```
from rdkit import Chem
from rdkit.Chem.Draw import rdMolDraw2D
from IPython.display import SVG

moldata = """\

  ACD/Labs05262313092D

 38 42  0  0  1  0  0  0  0  0 41 V2000
    2.2895   -3.9955    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.2895   -2.6337    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.4568   -1.9903    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.6389   -2.6337    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.7463   -1.9903    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    6.9285   -2.6337    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    6.9285   -3.9955    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.7463   -4.6389    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.6389   -3.9955    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    8.0358   -4.6389    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    9.2180   -3.9955    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    9.2180   -2.6337    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   10.3254   -4.6389    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   10.3254   -5.9857    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    9.2180   -6.6292    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    8.0358   -5.9857    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    9.2180   -7.9760    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    8.1555   -8.7392    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    8.5745  -10.0410    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    9.8615  -10.0410    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   10.2655   -8.7392    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   11.5674   -8.3351    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   11.5075   -3.9955    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   11.5075   -2.6337    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   12.6748   -1.9903    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   13.7971   -2.6337    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   13.7971   -3.9955    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   14.9643   -4.6389    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   14.9643   -5.9857    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   13.7971   -6.6292    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   12.6748   -5.9857    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   12.6748   -4.6389    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.4568   -0.6435    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.6389    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.2895    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.1672   -0.6435    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.1672   -1.9903    0.0000 N   0  0  0  0  0  4  0  0  0  0  0  0
    0.0000   -2.6337    0.0000 O   0  5  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  2  3  2  0  0  0  0
  2 37  1  0  0  0  0
  3  4  1  0  0  0  0
  3 33  1  0  0  0  0
  4  5  2  0  0  0  0
  4  9  1  0  0  0  0
  5  6  1  0  0  0  0
  6  7  2  0  0  0  0
  7  8  1  0  0  0  0
  7 10  1  0  0  0  0
  8  9  2  0  0  0  0
 10 11  1  0  0  0  0
 11 12  2  0  0  0  0
 11 13  1  0  0  0  0
 13 14  1  1  0  0  0
 13 23  1  0  0  0  0
 14 15  1  0  0  0  0
 15 16  2  0  0  0  0
 15 17  1  0  0  0  0
 17 18  2  0  0  0  0
 17 21  1  0  0  0  0
 18 19  1  0  0  0  0
 19 20  2  0  0  0  0
 20 21  1  0  0  0  0
 21 22  1  0  0  0  0
 23 24  1  1  0  0  0
 23 32  1  0  0  0  0
 24 25  1  0  0  0  0
 25 26  1  0  0  0  0
 26 27  1  0  0  0  0
 27 28  2  0  0  0  0
 27 32  1  0  0  0  0
 28 29  1  0  0  0  0
 29 30  2  0  0  0  0
 30 31  1  0  0  0  0
 31 32  2  0  0  0  0
 33 34  1  0  0  0  0
 33 35  2  0  0  0  0
 35 36  1  0  0  0  0
 36 37  2  0  0  0  0
 37 38  1  0  0  0  0
M  END
"""
mol = Chem.MolFromMolBlock(moldata, sanitize=False)
assert mol
mol
```
![image](https://github.com/rdkit/rdkit/assets/5244385/79e36a7a-adf1-43a1-a446-9ad4a37fc436)

**Closed by ptosco** 2023-06-02 10:27 UTC
Labels: bug

**Comment by LegacyOfKain** [comment] 2023-06-02 13:21
Hi @ptosco 
Appreciate your solution with detailed explanation.
