### ISSUE TITLE
ImportError: cannot import name format

### ISSUE THREAD

**Issue by Allvitende** [rdkit/rdkit#1441] opened 2017-06-01 20:07 UTC
I'm getting an error when trying to import this in my Python script. All packages are installed correctly. Also tried reinstalling them. Here is the error:
`    152     from pandas.formats import format as fmt `
`    153   except ImportError:`
`--> 154     from pandas.core import format as fmt  # older versions`
`    155 else: `
`    156   fmt = 'Pandas not available'`

**Comment by Allvitende** [comment] 2017-06-01 20:09
My imports look like this:
`import pandas as pd
`
`
from rdkit import Chem
`
`
from rdkit.Chem import PandasTools
`

**Comment by hsiaoyi0504** [comment] 2017-06-02 03:18
I don't think so it's `rdkit`'s problem. It should be `pandas`'s problem. Can you give more details which version `rdkit`, `pandas`, and how your environment are installed ?

**Comment by gedeck** [comment] 2017-06-02 03:26
It is and it's not. It's the third time that pandas moves the format function. First it was in `pandas.core`, then `pandas.formats` and now in `pandas.io.formats`.

A fix for the move was added to RDkit a few weeks ago in PR #1410 . If you work with a default distribution, just fix the import (`from pandas.io.formats import format as fmt`) and with the next release the problem is gone until pandas moves it a fourth time.

**Comment by greglandrum** [comment] 2017-06-02 05:07
To confirm, this will be in the 2017.03.2 patch release (coming in the next week or so)

**Closed** 2017-06-02 05:08 UTC
Labels: duplicate
