### ISSUE TITLE
how to extract a fingerptint for SMARTS?

### ISSUE THREAD

**Issue by chaoyan1037** [rdkit/rdkit#4509] opened 2021-09-14 00:26 UTC
Is there a way to extract fingerprints for SMARTS? Converting them into SMILES may result in invalid molecules. PatternFingerprint does not consider the bond information. I am looking for something else than can be used as the representation for the SMARTS sequences.

For example, I have the following examples:
```
'C-[C&H1&D2&+0]=[C&H1&D2&+0]-[C&D1&H3]',
'C-[C&H1&D2&+0]=[C&H1&D2&+0]-C',
'C/[C&H1&D2&+0]=[C&H1&D2&+0]\\C',
'C/[C&H1&D2&+0]=[C&H1&D2&+0]\\[C&D1&H3]',
'C/C=C/[C&H3&D1&+0]',
'C/[C&H1&D2&+0]=[C&H1&D2&+0]/C'
```

**Comment by greglandrum** [comment] 2021-09-14 06:31
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.

**Closed by greglandrum** 2021-09-14 06:31 UTC
Labels: enhancement
