### ISSUE TITLE
Hydrogen Mapping

### ISSUE THREAD

**Issue by TieuLongPhan** [rdkit/rdkit#7934] opened 2024-10-18 09:24 UTC
I'm working with Hydrogen tracing  so I need the atom map for hydrogen, but I found Chem.CanonSmiles will remove it in some cases.

Please see examples below:

rsmi = '[H][O:1][H:2]'
canon_rsmi = Chem.CanonSmiles(rsmi)
>> '[OH2:1]' # miss the hydrogen with atom number 2

rsmi = '[H:1][H:2]'
canon_rsmi = Chem.CanonSmiles(rsmi)
>> '[H:1][H:2]' # still keep hydrogen number

What I expect is can still keep the atom map number of hydrogen and it should be explicit rdkit.Mol.

**Screenshots**

**Configuration (please complete the following information):**
 - RDKit version:  2024.3.5
 - OS: Fedora 37
 - Python version (if relevant): 3.11
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? pip
 - If you are not using conda: how did you install the RDKit? pip

**Comment by greglandrum** [comment] 2024-10-18 10:47
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.

**Closed by greglandrum** 2024-10-18 10:47 UTC
