### ISSUE TITLE
RDGeneral/export.h not found

### ISSUE THREAD

**Issue by alphamol-basel** [rdkit/rdkit#7568] opened 2024-06-26 03:06 UTC
Dear developers:

I am trying to use rdkit with C++ (GCC version 7.5.0 SUSE Linux). 
However, the file RDGeneral/export.h cannnot be found, although this file is cited by other files, e.g. GraphMol/GraphMol.h.

Thanks.

-----------------------------------------

**Describe the bug**
RDGeneral/export.h file not found.

**To Reproduce**
**rdkit.cpp:**
#include <GraphMol/GraphMol.h>
#include <iostream>

int main()
{
    std::cout << "test" << std::endl;
    return 0;
}

**Compile command:**
g++ -o test rdkit.cpp -I/home/shiyu/Documents/compression/rdkit/Code/

**Output:**
In file included from rdkit.cpp:1:0:
/home/shiyu/Documents/compression/rdkit/Code/GraphMol/GraphMol.h:15:10: fatal error: RDGeneral/export.h: No such file or directory
 #include <RDGeneral/export.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Expected behavior**
To test whether i cite the rdkit code correctly.
Expected can print test string.

**Screenshots**
![image](https://github.com/rdkit/rdkit/assets/150132532/74626bdc-6794-4deb-9a1c-1e6106b6ca59)

**Configuration (please complete the following information):**
 - RDKit version: 2024_03_3 Release.
 - OS: OpenSuse Linux 15.4
 - Are you using conda? None

**Comment by greglandrum** [comment] 2024-06-26 03:59
What commands did you use to build and install the RDKit?

**Comment by greglandrum** [comment] 2024-06-26 03:59
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.

**Closed by greglandrum** 2024-06-26 03:59 UTC
Labels: bug

**Comment by alphamol-basel** [comment] 2024-06-26 08:09
Thanks for you reminder.
