### ISSUE TITLE
Some tests still failing on less common platforms.

### ISSUE THREAD

**Issue by giallu** [rdkit/rdkit#2311] opened 2019-03-04 18:15 UTC
Apparently, the fix  for bug #1999 does not work on some platforms, as you can see from this failed ppc64le Fedora build:
https://kojipkgs.fedoraproject.org//work/tasks/9545/33109545/build.log

29: [22:18:53] Testing Github 1999: pickling atom map numbers >127 gives negative values
29: terminate called after throwing an instance of 'RDKit::MolPicklerException'
29:   what():  std::exception
 29/140 Test  #29: graphmoltestPickler ................Child aborted***Exception:   0.97 sec

**Comment by greglandrum** [comment] 2019-03-06 05:12
Thanks for reporting this @giallu 
I can guess what the problem is, but since I can't directly test on POWER8 hardware myself (at least I don't think I can), I can't confirm that.
Can you test to see if the fix on this branch works?
https://github.com/greglandrum/rdkit/tree/fix/github2311

Here's the diff:
```
diff --git a/Code/GraphMol/MolPickler.cpp b/Code/GraphMol/MolPickler.cpp
index 54b18a1b7..a12e65f55 100644
--- a/Code/GraphMol/MolPickler.cpp
+++ b/Code/GraphMol/MolPickler.cpp
@@ -1486,7 +1486,10 @@ Atom *MolPickler::_addAtomFromPickle(std::istream &ss, ROMol *mol,
         }
         int tmpInt;
         streamRead(ss, tmpChar, version);
-        if (tmpChar < 0 && version > 9000) {
+        // the test for tmpChar below seems redundant, but on at least
+        // the POWER8 architecture it seems that chars may be unsigned
+        // by default.
+        if ((tmpChar < 0 || tmpChar > 127) && version > 9000) {
           streamRead(ss, tmpInt, version);
         } else {
           tmpInt = tmpChar;
```

**Comment by giallu** [comment] 2019-03-07 07:06
Yep, it worked:
https://koji.fedoraproject.org/koji/taskinfo?taskID=33243830
Now digging for the failures on the other platforms.

**Comment by greglandrum** [comment] 2019-03-07 07:08
That's excellent!
If you can point me to other cross-platform failures like that I will clear up as many as I can with one PR.

**Comment by giallu** [comment] 2019-03-07 08:15
Now I'm having a look at the S390 failures (don't even know what's that :confused: ) and several are related to tests that are performed on libraries not built. Example, in: https://kojipkgs.fedoraproject.org//work/tasks/3835/33243835/build.log

We can see:
```
BUILDSTDERR: Skipping build of SimDivPickers on big endian system
BUILDSTDERR: Skipping build of clustering and cmim libraries on big endian system
```
And later:
```
Start 134: pythonTestDirDataStructs
134: Test command: /usr/bin/python3 "/builddir/build/BUILD/rdkit-Release_2018_09_2/python3/rdkit/DataStructs/test_list.py" "--testDir" "/builddir/build/BUILD/rdkit-Release_2018_09_2/python3/rdkit/DataStructs"
134: Test timeout computed to be: 10000000
134: Traceback (most recent call last):
134:   File "UnitTestDocTests.py", line 16, in <module>
134:     from rdkit.Chem.Fingerprints.FingerprintMols import FingerprinterDetails
134:   File "/builddir/build/BUILD/rdkit-Release_2018_09_2/python3/rdkit/Chem/Fingerprints/FingerprintMols.py", line 32, in <module>
134:     from rdkit.ML.Cluster import Murtagh
134:   File "/builddir/build/BUILD/rdkit-Release_2018_09_2/python3/rdkit/ML/Cluster/Murtagh.py", line 17, in <module>
134:     from rdkit.ML.Cluster.Clustering import MurtaghCluster, MurtaghDistCluster
134: ModuleNotFoundError: No module named 'rdkit.ML.Cluster.Clustering'
134: ......FF.F.F..UnitTestcBitVect.py:42: DeprecationWarning: Please use assertRaisesRegex instead.
134:   with self.assertRaisesRegexp(IndexError, ""):
```

**Comment by greglandrum** [comment] 2019-03-07 08:28
"The IBM System/390 was the third major generation of the System/360 line of computers, introduced in 1990 and superseded in 2000." (https://en.wikipedia.org/wiki/IBM_System/390)

Not exactly super relevant, :-)

Still, it's easy enough to detect if those modules haven't been built and skip the relevant tests.

**Comment by giallu** [comment] 2019-03-07 08:33
Yeah, I don't even know why the builds are blocked on these platforms failures, but well...

On the other hand, both armv7hl and i686 (again, not really "modern" stuff) seem to be stuck on the enumeration test #56:
https://koji.fedoraproject.org/koji/getfile?taskID=33243836&volume=DEFAULT&name=build.log&offset=-4000

**Comment by greglandrum** [comment] 2019-03-07 10:00
The hang in testEnumeration on 32bit systems is #2209 
It's fixed and will be in the next patch release (should have been in the last one, but I forgot to tag the issue properly).

**Comment by giallu** [comment] 2019-03-08 06:48
Ok, I applied the patch in #2209 and kicked a new build;
https://koji.fedoraproject.org/koji/taskinfo?taskID=33269633

Enumeration now passing, but I've got 39 python tests failing (most of them with a segfault) in i686 and armv7:
https://kojipkgs.fedoraproject.org//work/tasks/9637/33269637/build.log

something else still going on in s390, but it seems we're getting there...

**Comment by greglandrum** [comment] 2019-03-08 06:59
Many of those i686 failures really look like there's a problem with the python installation.
That many segfaults, and all in python tests, tends to point to a library mismatch. Often this is because the RDKit was built against a different version of numpy or boost-python than what is begin found when the tests are run

**Comment by greglandrum** [comment] 2019-03-08 07:01
I'm looking into the s390 things now, but I suspect that this system may need to be removed from the build matrix. Given how old it is, that doesn't strike me as a huge problem... I don't think there are likely to be all that many people using the RDKit on 20 year old minicomputers. :-)

**Comment by greglandrum** [comment] 2019-03-08 09:32
Could you please try: https://github.com/greglandrum/rdkit/tree/fix/github2311_rel
and see if that helps?
That branch is relative to the 2018_09_2 release, so it should be reasonably easy to apply the corresponding diff

**Comment by greglandrum** [comment] 2019-03-08 10:45
@giallu : there was a stupid typo in that branch. I'm running the CI build again, but you should hold off until at last part of this build passes: 
https://travis-ci.org/greglandrum/rdkit/builds/503541793
sorry about that

**Closed** 2019-04-04 08:21 UTC
Labels: bug
