### ISSUE TITLE
AttributeError: module 'pandas.io.formats.format' has no attribute 'get_adjustment'

### ISSUE THREAD

**Issue by llvllahsa** [rdkit/rdkit#7492] opened 2024-06-05 13:39 UTC
I want to run reinvent4, and when I do so, I receive this error in rdk part:

`File "my/address/lib/python3.10/site-packages/rdkit/Chem/PandasPatcher.py", line 263, in patchPandas
    if getattr(pandas_formats.format, get_adjustment_name) != patched_get_adjustment:
AttributeError: module 'pandas.io.formats.format' has no attribute 'get_adjustment'
`

I am not sure how this can be resolved. I also checked the previous issues and one was similar related to few years ago. I checked the patch file there and PandasPatcher.py looked the same as the one mentioned there. So, the explanation there did not resolve the issue on my system.

**To Reproduce**
I think simply by installing reinvent4, and running the command to generate samples, you will get the error using the configuration I have introduced later.

**Expected behavior**
I expect that reinvent produces a set of molecules for me when the program runs successfully. 

**Configuration (please complete the following information):**
 - Python=3.10
 - Pandas=2.2.2
 - RDKIT=2024.03.3
 - OS: Ubuntu 22.04.4 LTS
 - Are you using conda? No. Micromamba.
 - If you are not using conda: how did you install the RDKit? with the command micromamba install rdkit

**Comment by llvllahsa** [comment] 2024-06-06 06:48
By changing Pandas version from 2.2.2 to 2.0.0 in the environment, the issue was resolved.

**Comment by ptosco** [comment] 2024-06-06 08:20
I am reopening this as the root issue needs to be fixed in `rdkit.Chem.PandasTools`.
Downgrading `pandas` is certainly a viable workaround until the root issue is fixed.

**Comment by ptosco** [comment] 2024-06-21 15:30
I cannot reproduce the issue on a fresh `pandas-2.2.2` install. Looking at the error reported above:
```
File "my/address/lib/python3.10/site-packages/rdkit/Chem/PandasPatcher.py", line 263, in patchPandas if getattr(pandas_formats.format, get_adjustment_name) != patched_get_adjustment: AttributeError: module 'pandas.io.formats.format' has no attribute 'get_adjustment' 
```
it looks like in your installation at `my/address/lib/python3.10/site-packages/rdkit/Chem/PandasPatcher.py` you might have a `PandasPatcher.py` from an older version rather than the one from `2024.03.3`, because the contents of `rdkit/Chem/PandasPatcher.py` in `2024.03.3` at line 263 are different:
https://github.com/rdkit/rdkit/blob/5d3c7f1df98829bb0f909f83037f508741f7a404/rdkit/Chem/PandasPatcher.py#L263

Therefore I am closing this as it is not a bug with RDKit.

**Closed by ptosco** 2024-06-21 15:30 UTC
Labels: bug
