### ISSUE TITLE
Illegal instruction on Chem.MolFromSmiles

### ISSUE THREAD

**Issue by gokhantahil** [rdkit/rdkit#3814] opened 2021-02-15 13:59 UTC
Hello, 

When using MolFromSmiles function, I get "Illegal instruction" error for some "smile" values:
  
`from rdkit import Chem`
`print(Chem.MolFromSmiles('C1NCN1.C1NCN1'))`
`print(Chem.MolFromSmiles('CC1CCCCC1'))`
`print(Chem.MolFromSmiles('Cc1ccccc1'))`
`print(Chem.MolFromSmiles('CC1=C(C(=CC=C1)NC2=CC=CC=C2C(=O)O)C'))`

and the output is:
`<rdkit.Chem.rdchem.Mol object at 0x7fa989a42170>`
`<rdkit.Chem.rdchem.Mol object at 0x7fa989a42170>`
`Illegal instruction`

When I remove the third print I get the same error on the last line.

I was expecting to get a rdkit object but got an error. 

RDKit version: 2020.09.4
OS: Ubuntu 20.04
Python version (if relevant): 3.8.5
Are you using conda? : Yes
If you are using conda, which channel did you install the rdkit from? : conda-forge

Thanks

**Comment by greglandrum** [comment] 2021-02-15 14:05
The issue template asks you a series of questions that make it easier for us to help.
The fact that you've either deleted those or only answered a subset of them makes it more difficult for us to help, so I'm closing this issue.

Please feel free to edit the issue description to include the requested information and reopen the issue and then we'll try to help.

**Comment by gokhantahil** [comment] 2021-02-15 14:28
How can I reopen @greglandrum ? Thanks.

**Comment by greglandrum** [comment] 2021-02-15 14:36
Do you see this button when you create a comment?
![image](https://user-images.githubusercontent.com/540511/107959370-9ed45500-6fa3-11eb-988b-b279a9e99cb0.png)

**Comment by gokhantahil** [comment] 2021-02-15 14:52
No there is not a button like that. May be it's because of I'm not the one closing the topic. Should i open another issue or can you reopen it ? 

**

> you cannot re-open your own issues if a repo collaborator closed them

**

https://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github

**Comment by greglandrum** [comment] 2021-02-15 15:05
Thanks for the additional info.
I am unable to reproduce this on ubuntu 20.04 using the conda-forge install of the RDKit.
Are you sure that this is exactly the script that you ran?
```
from rdkit import Chem
print(Chem.MolFromSmiles('C1NCN1.C1NCN1'))
print(Chem.MolFromSmiles('CC1CCCCC1'))
print(Chem.MolFromSmiles('Cc1ccccc1'))
print(Chem.MolFromSmiles('CC1=C(C(=CC=C1)NC2=CC=CC=C2C(=O)O)C'))
```

**Comment by gokhantahil** [comment] 2021-02-15 15:09
@greglandrum Thanks for your answer.
Yes that's exatly the same one that I ran. There are no missing or extra lines.

**Comment by bp-kelley** [comment] 2021-02-15 15:41
Could you give us the results of

lscpu

In case it’s a cpu instruction issue?

**Comment by gokhantahil** [comment] 2021-02-15 15:44
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    2
Core(s) per socket:    2
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 54
Model name:            Intel(R) Atom(TM) CPU N2800   @ 1.86GHz
Stepping:              1
CPU MHz:               919.286
CPU max MHz:           1862.0000
CPU min MHz:           798.0000
BogoMIPS:              3733.16
L1d cache:             24K
L1i cache:             32K
L2 cache:              512K
NUMA node0 CPU(s):     0-3
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts nopl nonstop_tsc cpuid aperfmperf pni dtes64 monitor ds_cpl est tm2 ssse3 cx16 xtpr pdcm movbe lahf_lm dtherm arat

**Comment by bp-kelley** [comment] 2021-02-15 17:21
I expect the issue might be you are running an intel atom which doesn’t support AVX.  This is very tough for us to test as we don’t have that particular hardware.

----
Brian Kelley

**Comment by greglandrum** [comment] 2021-02-15 18:22
Yeah, I think this is a conda-forge thing. I will transfer the issue there (if I can)

**Comment by gokhantahil** [comment] 2021-02-15 23:14
Thank you so much. I will be waiting for more information. Normally I would expect at least the two lines below to give the same result. 

`print(Chem.MolFromSmiles('CC1CCCCC1'))`
`print(Chem.MolFromSmiles('Cc1ccccc1'))`

It is really interesting.

**Comment by jaimergp** [comment] 2021-02-16 08:58
Maybe one can emulate the missing instruction through QEmu virtualization?

**Comment by greglandrum** [comment] 2021-02-17 13:13
Closing this because it's not actually an RDKit bug.

**Closed by greglandrum** 2021-02-17 13:13 UTC
Labels: bug
