### ISSUE TITLE
With kekulize=False, '*1:*:*:1' fails to be rendered with an inner dotted triangle

### ISSUE THREAD

**Issue by shenkin** [rdkit/rdkit#1095] opened 2016-10-12 01:51 UTC
The attached .ipynb produces two depictions. The first (cyclopropenium) was discussed in [issue #1094](https://github.com/rdkit/rdkit/issues/1094). This issue deals with the second one.

This issue is for `*1:*:*:1`, the cyclopropane skeleton with dummy atoms and explicit aromatic bonds. Since the depiction (second image below) is done with kekulize=False, the molecule should be displayed like cyclopropenium; namely, aromaticity should be indicated by an inner dotted triangle. Instead, one edge is shown with a double bond, which is the way cyclopropenium is displayed with kekulize=True.

As a comment, if a similar SMILES is instead constructed with explicit single bonds, the molecule is correctly depicted as cyclopropane (aliphatic, no double bonds). This strengthens the case that the current molecule is indeed recognized as aromatic, but is improperly rendered when kekulize=False is specified.

![problem-depictions](https://cloud.githubusercontent.com/assets/3138991/19294603/1fc0b28a-8ffc-11e6-958d-22592617931d.png)

[Problem-depictions.ipynb.zip](https://github.com/rdkit/rdkit/files/523336/Problem-depictions.ipynb.zip)

**Comment by greglandrum** [comment] 2016-10-12 03:04
This isn't a rendering thing.
When the molecule with the dummies is read in and sanitized the aromaticity is removed:
```
In [6]: m = Chem.MolFromSmiles('*:1:*:*:1')

In [7]: m.Debug()
Atoms:
	0 0 * chg: 0  deg: 2 exp: 2 imp: 0 hyb: 0 arom?: 0 chi: 0
	1 0 * chg: 0  deg: 2 exp: 3 imp: 0 hyb: 0 arom?: 0 chi: 0
	2 0 * chg: 0  deg: 2 exp: 3 imp: 0 hyb: 0 arom?: 0 chi: 0
Bonds:
	0 0->1 order: 1 conj?: 0 aromatic?: 0
	1 1->2 order: 2 conj?: 0 aromatic?: 0
	2 0->2 order: 1 conj?: 0 aromatic?: 0
```
This happens because the RDKit no longer assigns aromaticity to rings that are constructed completely of dummies.

If you would like to maintain the aromaticity, you'll have to work with partially sanitized molecules.

**Comment by greglandrum** [comment] 2016-10-12 03:05
(flagging this as invalid because it's not a bug)

**Comment by shenkin** [comment] 2016-10-12 06:57
> you'll have to work with partially sanitized molecules

Or perhaps unsanitized molecules. For this all-dummy system, the following renders the structure with an interior dotted-line:

`mol = Chem.MolFromSmiles(mol.SMILES, sanitize=False)`

... then using `kekulize=False` when adding it to MolsToGridImage().

I think this will suffice for my purpose, but for the record, the atoms are still not considered aromatic, though the ring now is. I haven't found a way to have RDKit perceive the dummy atoms as aromatic. 

Thanks for your help....

Finally, as a heads-up, the text at http://www.rdkit.org/docs/Cookbook.html#miscellaneous-topics refers to indole, but the associated image depicts phenol.

**Comment by shenkin** [comment] 2016-10-12 07:02
For the record, if I create the mol using `Chem.MolFromSmiles(mol.SMILES, sanitize=False) `, then add it to the grid with `kekulize=False`, I get my desired behavior, even though the dummies are still viewed as non-aromatic. I don't see a way to get the dummies perceived as aromatic, but I think what I have now will suffice for my purposs. Thanks for your help, as always....

Finally, as a heads-up, at http://www.rdkit.org/docs/Cookbook.html#miscellaneous-topics, the text refers to indole, but the image is of phenol.

**Comment by greglandrum** [comment] 2016-10-12 07:33
Yeah, that documentation mistake has been fixed in github:
https://github.com/rdkit/rdkit/blob/master/Docs/Book/Cookbook.md#using-a-different-aromaticity-model

**Comment by greglandrum** [comment] 2016-10-12 07:40
Re: aromaticity of the dummy atoms
If you'd like that flag set, you can always do something like this:
```
In [7]: m = Chem.MolFromSmiles('*:1:*:*:1',sanitize=False)

In [8]: Chem.SanitizeMol(m,sanitizeOps=Chem.SANITIZE_ALL^Chem.SANITIZE_KEKULIZE)
Out[8]: rdkit.Chem.rdmolops.SanitizeFlags.SANITIZE_NONE

In [9]: for match in m.GetSubstructMatches(Chem.MolFromSmarts('[$(*:*)]')):
   ...:     m.GetAtomWithIdx(match[0]).SetIsAromatic(True)
   ...:     

In [10]: m.Debug()
Atoms:
	0 0 * chg: 0  deg: 2 exp: 3 imp: 0 hyb: 0 arom?: 1 chi: 0
	1 0 * chg: 0  deg: 2 exp: 3 imp: 0 hyb: 0 arom?: 1 chi: 0
	2 0 * chg: 0  deg: 2 exp: 3 imp: 0 hyb: 0 arom?: 1 chi: 0
Bonds:
	0 0->1 order: 12 conj?: 1 aromatic?: 1
	1 1->2 order: 12 conj?: 1 aromatic?: 1
	2 0->2 order: 12 conj?: 1 aromatic?: 1
```

**Comment by shenkin** [comment] 2016-10-12 07:53
Interesting. I don't understand the individual sanitize flags well enough to understand exactly how they work. But the main trick appears to be the use of SetIsAromatic(), which  I didn't know about.

Thanks again, and good night!
-P.

**Closed** 2016-10-14 04:37 UTC
Labels: invalid
