### ISSUE TITLE
error:could not triangle bounds smooth molecular

### ISSUE THREAD

**Issue by lonngxiang** [rdkit/rdkit#5889] opened 2022-12-22 03:40 UTC
After using the EmbedMolecule parameter coordMap，run AllChem.EmbedMolecule( ) error; if the result is equal to -1, what is the meaning?

**Comment by greglandrum** [comment] 2022-12-25 07:27
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.

**Closed by greglandrum** 2022-12-25 07:27 UTC
Labels: bug
