### ISSUE TITLE
Strange hybridization results for hydrogen 

### ISSUE THREAD

**Issue by JulianKimmig** [rdkit/rdkit#3643] opened 2020-12-14 10:49 UTC
**Describe the bug**
I stumbled over a strange behaviour when detecting the full hybridization of molecules including hydrogens:
If the specific isotope is specified in the smiles (e.g. [1H]) the resulting hybridization is S whereas if no isotope is specified the result is UNDEFINED.
Shouldn't be the result the same in every case?

**To Reproduce**
```python
from rdkit import Chem

mol = Chem.MolFromSmiles('[2H]C([2H])([2H])C(=O)C([2H])([2H])[2H]')
for atom in mol.GetAtoms():
    print(atom.GetSymbol(), atom.GetHybridization())

print("-"*20)

mol = Chem.MolFromSmiles('[1H]C([1H])([1H])C(=O)C([1H])([1H])[1H]')
mol = Chem.AddHs(mol)
for atom in mol.GetAtoms():
    print(atom.GetSymbol(), atom.GetHybridization())
    
print("-"*20)

mol = Chem.MolFromSmiles('[H]C([H])([H])C(=O)C([H])([H])[H]')
mol = Chem.AddHs(mol)
for atom in mol.GetAtoms():
    print(atom.GetSymbol(), atom.GetHybridization())
```
Output:
```
H S
C SP3
H S
H S
C SP2
O SP2
C SP3
H S
H S
H S
--------------------
H S
C SP3
H S
H S
C SP2
O SP2
C SP3
H S
H S
H S
--------------------
C SP3
C SP2
O SP2
C SP3
H UNSPECIFIED
H UNSPECIFIED
H UNSPECIFIED
H UNSPECIFIED
H UNSPECIFIED
H UNSPECIFIED
```

**Expected behavior**
Intuitivly I would expect the result to be UNDEFINED in all cases since hydrogen should usually not be able to form hybrid orbitales.
(In general I'm not shure when s-hybridization takes place, but I guess it might be possible for higher s orbitals to combine with lower ones?)

**Configuration:**
 - RDKit version: '2020.03.5'

**Comment by greglandrum** [comment] 2020-12-17 09:24
I can see why you'd think this is a bug, but it is the expected behavior. Here's what's going on:

Hybridization is assigned when the molecule is santized. This normally happens on parsing.
In your last example all of the Hs you provided are removed when the molecule is parsed since no isotope is specified. This is different from the first examples, where the Hs in the input SMILES have isotopes specified and are thus preserved.

AddHs() adds molecules back to the molecule, but does not set hybridization.

If you want to have Hs with hybridization assigned, you have two choices:

*1.* don't remove the Hs at all when parsing the input:
```
In [3]: ps = Chem.SmilesParserParams()

In [4]: ps.removeHs = False

In [5]: mol = Chem.MolFromSmiles('[H]C([H])([H])C(=O)C([H])([H])[H]')

In [6]: for atom in mol.GetAtoms():
   ...:     print(atom.GetSymbol(), atom.GetHybridization())
   ...: 
C SP3
C SP2
O SP2
C SP3

In [7]: ps = Chem.SmilesParserParams()

In [8]: ps.removeHs = False

In [9]: mol = Chem.MolFromSmiles('[H]C([H])([H])C(=O)C([H])([H])[H]',ps)

In [10]: for atom in mol.GetAtoms():
    ...:     print(atom.GetSymbol(), atom.GetHybridization())
    ...: 
H S
C SP3
H S
H S
C SP2
O SP2
C SP3
H S
H S
H S
```

*2.* Reassign hybridization after you call AddHs() by calling `SetHybridization()`:
```
In [11]: mol = Chem.MolFromSmiles('[H]C([H])([H])C(=O)C([H])([H])[H]')

In [12]: mol = Chem.AddHs(mol)

In [13]: Chem.SetHybridization(mol)

In [14]: for atom in mol.GetAtoms():
    ...:     print(atom.GetSymbol(), atom.GetHybridization())
    ...: 
C SP3
C SP2
O SP2
C SP3
H S
H S
H S
H S
H S
H S
```

**Closed** 2020-12-17 10:01 UTC
Labels: not a bug
