### ISSUE TITLE
how to read the smiles from the table and convert it to 3d rdkit objects in streamlit python 

### ISSUE THREAD

**Issue by acchu69** [rdkit/rdkit#6137] opened 2023-02-27 08:13 UTC
how can i read the smiles from this table and convert these to 3d objects ..
below is ss of the table 

![jj](https://user-images.githubusercontent.com/115561112/221508528-c0243105-584a-4db6-9cf5-9630112ad998.png)

**Comment by acchu69** [comment] 2023-02-27 08:18
code:
st.header('**3D Visualization**')
    df = pd.DataFrame(load_data[0])
    smiles_list = df.smiles.astype(str).to_list()
    mol_list = [Chem.MolFromSmiles(smiles_list) for smiles in smiles_list]
    img = Draw.MolsToGridImage(mol_list)
    st.write(img)
error:
'DataFrame' object has no attribute 'smiles'

**Comment by churnikov** [comment] 2023-02-28 07:59
Hi!
It seems to not be a problem with rdkit, but with your code:
When you are trying to access `df.smiles` on the line 3, you are trying to access a column that does not exist. You should change this line to the following: `smiles_list = df["Molecular Structure"].astype(str).to_list()`

**Comment by acchu69** [comment] 2023-02-28 16:48
resolved the issue  and i modified it the code to :

# Model building
def build_model(input_data):
    # Reads in saved regression model
    load_model = pickle.load(open('acetylcholinesterase_model.pkl', 'rb'))
    # Apply model to make predictions
    prediction = load_model.predict(input_data)
    st.header('**Prediction output**')
    prediction_output = pd.Series(prediction, name='pIC50')
    molecule_name = pd.Series(load_data[1], name='molecule_name')
    smiles_notations = pd.Series(load_data[0], name='Molecular Structure')
    df = pd.concat([molecule_name, prediction_output, smiles_notations], axis=1)
    st.write(df)
    st.markdown(filedownload(df), unsafe_allow_html=True)
    st.header('**Molecular Structures**')
    for i, smiles in enumerate(load_data[0]):
        mol = Chem.MolFromSmiles(smiles)
        if mol:
            mol = Chem.AddHs(mol)
            AllChem.EmbedMolecule(mol)
            drawer = rdMolDraw2D.MolDraw2DCairo(300, 300)
            drawer.DrawMolecule(mol)
            drawer.FinishDrawing()
            img = drawer.GetDrawingText()
            st.image(img, caption=f'Molecule {i+1}')

and its working thanks

**Comment by greglandrum** [comment] 2023-03-01 05:38
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.

**Closed by greglandrum** 2023-03-01 05:38 UTC
Labels: bug
