### ISSUE TITLE
JavaWrapper SWIG not generating libGraphMol.so

### ISSUE THREAD

**Issue by tnguy271** [rdkit/rdkit#5606] opened 2022-09-29 17:49 UTC
Hi everyone,

After using cmake and make to build the java wrapper for rdkit, I only have the files org.RDKit.jar, and org.RDKitDoc.jar in gmwrapper folder. I'm missing the libGraphMolWrap.so file but instead I have GraphMolJava.i. Can someone help me please. 

Thank you

**Comment by ptosco** [comment] 2022-09-30 10:46
I am closing this as the Java wrappers build without errors on the current `master` branch. Please repost your question in the [Discussions](https://github.com/rdkit/rdkit/discussions) tab. Also, check your build logs since if the library is not generated most likely the build has failed with some error message that will help you figure out where the problem is.
These are the contents of my `$RDBASE/Code/JavaWrappers/gmwrapper` after a successful build:
```
$ ls Code/JavaWrappers/gmwrapper/
build  build-test  CMakeLists.txt  doc  GraphMolJava.i  libGraphMolWrap.so  org.RDKitDoc.jar  org.RDKit.jar  src  src-test  std_list.i
```

**Closed by ptosco** 2022-09-30 10:46 UTC
Labels: bug
