### ISSUE TITLE
The transformation of mol into smiles is implemented by the deep search method?

### ISSUE THREAD

**Issue by codeking01** [rdkit/rdkit#5682] opened 2022-10-24 13:37 UTC
-----------------------------------------

If you have a question about the RDKit please use the Discussions tab above (https://github.com/rdkit/rdkit/discussions) instead of posting it here.

If you have a suggestion for a new RDKit feature or enhancement please consider starting a discussion about it using the Discussions tab above (https://github.com/rdkit/rdkit/discussions) before creating an issue. Community input on how a feature could work is often helpful and it could be that there's already a way to do what you want to do in the RDKit.

PLEASE DELETE THIS SECTION AFTER YOU HAVE READ IT

-----------------------------------------

**Is your feature request related to a problem? Please describe.**
Dear autor,I want to know whether the transformation of mol into smiles is implemented by the deep search method. Could you please provide the entry of the key code

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by greglandrum** [comment] 2022-10-24 13:42
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.

**Closed by greglandrum** 2022-10-24 13:42 UTC
Labels: enhancement
