### ISSUE TITLE
AdjustQueryParameters

### ISSUE THREAD

**Issue by Flora-Feng0532** [rdkit/rdkit#4335] opened 2021-07-13 12:13 UTC
I got into a problem when trying to do substructure matching of scaffolds:

Scaffold 1: O=c1oc2ccccc2[nH]1
Scaffold 2: c1(ocn2)c2cccc1
Molecule: O=S(N1CCN(C1)c2ncncc2)(c(cc3)cc4c3oc(=O)[nH]4)=O

What I want:
Molecule.HasSubstructureMatch(scaffold 1) --> True
Molecule.HasSubstructureMatch(scaffold 2) --> False

In fact, Molecule believes it has both patterns.

I tried many ways, like ignore explicit Hs, set adjustDegree=True in Chem.AdjustQueryParameters()...
It didnt work unless I was able to define H0(hydrogen zero) in SMARTS strings.
I was hopping is there any solution to this situation?

**Comment by greglandrum** [comment] 2021-07-13 12:16
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.

**Closed by greglandrum** 2021-07-13 12:16 UTC

**Comment by Flora-Feng0532** [comment] 2021-07-13 12:23
Sorry! this is a typo!
