### ISSUE TITLE
Wavefunction for a monoatomic molecule

### ISSUE THREAD

**Issue by teltim** [rdkit/rdkit#6417] opened 2023-05-31 12:52 UTC
https://forum.psicode.org/t/wavefunction-for-a-monoatomic-molecule/2813/6

Referring to the above question, I also estimate wavefuntion for monoatomic moleclue such as Ne, Xe, Ar ... 

But, I met the same error?
Are there any solution on this issue?

**Comment by jasondbiggs** [comment] 2023-05-31 15:31
- When reporting an issue, please include a self-contained example of *RDKit* code that demonstrates the issue.
- "monoatomic moleclue" - so an atom?
- the RDKit message being printed from your Psi4 code clearly states that "Ar" is not a valid SMILES string, use "[Ar]"

**Comment by greglandrum** [comment] 2023-06-01 07:02
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.

**Closed by greglandrum** 2023-06-01 07:02 UTC
Labels: bug

**Comment by teltim** [comment] 2023-06-01 08:56
I understood, thank you for the comment
