### ISSUE TITLE
AtomValenceException for transition metal anion

### ISSUE THREAD

**Issue by simonmb** [rdkit/rdkit#7746] opened 2024-08-22 21:57 UTC
**Describe the bug**
for the following anion: `[Co+2]([Br-])([Br-])([Br-])([Br-])`, I would have expected the valence for the Br- atoms to be one. However, I keep getting a AtomValenceException like: `Explicit valence for atom # 1 Br, 2, is greater than permitted` Hopefully, I am not making a mistake.

**To Reproduce**
```python
mol = Chem.MolFromSmiles('[Co+2]([Br-])([Br-])([Br-])([Br-])', sanitize=False)
mol.UpdatePropertyCache(strict=False)
Chem.RemoveHs(mol)
```

I am aware that in this case removing Hs makes no sense. But the code is part of a larger project and happens to get executed for thousands of molecules including this one.

**Configuration (please complete the following information):**
 - RDKit version: 2023.03.1
 - OS: Windows 10
 - Python version: 3.11

**Comment by greglandrum** [comment] 2024-08-23 02:57
Hi @simonmb, the problem here is that `RemoveHs()` also sanitizes the molecule by default, you need to tell it not to do so:
```
newMol = Chem.RemoveHs(mol,sanitize=False)
```
Note that Chem.RemoveHs() does not modify the input molecule: it returns a new mol with the Hs removed.

As for the valence of the Br in this molecule: each bromine has a single bond and a negative charge; that corresponds to a valence of two. From the RDKit's perspective: Br- is isoelectronic to Kr, so it should not have any bonds to it.

**Comment by simonmb** [comment] 2024-08-23 05:47
Hi @greglandrum, thanks for the fast response. Then I am wondering if I have my SMILES wrong? After reading your comments, I searched online and I found `[Co-2](Br)(Br)(Br)(Br)` which does not lead to the same problem.

**Comment by simonmb** [comment] 2024-08-23 06:56
Hi @greglandrum, just for the future, to make sure I am doing everything correctly, for the following halogen containing molecules, are the SMILES ok, or am I missing something? If I do not turn off sanitization, rdkit is unable to create a molecule out of them,

Chlorine trifluoride FCl(F)F
Chlorine pentafluoride FCl(F)(F)(F)F
Perchloryl fluoride O=Cl(=O)(=O)F
Bromine trifluoride FBr(F)F
Bromine pentafluoride F[Br](F)(F)(F)F
iodine pentafluoride oxide F[I](F)(F)(F)(F)=O
Iodine heptafluoride FI(F)(F)(F)(F)(F)F

**Comment by greglandrum** [comment] 2024-09-01 13:40
@simonmb the RDKit does not by default recognize many hypervalent molecules; this is what you are observing here. If you want to support these non-classical species you need to disable the default sanitization and do something more custom.
This requires thinking about what you need and reading through the docs on what the existing sanitization functions do so that you know what pre-built tools are available to you and what you will need to build yourself

**Comment by greglandrum** [comment] 2024-09-01 13:41
I'm closing this because it's not a bug.

**Closed** 2024-09-01 13:41 UTC
