### ISSUE TITLE
Gasteger charges are NaN

### ISSUE THREAD

**Issue by bkagroup** [rdkit/rdkit#2674] opened 2019-10-01 10:59 UTC
Was trying to calculate Gasteiger charges for `C[NH+]1C=NC=C1.F[P-](F)(F)(F)(F)F`.  Returns nan for P and F atoms. 

0.012116324006130183
-0.34056785662789607
0.09427933059631977
-0.24523724789783408
0.0448021594653024
0.022958584468483076
nan
nan
nan
nan
nan
nan
nan

**Comment by greglandrum** [comment] 2019-10-01 15:06
This is because the Gasteiger charging scheme doesn't have parameters for the hexavalent P atom. The only supported P hybridization is `sp3`.

You can solve the problem in this particular case by stripping salts from the molecule and just calculating charges on the parent.

Here's an example of that:
```
In [11]: from rdkit.Chem.MolStandardize import rdMolStandardize                                                                                                                                                     

In [12]: salt_remover = rdMolStandardize.FragmentRemover()                                                                                                                                                          

In [13]: m = Chem.MolFromSmiles('C[NH+]1C=NC=C1.F[P-](F)(F)(F)(F)F')                                                                                                                                                

In [14]: parent = salt_remover.remove(m)                                                                                                                                                                            
[17:03:29] Running FragmentRemover
[17:03:29] Removed fragment: hexafluorophosphate

In [15]: Chem.SanitizeMol(parent)                                                                                                                                                                                   
Out[15]: rdkit.Chem.rdmolops.SanitizeFlags.SANITIZE_NONE

In [16]: rdPartialCharges.ComputeGasteigerCharges(parent)                                                                                                                                                           

In [18]: print(Chem.MolToSmiles(parent))                                                                                                                                                                            
C[NH+]1C=CN=C1

In [19]: for at in parent.GetAtoms(): 
    ...:     print(at.GetDoubleProp('_GasteigerCharge')+at.GetDoubleProp('_GasteigerHCharge')) 
    ...:      
    ...:                                                                                                                                                                                                            
0.3445692953561144
0.09258548891999296
0.3445883166016806
-0.20590917523699315
0.17599443160092182
0.2481716427582832
```

**Comment by greglandrum** [comment] 2019-10-03 16:20
I'm closing this because it looks like the question is answered. Please reopen if necessary.

**Closed** 2019-10-07 07:27 UTC
Labels: question

**Comment by koyurion** [comment] 2020-12-18 09:50
Hi , I get almost nan of the ligands : "364"、“DUD”
# "364" : OC(CN1CCCC(C2CCCC(C3CCCCC3)C2)C1)([PH](O)(O)O)[PH](O)(O)O
# "DUD": OC1CCN(C2CC(O)C(CO[PH](O)(O)O[PH](O)(O)O)O2)C(O)N1
take "DUD" as an example:
[code]:
```
mol = Chem.MolFromSmiles('OC1CCN(C2CC(O)C(CO[PH](O)(O)O[PH](O)(O)O)O2)C(O)N1')

print(Chem.MolToSmiles(mol))
parent = salt_remover.remove(mol)
print(Chem.MolToSmiles(parent))

Chem.SanitizeMol(parent)
rdPartialCharges.ComputeGasteigerCharges(parent)
for a in parent.GetAtoms():
    print(a.GetSymbol() ,a.GetDoubleProp('_GasteigerCharge'), a.GetDoubleProp('_GasteigerHCharge'))
```
[output]:
O nan nan
C nan nan
C nan nan
C nan nan
N nan 0.0
C nan nan
C nan nan
C nan nan
O nan nan
C nan nan
C nan nan
O nan 0.0
P nan nan
O nan nan
O nan nan
O nan 0.0
P nan nan
O nan nan
O nan nan
O nan nan
O nan 0.0
C nan nan
O nan nan
N nan nan

**Comment by greglandrum** [comment] 2023-01-27 05:50
Since this keeps coming up and I forgot to mention it previously: if you want to have the code thrown an exception if Gasteiger parameters are missing, you can do so:
```
In [20]: rdPartialCharges.ComputeGasteigerCharges(Chem.MolFromSmiles("CC[O-].[Na+]"),throwOnParamFailure=True)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [20], in <module>
----> 1 rdPartialCharges.ComputeGasteigerCharges(Chem.MolFromSmiles("CC[O-].[Na+]"),throwOnParamFailure=True)

ValueError: ERROR: No Gasteiger Partial Charge parameters for Element: Na Mode: 
```

**Comment by koyurion** [comment] 2023-01-27 05:50
你好，你的邮件已收到。谢谢！

**Comment by libokj** [comment] 2023-05-12 11:24
> Since this keeps coming up and I forgot to mention it previously: if you want to have the code thrown an exception if Gasteiger parameters are missing, you can do so:
> 
> ```
> In [20]: rdPartialCharges.ComputeGasteigerCharges(Chem.MolFromSmiles("CC[O-].[Na+]"),throwOnParamFailure=True)
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> Input In [20], in <module>
> ----> 1 rdPartialCharges.ComputeGasteigerCharges(Chem.MolFromSmiles("CC[O-].[Na+]"),throwOnParamFailure=True)
> 
> ValueError: ERROR: No Gasteiger Partial Charge parameters for Element: Na Mode: 
> ```
I understand it's expected behavior that some atoms do not produce Gasteiger charges (especially when the molecule contains certain metal atoms). However, the example `OC1CCN(C2CC(O)C(COPH(O)OPH(O)O)O2)C(O)N1` provided by @koyurion contains only common non-metal elements, and none of the atoms' charges were calculated. Can we make sure this is the expected behavior?

**Comment by koyurion** [comment] 2023-05-12 11:24
你好，你的邮件已收到。谢谢！
