### ISSUE TITLE
Reaction that breaks a ring bond produces more atoms than put in

### ISSUE THREAD

**Issue by jasondbiggs** [rdkit/rdkit#5159] opened 2022-04-01 21:53 UTC
A reaction is defined that breaks a bond and forms two products.  When that reaction acts on a molecule and breaks a ring bond, we still get two products, and that doesn't seem right.  The consequence is that the same unmapped atoms can show up in multiple products:

```
rxn = AllChem.ReactionFromSmarts('[N:1][O:2]>>[N:1].[O:2]')
ps = rxn.RunReactants((Chem.MolFromSmiles('C1NO1'),))
for mol in ps[0]:
	print(MolToSmiles(mol))

CN

CO
```
The input molecule had only one carbon atom, and it went to both products.

Is this as designed?  Maybe a duplicate of issue #58?

**Comment by wopozka** [comment] 2022-04-04 12:21
This is actually the way it works. O rhs you explicite want 2 molecules and you are receiving 2 molecules. Internally it works (more or less) like NO bond is matched, bond is split and the rest is copied. As you want 2 seperate molecules on rhs the same atoms are copied to both oxygen and nitrogen. If you want chemically correct product put products in brakets: [N:1][O:2]>>([N:1].[O:2]).

**Comment by cottonkiet** [comment] 2022-04-23 13:27
Just for discussion. Is there a way that rdkit will automatically detect whether the bond to break is in a ring or not? As a result, it will automatically produce 2 products if the bond is not in a ring, while produce 1 if the bond is in a ring. Because this will be a problem for each cleavage reaction and it is a lot of trouble to define two reactions (one for ring compound, one for non-ring compound) for each cleavage reaction. After all, in daylight smarts, C.C include both (C).(C) and (C.C)

**Comment by wopozka** [comment] 2022-04-23 20:36
@cottonkiet 
In general it is quite safe to put brackets on RHS and post-process reaction to check whether there appeared 2 or 1 molecule as a result. But answering your question, it is very easy achievable by proper SMARTS definition on LHS. If there is no mach then, the reaction will not work. Here would be enough to mark bond to be in ring [N:1]@-[O:2], or not in the ring [N:1]!@-[O:2]

**Comment by cottonkiet** [comment] 2022-04-24 07:55
Thanks a lot! Since I have like 100 reactions so it might be easier to do post-process reaction check. Can you tell me some details about it?

**Comment by wopozka** [comment] 2022-04-25 08:03
@cottonkiet 
Correcting 100 reactions is really not a problem, couple of seconds each for the correction you want (adding brackets on RHS). But if you would like to postprocess, then you have to analyse starting material (whether it is single molecule) and analyse products (if single molecule is preserved). If you recognize that products contains two molecules instead of one, you need to merge these two moelcules into one.  It might be necesary to mark reaction centre (to see where was a match to the reaction) to be able to do it. I am not able to give you a ready solution as I would need to generate this algorithm from scratch. It is definitely durable (I know at least one commercial software doing that). Anyway, IMHO much better solution would be just add brackets to the RHS of reaction (even during reaction running, just by modifying string), and then rdkit should deal with a problem. As I said in most cases it is probably absolutely safe to do it, and it will solve you problem.

**Comment by cottonkiet** [comment] 2022-04-25 09:22
I see, thanks a lot!

**Comment by greglandrum** [comment] 2023-03-01 05:50
I'm going to close this because the code is working as designed. @wopozka's explanation of what's going on and why it's expected behavior is dead on.

**Closed by greglandrum** 2023-03-01 05:50 UTC
Labels: bug
