### ISSUE TITLE
Draw.MolsToGridImage doesn't work ??

### ISSUE THREAD

**Issue by ys0123** [rdkit/rdkit#3937] opened 2021-03-16 06:37 UTC
**Describe**

I've been trying to build rdkit from source in a few environments since anaconda isn't free these days.
At this time, I noticed the strange behavior of Draw.MolToImage() and Draw.MolsToGridImage ([]) of rdkit. 
```
Env.1: ubuntu16.04 rdkit2020.09.5(conda install rdkit) python3=3.8.3 python=3.8.3
Env.2: ubuntu18.04 rdkit2019.03.4(build from source) python3=3.6.9 python=2.7.17
Env.3: ubuntu20.04 rdkit2020.09.5(build from source) python3=3.8.5 python=not found
```
Env.1
<img width="397" alt="9105" src="https://user-images.githubusercontent.com/80317523/111265834-0d710500-866d-11eb-9395-7b9ce961b7d8.png">
Env.2
<img width="396" alt="9106" src="https://user-images.githubusercontent.com/80317523/111265840-0ea23200-866d-11eb-8592-8fe9d944f321.png">
Env.3
<img width="395" alt="9109" src="https://user-images.githubusercontent.com/80317523/111265841-0ea23200-866d-11eb-9acf-b050af22905f.png">

In Env1, both Draw.MolToImage and Draw.MolsToGridImage are displayed normally. 
However, in Env2, the lines of the structural image become thin and small.
Also, in MolsToGridImage of Env3, `FileNotFoundError: No such file or directory:` occurs. 

I want to get the same result as Env.1. How shoud I do?
Thanks for any help!

**Code**
```
from rdkit import Chem
from rdkit.Chem import Draw
benzene = Chem.MolFromSmiles('C1=CC=CC=C1')
Draw.MolToImage(benzene)

Draw.MolsToGridImage([benzene])
```

**Error Message**
```
TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.8/dist-packages/IPython/core/display.py in _data_and_metadata(self, always_both)
   1292         try:
-> 1293             b64_data = b2a_base64(self.data).decode('ascii')
   1294         except TypeError:

TypeError: a bytes-like object is required, not 'Image'

During handling of the above exception, another exception occurred:

FileNotFoundError                         Traceback (most recent call last)
/usr/local/lib/python3.8/dist-packages/IPython/core/formatters.py in __call__(self, obj)
    343             method = get_real_method(obj, self.print_method)
    344             if method is not None:
--> 345                 return method()
    346             return None
    347         else:

/usr/local/lib/python3.8/dist-packages/IPython/core/display.py in _repr_png_(self)
   1311     def _repr_png_(self):
   1312         if self.embed and self.format == self._FMT_PNG:
-> 1313             return self._data_and_metadata()
   1314 
   1315     def _repr_jpeg_(self):

/usr/local/lib/python3.8/dist-packages/IPython/core/display.py in _data_and_metadata(self, always_both)
   1293             b64_data = b2a_base64(self.data).decode('ascii')
   1294         except TypeError:
-> 1295             raise FileNotFoundError(
   1296                 "No such file or directory: '%s'" % (self.data))
   1297         md = {}

FileNotFoundError: No such file or directory: '<PIL.Image.Image image mode=RGBA size=600x200 at 0x7FECA1E2E460>'
```

**Comment by greglandrum** [comment] 2021-03-17 04:01
Env2 is running an older version of the RDKit and the molecular drawing code is something we've been working on a lot over the last few releases, so differences like this are to be expected.
I can't reproduce the problem you're seeing in the last example, but I would suggest including:
```
from rdkit.Chem.Draw import IPythonConsole
```
either directly before or directly after you import the `Draw` module so that you can be sure that the RDKit's integration with the jupyter notebook has been fully loaded.

**Comment by ys0123** [comment] 2021-03-17 06:22
```
from rdkit import Chem
from rdkit.Chem import Draw
from rdkit.Chem.Draw import IPythonConsole
benzene = Chem.MolFromSmiles('C1=CC=CC=C1')
Draw.MolsToGridImage([benzene])
```
I tried that code, but same error occurs.
Hmm..... I think my build method of rdkit may be no good.  but I don't know what is wrong.

**Comment by greglandrum** [comment] 2021-03-17 07:54
Yeah, sorry, this is more or less impossible to diagnose this way.
Your life would be a lot easier if you used conda for this. And before you repeat that "anaconda is no longer free", I would suggest that you read both the blog post from the CEO of anaconda: https://www.anaconda.com/blog/sustaining-our-stewardship-of-the-open-source-data-science-community
and this post from the conda-forge team: https://conda-forge.org/blog/posts/2020-11-20-anaconda-tos/

**Comment by ys0123** [comment] 2021-03-18 08:49
I can understand your suggestions. I will pay the cost if absolutely necessary, but first I would like to know a workaround that does not use conda.

Can you install boost and rdkit from source  and work fine on ubuntu 20.04LTS ,?

thanks.

**Comment by greglandrum** [comment] 2021-03-18 09:02
yes, my primary work machine runs ubuntu 20.04

**Comment by ys0123** [comment] 2021-03-18 09:09
If possible, Could you show me your build procedure?

I really appreciate for your info.

**Comment by greglandrum** [comment] 2021-04-12 07:23
The details of my specific build are unlikely to help you since they are tied to things like the version of boost which I installed.
Take a look at the installation instructions in the RDKit documentation and see if those help you. If not, please feel file a bug pointing out the documentation problem.

I'm closing this now because it's not an RDKit issue or feature request

**Closed by greglandrum** 2021-04-12 07:23 UTC
