### ISSUE TITLE
 Could NOT find Boost (missing: Boost_INCLUDE_DIR python) (Required is at   least version "1.58.0") - when installing from source

### ISSUE THREAD

**Issue by MKCarter** [rdkit/rdkit#7717] opened 2024-08-14 14:48 UTC
Hi,

I am tyring to install rdkit version 2023.03.01 from source on ubuntu 22.04. However, after running:

```
cd rdkit-Release_2023_03_1
mkdir build 
cd build
cmake -DPy_ENABLE_SHARED=1 \
  -DRDK_INSTALL_INTREE=ON \
  -DRDK_BUILD_AVALON_SUPPORT=ON \
  -DRDK_BUILD_INCHI_SUPPORT=ON \
  -DRDK_INSTALL_STATIC_LIBS=OFF \
  -DRDK_BUILD_CPP_TESTS=ON \
  -DRDK_BUILD_PYTHON_WRAPPERS=ON \
  -DRDK_BUILD_YAEHMOP_SUPPORT=ON \
  -DBoost_NO_SYSTEM_PATHS=ON \
  -DRDK_BUILD_CAIRO_SUPPORT=ON \
  -DRDK_BUILD_XYZ2MOL_SUPPORT=ON \
  -DRDK_BUILD_FREESASA_SUPPORT=ON \
  -DPYTHON_NUMPY_INCLUDE_PATH="$(python -c 'import numpy ; print(numpy.get_include())')" \
  -DBOOST_ROOT="$CONDA_PREFIX" \
  -DINCHI_URL=https://rdkit.org/downloads/INCHI-1-SRC.zip \
  ..
-- Found Catch2 source in /home/michaelcarter/DD_tools/roshambo/rdkit-Release_2023_03_1/External/catch/catch
CATCH: /home/michaelcarter/DD_tools/roshambo/rdkit-Release_2023_03_1/External/catch/catch/single_include/catch2
-- Could NOT find InChI in system locations (missing: INCHI_INCLUDE_DIR) 
CUSTOM_INCHI_PATH = /home/michaelcarter/DD_tools/roshambo/rdkit-Release_2023_03_1/External/INCHI-API
-- Found InChI software locally
CMake Warning at /usr/share/cmake-3.22/Modules/FindBoost.cmake:2201 (message):
  No header defined for python-py39; skipping header check (note: header-only
  libraries have no designated component)
Call Stack (most recent call first):
  CMakeLists.txt:305 (find_package)


CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR python) (Required is at
  least version "1.58.0")
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.22/Modules/FindBoost.cmake:2360 (find_package_handle_standard_args)
  CMakeLists.txt:313 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/michaelcarter/DD_tools/roshambo/rdkit-Release_2023_03_1/build/CMakeFiles/CMakeOutput.log".
```

It seems that rdkit cannot find my boost libraries. I have installed the required libraries using:
`sudo apt-get install libboost-all-dev`

I wonder if I have to specify their location? Does anyone know how to do this?

All the best,
Mike

**Comment by greglandrum** [comment] 2024-08-14 15:08
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.

**Closed by greglandrum** 2024-08-14 15:08 UTC
Labels: bug

**Comment by MKCarter** [comment] 2024-08-14 15:12
OK, will do!
