### ISSUE TITLE
The same molecule corresponds to a different 3D structure？

### ISSUE THREAD

**Issue by Mryangkaitong** [rdkit/rdkit#2382] opened 2019-04-01 10:02 UTC
**Description:**

```
m = Chem.MolFromSmiles('C1CCC1OC')
m2=Chem.AddHs(m)
m3=Chem.AddHs(m)
m4=Chem.AddHs(m)
m5=Chem.AddHs(m)

AllChem.EmbedMultipleConfs(m2, numConfs=2)
AllChem.EmbedMultipleConfs(m3, numConfs=2)
AllChem.EmbedMultipleConfs(m4, numConfs=2)
AllChem.EmbedMultipleConfs(m5, numConfs=2)

df = pd.DataFrame({'smile':'CC'},index=['a'])
df['s2'] = m2
df['s3'] = m3
df['s4'] = m4
df['s5'] = m5

df
```
![result](https://github.com/Mryangkaitong/python-Machine-learning/blob/master/photo/result.png)

 
Now that I want to achieve the same molecule and get the only definite 3D structure, what do I do? thanks

**Comment by greglandrum** [comment] 2019-04-01 14:46
The conformation generation procedure uses a random number generator for parts of the process. In order to get reproducible conformations, you need to provide the `randomSeed` argument to `AllChem.EmbedMultipleConfs`. Try doing something like:
`AllChem.EmbedMultipleConfs(m2, numConfs=2, randomSeed=42)`

**Comment by Mryangkaitong** [comment] 2019-04-03 08:35
> The conformation generation procedure uses a random number generator for parts of the process. In order to get reproducible conformations, you need to provide the `randomSeed` argument to `AllChem.EmbedMultipleConfs`. Try doing something like:
> `AllChem.EmbedMultipleConfs(m2, numConfs=2, randomSeed=42)`

OK ,thanks

**Comment by greglandrum** [comment] 2019-04-03 09:47
I'm closing this because it looks like the question is answered. Please reopen if necessary.

**Closed by greglandrum** 2019-04-03 09:47 UTC
Labels: question
