### ISSUE TITLE
Any strategy to generate a set of all possible kekulized structures from a single, unkekulized input? 

### ISSUE THREAD

**Issue by DaRinker** [rdkit/rdkit#8100] opened 2024-12-14 23:10 UTC
Can anyone suggest a reasonable strategy to generate a set of **_all_** valid Kekulé structures from a single, unkekulized input? 

For example, I would like to input the aromatic structure c2ccc1CCCc1c2 and get back both
C12=CC=CC=C1CCC2 and C12=C(CCC2)C=CC=C1

I don't know if this would actually be a feature request. My use case is that I am needing to generate chemical fingerprints from input aromatic compounds. I discovered that for at least some compounds, canonical smiles can end up shifting (arbitrarily) the placement of aromatic double bonds relative to how they are placed in related molecules that are structurally, almost identical. Generating all valid Kekule structures would healp me to account for this in my downstream clustering.

**Comment by greglandrum** [comment] 2024-12-15 08:38
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.

**Closed** 2024-12-15 08:38 UTC
