### ISSUE TITLE
Error when trying to write a molecule

### ISSUE THREAD

**Issue by lois1811** [rdkit/rdkit#5850] opened 2022-12-08 00:50 UTC
- RDKit Version: 2022.09.1
- Operating system: Windows 11
- Python version (if relevant): 3.9.7
- Are you using conda? Yes 
pip install rdkit

I have been trying to write a simple molecule on python using a .mol file but I keep getting the following error: 

Cannot convert '   ' to int on line 7

My code is:

```
import rdkit

from rdkit import Chem

m = Chem.MolFromMolFile('conf11.mol')
Chem.MolToSmiles(m)
```

and conf11.mol is attached as a text file:
[conf11.txt](https://github.com/rdkit/rdkit/files/10181201/conf11.txt)

I cannot find any formatting issues. Can anyone help?

**Comment by bp-kelley** [comment] 2022-12-08 01:35
The mol file you supplied isn't following the MDL specifications.   How was it generated?

**Comment by bp-kelley** [comment] 2022-12-08 01:36
I'm closing this as it's not a bug, please follow up as a discussion:  https://github.com/rdkit/rdkit/discussions

**Closed by bp-kelley** 2022-12-08 01:36 UTC
