### ISSUE TITLE
Python multiprocessing for Chem.SDMolSupplier

### ISSUE THREAD

**Issue by nadzhou** [rdkit/rdkit#4004] opened 2021-04-05 08:37 UTC
This is kind of related #2529, but I'm trying to do this via Chem.SDMolSupplier from a file in a Jetson Nano 2018 device. But I'm unable to do this because picke is not enabled for Chem.SDMolSupplier. The error I get is: 

```
multiprocessing.pool.MaybeEncodingError: 

Reason: 'RuntimeError('Pickling of "rdkit.Chem.rdmolfiles.SDMolSupplier" instances is not enabled 

(http://www.boost.org/libs/python/doc/v2/pickle.html)')'
```

for the code: 

```
    def mp_process_lib(self): 
        return Chem.SDMolSupplier(self.library)

    def read_library(self): 
        library = Path(self.out_dir) / "query.sdf"
        self.library = str(library)


        with Pool() as pool: 
            self.vs_library_2D = pool.starmap(self.mp_process_lib,  [() for _ in range(10)])

```

**Comment by ptosco** [comment] 2021-04-05 09:31
@nadzhou Not sure what you are trying to do here, but I'll try to help with a couple of points:
1. There is a native multi-threaded molecule supplier in the RDKit, which uses C++ threads: http://rdkit.org/docs/source/rdkit.Chem.rdmolfiles.html?highlight=multithreaded#rdkit.Chem.rdmolfiles.MultithreadedSDMolSupplier
2. There is little point in just creating a `SDMolSupplier` in a separate process, as the supplier itself is lazy, i.e. it will not actually do any work unless you iterate over it with a `for` loop or with `next`. `Chem.Mol` objects can indeed be pickled, so most likely what you want to do is reading the molecules in your separate process and return a list of processed molecules. As `Chem.Mol` objects can be pickled, this will work.
I am closing this as this is not a bug and no enhancement is required - the existing functionality will allow you to do what you need. Feel free to reopen if this is not the case.

**Closed by ptosco** 2021-04-05 09:31 UTC
Labels: enhancement
