### ISSUE TITLE
How can I appropriately use the gpu accelerated conformer generation through AllChem.MMFFGetMoleculeOpenMMForceField function using rdkit? Can I get any working example of conformer generation using openmm with gpu acceleration using rdkit interface? Please let me know.

### ISSUE THREAD

**Issue by rajarshiche** [rdkit/rdkit#5110] opened 2022-03-19 09:56 UTC
-----------------------------------------

If you have a question about the RDKit please use the Discussions tab above (https://github.com/rdkit/rdkit/discussions) instead of posting it here.

If you have a suggestion for a new RDKit feature or enhancement please consider starting a discussion about it using the Discussions tab above (https://github.com/rdkit/rdkit/discussions) before creating an issue. Community input on how a feature could work is often helpful and it could be that there's already a way to do what you want to do in the RDKit.

PLEASE DELETE THIS SECTION AFTER YOU HAVE READ IT

-----------------------------------------

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by greglandrum** [comment] 2022-03-20 04:42
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.

**Closed by greglandrum** 2022-03-20 04:42 UTC
Labels: enhancement
