### ISSUE TITLE
Adding/removing hydrogens

### ISSUE THREAD

**Issue by arunraja-hub** [rdkit/rdkit#6956] opened 2023-11-30 11:31 UTC
For any given rdkit molecule object, is there a way to check if the molecule has all of its hydrogen atoms removed or added? It seems AddHs adds hydrogen to a molecule object even when the molecule object has all of its hydrogens present

**Comment by greglandrum** [comment] 2023-12-08 15:38
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.

**Closed as completed by greglandrum** 2023-12-08 15:38 UTC
Labels: bug
