### ISSUE TITLE
Atomic Fingerprints

### ISSUE THREAD

**Issue by ekwan** [rdkit/rdkit#4264] opened 2021-06-20 19:20 UTC
Hello all,

Is it possible to get any of the intermediate hash codes from a fingerprint calculation?  Reading [this description](https://towardsdatascience.com/a-practical-introduction-to-the-use-of-molecular-fingerprints-in-drug-discovery-7f15021be2b1) of the fingerprinting procedure indicates that hash codes are generated at each atom before being folded into an overall molecular fingerprint.

Also, is it possible to compute these fingerprints from a 3D structure, rather than a SMILES string?

Thanks,
-Eugene

**Comment by greglandrum** [comment] 2021-06-21 13:03
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.

**Closed by greglandrum** 2021-06-21 13:03 UTC

**Comment by greglandrum** [comment] 2021-06-22 08:43
Hi Eugene,

> 
> Is it possible to get any of the intermediate hash codes from a fingerprint calculation? Reading [this description](https://towardsdatascience.com/a-practical-introduction-to-the-use-of-molecular-fingerprints-in-drug-discovery-7f15021be2b1) of the fingerprinting procedure indicates that hash codes are generated at each atom before being folded into an overall molecular fingerprint.

I don't understand the question. What exactly do you want to get from the fingerprint calculation?

> Also, is it possible to compute these fingerprints from a 3D structure, rather than a SMILES string?

The RDKit can generate fingerprints for 3D molecules just the same as for "2D" molecules generated from SMILES, but almost all of the fingerprinting algorithms ignore 3D information. The one exception to this is the AtomPair fingerprinter, which you can tell to use 3D distances instead of 2D distances.
