### ISSUE TITLE
Have problem to import RDKit library

### ISSUE THREAD

**Issue by sajedehsaremi** [rdkit/rdkit#4411] opened 2021-08-11 18:50 UTC
HI,
I am trying to get RDkit to work in order to use it for my QSAR models at work. I successfully installed RDkit and activate my environment on my conda through the following command on my Python 3 using windows 10:
1.  conda install -c rdkit rdkit -y
2.  conda activate PythonDataChem

now that I do have RDkit installed, I am trying to import my libraries as follow:
   import rdkit
   from rdkit import Chem
   from rdkit.Chem import Descriptors, Lipinski

However, it keeps giving me the following error:

ModuleNotFoundError: No module named 'rdkit'

Can someone kindly advise how I can overcome this issue? FYI, I did update my python and it does support Python 3.6.

Many thanks in advance.

**Comment by greglandrum** [comment] 2021-08-11 19:34
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.

**Closed by greglandrum** 2021-08-11 19:34 UTC
Labels: bug
