### ISSUE TITLE
MolsToGridImage returnPNG documented wrong?

### ISSUE THREAD

**Issue by jajupmochi** [rdkit/rdkit#5326] opened 2022-05-25 08:47 UTC
**Describe the bug**

When I use `MolsToGridImage` function to show and save image, it can not be done unless `returnPNG` is explicitly set to False.

**To Reproduce**
```
from rdkit.Chem.Draw import IPythonConsole
from rdkit import Chem
from rdkit.Chem.Draw import MolsToGridImage
img = MolsToGridImage(molecules, molsPerRow=4, subImgSize=(300, 300))
img.show()
img.save(filename)
```
This returns:
```
  File "/usr/local/lib/python3.8/site-packages/spyder_kernels/py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)
.......

  File "/media/**.py", line 48, in plot_all_molecules
    img.show()

AttributeError: 'Image' object has no attribute 'show'
```

**Expected behavior**
When I explicitly set `returnPNG=False`, everything works out:
```
img = MolsToGridImage(molecules, molsPerRow=4, subImgSize=(300, 300), returnPNG=False)
img.show()
img.save(filename)
```

However, the default value of  `returnPNG=False`. May I ask what is the problem here?

**Configuration:**
 - RDKit version: 2021.09.2 1_76
 - OS: e.g. Ubuntu 18.04.6 LTS
 - Python version 3.8.5
 - Are you using conda? No
 - If you are not using conda: how did you install the RDKit?
 ```
python3 -m pip install rdkit-pypi
 ```

**Comment by greglandrum** [comment] 2022-05-25 11:48
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.

**Closed by greglandrum** 2022-05-25 11:48 UTC
Labels: bug
