### ISSUE TITLE
`MolFromSmiles` removes explicit hydrogens

### ISSUE THREAD

**Issue by BvB93** [rdkit/rdkit#5118] opened 2022-03-22 12:27 UTC
**Describe the bug**
The `Chem.MolFromSmiles` function removes all explicitly defined hydrogens from the passed SMILES string. 

A workaround that I previously used was to manually sanitize the resulting molecule without the `Chem.SanitizeFlags.SANITIZE_ADJUSTHS` flag, but this has some problematic side effects such as loss of *cis*-/*trans*-information.

**To Reproduce**
``` python
>>> from rdkit import Chem

# Create a fragment that one might use for, for example, substructure matching
>>> mol = Chem.MolFromSmiles("C[H]")
>>> for at in mol.GetAtoms():
...     print(at.GetSymbol())
C
```

**Expected behavior**
The inclusion of the explicit hydrogen (_i.e._ the same behavior that _is_ observed in `Chem.MolFromSmarts`):
``` python
>>> for at in mol.GetAtoms():
...     print(at.GetSymbol())
C
H
```

**Configuration (please complete the following information):**
 - RDKit version: 2021.09.5 (conda-forge)
 - OS: Windows 10
 - Python version (if relevant): 3.9

**Comment by ptosco** [comment] 2022-03-22 12:54
@BvB93 Removing Hs is the default behavior but you may override it:

```
params = Chem.SmilesParserParams()
params.removeHs = False

mol = Chem.MolFromSmiles("C[H]", params)

for at in mol.GetAtoms():
    print(at.GetSymbol())
C
H
```
Closing as this is not a bug, feel free to open if needed.

**Closed by ptosco** 2022-03-22 12:54 UTC
Labels: bug
