### ISSUE TITLE
Cannot reproduce an example with ResonanceMolSupplier

### ISSUE THREAD

**Issue by najwalb** [rdkit/rdkit#6354] opened 2023-05-09 08:10 UTC
**Describe the bug**
- Cannot print different kekule forms (smiles, images) from ResonanceMolSupplier

**To Reproduce**
- I am following the example mentioned in an old [rdkit mailing list](https://sourceforge.net/p/rdkit/mailman/message/36034365/):
```
    smi = 'c1ccccc1'

    mol = Chem.MolFromSmiles(smi)
    suppl = Chem.ResonanceMolSupplier(mol, Chem.KEKULE_ALL)

    print(len(suppl))
    for i in range(len(suppl)):
        print (Chem.MolToSmiles(suppl[i], kekuleSmiles=True))
```
Outputs: 
```
2
C1=CC=CC=C1
C1=CC=CC=C1
```

**Expected behavior**
Same as in the mailing list:
```
2
C1C=CC=CC=1
C1=CC=CC=C1
```

**Screenshots**

**Configuration (please complete the following information):**
 - RDKit version: 2023.3.1
 - OS: 13.3.1 (a) 
 - Python version (if relevant): 3.11.0
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? N/A
 - If you are not using conda: how did you install the RDKit? pip

**Additional context**
I would like to be able to generate and print different resonance structures of the same molecules. If the above approach does not work anymore, please show me one that does.

**Comment by greglandrum** [comment] 2023-05-22 04:55
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.

**Closed by greglandrum** 2023-05-22 04:55 UTC
Labels: bug
