### ISSUE TITLE
Workaround for making RDKit can be installed by pip directly

### ISSUE THREAD

**Issue by hsiaoyi0504** [rdkit/rdkit#1812] opened 2018-04-09 07:23 UTC
As title, I am trying to make `RDKit` installable by `pip` directly, which is the recommend installation for a python package. To do this, we need to add a `setup.py`, a `MANIFEST.in`, and probably need to put more settings into `setup.cfg`.

The main challenge of this is that `RDKit` is natively built by `CMake`, which is not directly supported by Python standard library. Therefore, we need to extend the build extension mechanism for `CMake`. There are two projects I found that use `CMake` as well: [cmake_example](https://github.com/pybind/cmake_example) and [boost-python-cmake-mac](https://github.com/buddha314/boost-python-cmake-mac). There are also other resources like [stackoverflow question](https://stackoverflow.com/questions/42585210/extending-setuptools-extension-to-use-cmake-in-setup-py) and [quora question](https://www.quora.com/How-do-you-distribute-Boost.Python-modules).

I put my current work here: https://github.com/hsiaoyi0504/rdkit/tree/d442394c45fb05d4f989c7f031ab67213ad1536d. However, I failed to finish. In principle, that is not so hard to extend the build extension process. We just need to call some CMake commands and put the result in `build_temp` directory. One observation I found is that after running
``` shell
mkdir build
cd build
cmake ..
cmake --build  # or make 
```

In [cmake_example](https://github.com/pybind/cmake_example), it will produce a file `cmake_example.cpython-36m-darwin.so`, but for our RDkit, it doesn't have a file like that.
@greglandrum Do you know how to produce such a file ? Where should I edit the `CMakeLists.txt`?

- RDKit Version: based on `Release_2017_09_3`.
- Platform: MacOS, but should be the same on Linux.

**Comment by greglandrum** [comment] 2018-04-09 07:51
This is a brave thing to attempt, and if it works it would be great, but the requirements for an RDKit install are pretty tricky: you need to install all of the .py files, the shared libraries for the extension modules (I believe that these are the equivalent of the `cmake_example.cpython-36m-darwin.so` file), *and* the shared libraries that those extension modules need.

**Comment by hsiaoyi0504** [comment] 2018-04-09 12:45
@greglandrum Although the installation is tricky as you described, I think it should be possible. I will keep working on this. However, based on my observation, I have a question. Does the `build/rdkit` folder is the only final product we need to use `rdkit` ?  I mean, just add this folder into python search path will make something like `from rdkit import Chem` work, right?

**Comment by bp-kelley** [comment] 2018-04-09 13:50
Have you looked at bdist_wheel?  It is designed to make pip+cmake coexist
somewhat gracefully:

https://blog.kitware.com/cmake-python-wheels/

**Comment by hsiaoyi0504** [comment] 2018-04-09 15:25
@bp-kelley Hmm... somewhat. Based on my understanding, bdist_wheel is about building a package accessible from pypi or other place. That will be the second step of this. For me, I think initial step for this is to make rdkit can be installed by pip using pip install . and consider make it a distribution later. The other thing is that the link you mentioned above is about you can install cmake through pip install cmake and it’s not for building the extension during the installation.

**Comment by greglandrum** [comment] 2018-04-09 15:57
@hsiaoyi0504 unfortunately the `build/rdkit` folder does not contain everything you need. It will be missing the python files from `$RDBASE/rdkit`, the shared libraries that the python extensions also need, and the data files. The easiest way to figure out what should be installed is to do a cmake build that is configured with `-DCMAKE_INSTALL_PREFIX=/some/directory/you/can/find` and then look at `make install` puts in that directory. (I think I got that incantation right, I don't have an easy way to test it at the moment).

**Comment by hsiaoyi0504** [comment] 2018-04-11 03:44
@greglandrum By using `-DCMAKE_INSTALL_PREFIX=/some/directory/you/can/find`, I now can see all stuffs installed by `make install`, but I am somewhat get confused about the directories. As I can see, there are three directory
```
.
├── include
├── lib
└── share
3 directories, 0 files
```
The python package (`rdkit` folder) is located at `lib/python3.6/site-packages`, and there are many `.dylib` and `.a` files there inside the `lib`. If we only consider using python API, can we just use the files in `lib/python3.6/site-packages` ?

Similarly, how about the `include` and `share` directory. My assumption is that the files in `include` are `.h` header files. It's for application using `C++ API` and we don't need to install that if we only use `Python API`. At the same time, I have no idea about `share` directory.

**Comment by hsiaoyi0504** [comment] 2018-04-11 04:12
It seems that I need to include the dylib in `lib`, I will get an error when I directly execute `python` under ·lib/python3.6/site-packages`.

**Comment by greglandrum** [comment] 2018-04-11 04:53
Yeah, you definitely need the stuff that's in `lib`. Those are the shared libraries that the python bindings require.

You're right that `include` is almost certainly not necessary.

`share` includes data, parameter files, documentation, the Contrib folder, etc:
```
glandrum@Otter:/scratch/RDKit_git/builds$ ls ~/anaconda5/envs/py36_rdkit/share/RDKit/
Contrib  Data  Docs  license.txt  Projects  README
```
I think it's important to include this stuff, particularly the `Data` directory.

**Comment by UnixJunkie** [comment] 2018-11-02 01:33
Very interesting endeavor.
```
pip install cmake
```
Does install cmake in ~/.local/bin on Linux.
It would quite useful if rdkit is also installable via pip.
Since then pure python scripts which are pip-enabled would be able
to automatically install rdkit as a dependency if it is missing.

**Comment by UnixJunkie** [comment] 2018-11-02 01:35
Intuitively, just changing the install prefix to ~/.local should do the job.
Maybe, a first step is to be able to do a source install of rdkit in there and
check that it is working from a python interpreter.
Then, we can have a look at how to create the complete pip package.

**Comment by UnixJunkie** [comment] 2018-11-02 01:38
Can this issue be assigned to me?

**Comment by greglandrum** [comment] 2018-11-02 07:10
Apparently you need to listed as a collaborator on the project (or have submitted the issue) for me to assign it to you. I just sent you an invite to be a collaborator

**Comment by greglandrum** [comment] 2018-11-05 04:53
No, but now I can assign you. :-)

**Comment by hsiaoyi0504** [comment] 2018-11-17 07:56
@UnixJunkie I think the hardest part of this issue is about the C part. It seems to me that `*.so` or `*.a`  are not easily to be installed into a virtual environment.

**Comment by Chasearmer** [comment] 2018-11-26 23:11
@hsiaoyi0504 @UnixJunkie Hi, I am also very interested interested in being able to install rdkit via pip because at the moment it appears I will be unable to use the GoogleCloud ML Engine unless I can do so. Do you mind filling me in on the current status/progress of the task and how, if at all, I would able to help?

**Comment by UnixJunkie** [comment] 2018-11-27 01:44
In this thread there are pointers to useful resources.
I guess the status/progress is that someone has to start from scratch since there is no pull request
associated with this issue.

**Comment by Chasearmer** [comment] 2018-11-27 18:13
@hsiaoyi0504 Would you happen to have any code you've written that you think would be useful to make public here?

**Comment by hsiaoyi0504** [comment] 2018-12-04 14:51
@Chasearmer The only things I have is a not-working **setup.py** and **MANIFEST.in**.
setup.py:
``` python
from distutils.command.build import build as build_orig
from distutils.command.install import INSTALL_SCHEMES
import os
import sys
from setuptools import setup
from shutil import move, rmtree
from glob import glob
from wheel.bdist_wheel import bdist_wheel as _bdist_wheel

data_files = []

here = os.path.abspath(os.path.dirname(__file__))

class bdist_wheel(_bdist_wheel):
    def finalize_options(self):
        _bdist_wheel.finalize_options(self)
        # Mark us as not a pure python package
        self.root_is_pure = False

class build(build_orig):
    def run(self):
        self.build_cmake()
        # super().run()

    def build_cmake(self):
        build_dir = os.path.join(here, 'build')
        install_dir = os.path.join(here, 'install_temp')
        os.makedirs(build_dir)
        os.makedirs(install_dir)
        config = 'Debug' if self.debug else 'Release'
        cmake_args = [
            '-DRDK_INSTALL_INTREE=OFF',
            '-DCMAKE_INSTALL_PREFIX=' + install_dir,
            '-DPYTHON_EXECUTABLE=' + sys.executable,
            '-DCMAKE_BUILD_TYPE=' + config
        ]
        os.chdir(build_dir)
        self.spawn(['cmake', '..'] + cmake_args)
        self.spawn(['make'])
        self.spawn(['make', 'install'])
        os.chdir('..')
        rmtree(os.path.join(here, 'rdkit'))
        move(os.path.join(install_dir, 'lib', 'python' + sys.version[0] + '.' + sys.version[2], 'site-packages', 'rdkit'), os.path.join(here, 'rdkit'))
        move(os.path.join(install_dir, 'lib'), os.path.join(here, 'lib'))
        # move(os.path.join(install_dir, 'rdkit'), os.path.join(here, 'install_temp', 'include'), os.path.join(here, 'include'))
        # move(os.path.join(install_dir, 'rdkit'), os.path.join(install_dir, 'share'), os.path.join(here, 'share'))
        lib_files = glob(os.path.join('lib', '*.dylib'))
        data_files.append(('lib', lib_files))


for scheme in INSTALL_SCHEMES.values():
    scheme['data'] = scheme['purelib']

setup(
    name='rdkit',
    version='2017.09.3',
    install_requires=['numpy'],
    packages=['rdkit'],
    include_package_data=True,
    data_files=data_files,
    cmdclass={
        'build': build,
        'bdist_wheel': bdist_wheel
    }
)
```

MANIFEST.in:
```
graft rdkit
```

**Comment by hsiaoyi0504** [comment] 2018-12-05 02:55
@greglandrum Although I haven't touched that for a while, but I found in my note, I would like to know if is it possible to build the dynamic libraries inside the python package directory ? That means, after running some `cmake` commands.

We can have a `$GIT_REPO_ROOT_DIRCTORY/rdkit` that can be moved everywhere and works without any external dependencies (i.e. any other stuffs in `/usr/lib` or other similar things). That means, if I have a project with following file directories tree:

```shell
project ---- rdkit
               |-- main.py
```

And in *main.py*:,

```python
from rdkit import Chem
# do whatever rdkit can do
```

It seems to me that there is a `-DRDK_INSTALL_INTREE=ON` option, but I didn't make it work before.

**Comment by RobinFrcd** [comment] 2019-02-07 12:05
Hi, is it still plan to have rdkit in pip ?

**Comment by UnixJunkie** [comment] 2019-03-14 02:41
We need an installer for pip3 also (for python3).

**Comment by Karrenbelt** [comment] 2019-10-29 11:59
alright, so did anyone manage to get this thing into the real world by making it pip installable yet?

**Comment by UnixJunkie** [comment] 2019-10-30 01:15
There is some work in progress there:
https://github.com/rdkit/rdkit/pull/2690

**Comment by UnixJunkie** [comment] 2020-05-20 00:00
Can this issue be renamed to "pip installer for rdkit"?

Also, is there any progress on this front?

**Comment by churnikov** [comment] 2020-07-30 19:41
Hey!

So may be it's possible to use [scikit-build](https://scikit-build.readthedocs.io/en/latest/index.html) to solve this problem?

**Comment by greglandrum** [comment] 2020-07-31 06:13
@churnikov : thanks for pointing that out. It's an interesting possibility. We would still have to figure out how to handle the boost library dependencies via pip.

**Comment by churnikov** [comment] 2020-07-31 13:15
@greglandrum maybe this tool could be used instead of python boost?
https://pybind11.readthedocs.io/en/stable/intro.html

**Comment by greglandrum** [comment] 2020-07-31 13:21
Theoretically, but that would require rewriting thousands of lines of code.

**Comment by rapodaca** [comment] 2020-08-12 16:56
Has anyone looked into [Conda-Press](https://github.com/regro/conda-press) as a way to auto-generate an RDKit wheel from the Conda package?

**Comment by bp-kelley** [comment] 2020-08-12 20:32
I have and it’s ugly.  Almost too ugly. I need to try it or more Linux systems.

**Comment by skearnes** [comment] 2020-08-23 17:25
`conda press` might not be a good general solution, but if we can use it to get a package that works with the GCP VMs behind colab it might be really useful to speed up installs there...

**Comment by dmyersturnbull** [comment] 2020-11-16 20:52
@bp-kelly Does it work though, and could that be a short-term solution?

**Comment by kuelumbus** [comment] 2021-03-27 17:52
I found a solution using the manylinux docker images. Please see [https://github.com/kuelumbus/rdkit_platform_wheels](https://github.com/kuelumbus/rdkit_platform_wheels). Python wheel packages are available for Python 3.7 and 3.8.

**Comment by bp-kelley** [comment] 2021-03-27 19:30
@kuelumbus This is great.  I had tried the package that turns condo packages into wheels but it brought along a lot of junk.

This is way better.

**Comment by njzjz** [comment] 2021-03-27 20:42
> I found a solution using the manylinux docker images. Please see https://github.com/kuelumbus/rdkit_platform_wheels. Python wheel packages are available for Python 3.7 and 3.8.

It works for me. I hope it can be officially published to pypi, so that packages that depends on rdkit could directly add rdkit as a install requirement.

**Comment by bp-kelley** [comment] 2021-03-27 22:00
I’m happy to try this on as many Linux variants as I can :)

**Comment by kuelumbus** [comment] 2021-03-27 22:21
I have upload the wheels to pypi: https://pypi.org/project/rdkit-pypi/2020.9.5/

This should work now on Linux systems.
`pip install rdkit-pypi`

**Comment by tbabej** [comment] 2021-03-28 21:59
I can confirm that this approach works, at [ProteinQure](https://proteinqure.com/) we've been testing a very similar approach internally: https://github.com/ProteinQure/rdkit-wheels

**Comment by tbabej** [comment] 2021-03-28 22:13
Also, while the currently both @kuelumbus and mine repos only support Linux systems, I'm quite confident this work could be extended to support MacOS X and Windows platforms. If this looks like promising development to the maintainers (cc @greglandrum ), it could be contributed to the build process of RDkit itself.

@kuelumbus perhaps you'd want to join forces on this one?

**Comment by churnikov** [comment] 2021-03-29 08:00
@tbabej It would've been great if you could make it work on MasOS. We at Biocad use Macs for development and Ubuntu on servers, so for us it would be great to remove Conda from development setup.
Specifically, I really hate to mix coda and poetry, but we have to right now with rdkit.

**Comment by kuelumbus** [comment] 2021-03-29 14:17
https://github.com/joerick/cibuildwheel seems to be a promising solution to get it work for MacOS and Windows. I will give it a try.

**Comment by UnixJunkie** [comment] 2021-03-30 23:51
Yep, it would be great if the pip installer also works on Mac.

**Comment by kuelumbus** [comment] 2021-04-02 19:52
I was able to build a Mac wheel for RDKit. Can somebody try it please? It is available at https://github.com/kuelumbus/rdkit_platform_wheels/actions/runs/712514749 in the artifact ZIP file.

**Comment by kuelumbus** [comment] 2021-04-28 14:40
Can somebody please check if the wheels at https://github.com/kuelumbus/rdkit_platform_wheels/actions/runs/790692407 (artifact.zip) work on Mac?

**Comment by psychemedia** [comment] 2021-05-15 17:36
@kuelumbus Trying `pip3 install artifact.zip` installs a non-importable package `UNKNOWN-0.0.0` on my Mac (original, not M1). No sign of `rdkit` package named as such.

**Comment by churnikov** [comment] 2021-05-15 21:01
> @kuelumbus Trying `pip3 install artifact.zip` installs a non-importable package `UNKNOWN-0.0.0` on my Mac (original, not M1). No sign of `rdkit` package named as such.

Did you unzip archive?
Installing wheel from zip archive worked for me

**Comment by psychemedia** [comment] 2021-05-16 15:10
Ah, ok - my mistake: `artifact.zip` is a bundle of wheels:

```
Archive:  artifact.zip
  inflating: rdkit_pypi-2021.3.1-cp36-cp36m-macosx_10_9_x86_64.whl  
  inflating: rdkit_pypi-2021.3.1-cp37-cp37m-macosx_10_9_x86_64.whl  
  inflating: rdkit_pypi-2021.3.1-cp38-cp38-macosx_10_9_x86_64.whl  
  inflating: rdkit_pypi-2021.3.1-cp39-cp39-macosx_10_9_x86_64.whl  
```

I assumed it was a pip installable archive. Selecting an appropriate wheel seems to work fine.

**Comment by rapodaca** [comment] 2021-05-19 20:53
Tried it on macOS and it seems to work. Thank you!

I'm not quite clear on how this is fixed now after so much discussion on how it would be difficult/impossible. What was the solution?

**Comment by kuelumbus** [comment] 2021-05-19 22:14
I didn't follow the discussion but I think platform wheels just recently became thing.

**Comment by greglandrum** [comment] 2021-05-20 03:14
@kuelumbus : thanks for this!
I just quickly tried it out on my linux box and M1 Mac (using the intel build, doesn't look like there's a build for the M1 there yet) and everything seems to work.

I haven't followed the developments on the python packaging front, but it looks like they've found a workable solution to the shared library problem that was so problematic. That's really cool!

It would be nice if it were possible to complete the build matrix a bit and at least have builds for 64bit windows and apple silicon. Can I help out with that?

**Comment by ElricleNecro** [comment] 2021-05-20 10:26
It seems there is still some problems with the linux wheels (did not try Mac, but I suspect it will be the same):
- some internal constants don't have a correct value, for example : `rdkit.RDConfig.RDDataDir` is set at `/tmp/pip-req-build-5c4y6o05/build/temp.linux-x86_64-3.9/rdkit_install/share/RDKit/Data` while it should be the final installation directory I think.
  This seems to be caused by some variables in `RDPaths.py` not properly set:
  ```python
  RDCodeDir=os.path.join(r'/tmp/pip-req-build-5c4y6o05/build/temp.linux-x86_64-3.9/rdkit_install/lib/python3.9/site-packages','rdkit')
  # not really hard-coded alternative RDCodeDir=os.path.dirname(__file__)
  _share = os.path.join(r'/tmp/pip-req-build-5c4y6o05/build/temp.linux-x86_64-3.9/rdkit_install', r'share/RDKit')
  ```
  Plus, those directories are missing in the installation.
- as such, some files are not installed, for example, the `oddt` package is looking for a file named `BaseFeatures.fdef`, but it (nor I) can't find it anywhere in the installation.

**Comment by kuelumbus** [comment] 2021-05-20 14:39
> @kuelumbus : thanks for this!
> I just quickly tried it out on my linux box and M1 Mac (using the intel build, doesn't look like there's a build for the M1 there yet) and everything seems to work.

There is an option to cross-compile arm64/aarch64 wheels for MacOS but I think it will work for Python >= 3.9 only. I will enable arm64/aarch64 wheels for Linux and MacOS.

> I haven't followed the developments on the python packaging front, but it looks like they've found a workable solution to the shared library problem that was so problematic. That's really cool!
> 
> It would be nice if it were possible to complete the build matrix a bit and at least have builds for 64bit windows and apple silicon. Can I help out with that?

I have never worked with Python on windows but I will give it a try. RDKit fails to build with Cairo 1.15 (available in the CentOS 7 repo). Do you know why? Also, can you check if the cmake build flags are correctly set at [setup.py](https://github.com/kuelumbus/rdkit_platform_wheels/blob/afaea2970fd44e20ceed3693a5964722fcc1f544/setup.py#L136).

@ElricleNecro thanks for pointing this out.

> It seems there is still some problems with the linux wheels (did not try Mac, but I suspect it will be the same):
> 
> * some internal constants don't have a correct value, for example : `rdkit.RDConfig.RDDataDir` is set at `/tmp/pip-req-build-5c4y6o05/build/temp.linux-x86_64-3.9/rdkit_install/share/RDKit/Data` while it should be the final installation directory I think.
>   This seems to be caused by some variables in `RDPaths.py` not properly set:
>   ```python
>   RDCodeDir=os.path.join(r'/tmp/pip-req-build-5c4y6o05/build/temp.linux-x86_64-3.9/rdkit_install/lib/python3.9/site-packages','rdkit')
>   # not really hard-coded alternative RDCodeDir=os.path.dirname(__file__)
>   _share = os.path.join(r'/tmp/pip-req-build-5c4y6o05/build/temp.linux-x86_64-3.9/rdkit_install', r'share/RDKit')
>   ```
>   Plus, those directories are missing in the installation.

Looks like `RDCodeDir` is mostly used to run tests. It should be not critical to run RDKit. @greglandrum  Can you help?


> * as such, some files are not installed, for example, the `oddt` package is looking for a file named `BaseFeatures.fdef`, but it (nor I) can't find it anywhere in the installation.

 `rdkit/rdkit/Chem/Pharm2D/test_data/BaseFeatures.fdef` & `rdkit/rdkit/Chem/Pharm3D/test_data/BaseFeatures.fdef` 
 are part of test directories which are not installed by default. @greglandrum Can you also clarify?

**Comment by kuelumbus** [comment] 2021-05-20 16:14
This would probably increase the size of the wheels significantly. Is there any reason for distributing these folders with the wheels?

**Comment by greglandrum** [comment] 2021-05-20 16:31
The `Data` directory includes parameter files and the like that the RDKit needs. It looks like the big offenders in terms of disk space are Contrib and Docs:
```
(rdkit_blog) glandrum@Badger:~$ du -sh /home/glandrum/miniconda3/envs/rdkit_blog/share/RDKit/*
55M	/home/glandrum/miniconda3/envs/rdkit_blog/share/RDKit/Contrib
2.5M	/home/glandrum/miniconda3/envs/rdkit_blog/share/RDKit/Data
34M	/home/glandrum/miniconda3/envs/rdkit_blog/share/RDKit/Docs
4.0K	/home/glandrum/miniconda3/envs/rdkit_blog/share/RDKit/license.txt
924K	/home/glandrum/miniconda3/envs/rdkit_blog/share/RDKit/Projects
4.0K	/home/glandrum/miniconda3/envs/rdkit_blog/share/RDKit/README
36K	/home/glandrum/miniconda3/envs/rdkit_blog/share/RDKit/Scripts
``` 
Those are, I guess, nice-to-haves since people can get Contrib from github and the docs are online.

Data definitely needs to be there and either:
1. RDDataDir and RDBaseDir in RDPaths.py needs to be setup to point to the appropriate place (this is something conda does at install time) or
2. an RDBASE environment variable needs to be created that allows the RDKit to find a correct value of RDBASE at runtime.

**Comment by kuelumbus** [comment] 2021-05-21 00:18
Ok. I see. I am not sure what's the best way to do this. 

I don't think that we can modify python files of the wheels at install time. I wonder if the best solution would be to set 
`_share=os.path.dirname(__file__)` in `RDPaths.py`. I can then copy the `Data` dir to the main tree and things should work?

**Comment by kuelumbus** [comment] 2021-05-21 21:30
I have pushed an arm64 rdkit wheel for MacOS to pypi. Can someone with a M1 Mac please test if the wheel works? You would need Python >= 3.9 and pip >= 20.3.

**Comment by greglandrum** [comment] 2021-05-22 02:43
Seems to have problems:
```
(py39_pypi) Marder:~ glandrum$ python -c 'import rdkit'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/glandrum/miniforge3/envs/py39_pypi/lib/python3.9/site-packages/rdkit/__init__.py", line 2, in <module>
    from .rdBase import rdkitVersion as __version__
ImportError: dynamic module does not define module export function (PyInit_rdBase)
```

That's running on an M1 mac mini and installing in a fresh conda environment. Using the intel version I didn't have problems, so it's probably not the conda env that's causing this

**Comment by kuelumbus** [comment] 2021-05-22 17:20
Thanks for testing. Looks like the libs are missing.

**Comment by marcosfelt** [comment] 2021-06-01 17:53
I just want to say thanks so much for this. Saved me so much headache by making it pip installable.

**Comment by brndnsy** [comment] 2021-08-11 15:17
> Seems to have problems:
> 
> ```
> (py39_pypi) Marder:~ glandrum$ python -c 'import rdkit'
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/Users/glandrum/miniforge3/envs/py39_pypi/lib/python3.9/site-packages/rdkit/__init__.py", line 2, in <module>
>     from .rdBase import rdkitVersion as __version__
> ImportError: dynamic module does not define module export function (PyInit_rdBase)
> ```
> 
> That's running on an M1 mac mini and installing in a fresh conda environment. Using the intel version I didn't have problems, so it's probably not the conda env that's causing this

D'you have any ideas how to resolve this manually on an M1 Macbook? I've tried symbolic links, DYLD_LIBRARY_PATHS and install_name_tool but I keep getting the same error :/

**Comment by kuelumbus** [comment] 2021-08-12 09:49
Please use

> > Seems to have problems:
> > ```
> > (py39_pypi) Marder:~ glandrum$ python -c 'import rdkit'
> > Traceback (most recent call last):
> >   File "<string>", line 1, in <module>
> >   File "/Users/glandrum/miniforge3/envs/py39_pypi/lib/python3.9/site-packages/rdkit/__init__.py", line 2, in <module>
> >     from .rdBase import rdkitVersion as __version__
> > ImportError: dynamic module does not define module export function (PyInit_rdBase)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > That's running on an M1 mac mini and installing in a fresh conda environment. Using the intel version I didn't have problems, so it's probably not the conda env that's causing this
> 
> D'you have any ideas how to resolve this manually on an M1 Macbook? I've tried symbolic links, DYLD_LIBRARY_PATHS and install_name_tool but I keep getting the same error :/

Unfortunately, the compilation on arm64 M1 Mac is a headache. Until this gets better, please use the intel builds. I have also yanked all the arm64 builds on PyPi. You should actually not be able to install the arm64 builds if you're using pipi.

**Comment by brndnsy** [comment] 2021-08-12 16:03
> > > Seems to have problems:
> > > ```
> > > (py39_pypi) Marder:~ glandrum$ python -c 'import rdkit'
> > > Traceback (most recent call last):
> > >   File "<string>", line 1, in <module>
> > >   File "/Users/glandrum/miniforge3/envs/py39_pypi/lib/python3.9/site-packages/rdkit/__init__.py", line 2, in <module>
> > >     from .rdBase import rdkitVersion as __version__
> > > ImportError: dynamic module does not define module export function (PyInit_rdBase)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > That's running on an M1 mac mini and installing in a fresh conda environment. Using the intel version I didn't have problems, so it's probably not the conda env that's causing this
> > 
> > 
> > D'you have any ideas how to resolve this manually on an M1 Macbook? I've tried symbolic links, DYLD_LIBRARY_PATHS and install_name_tool but I keep getting the same error :/
> 
> Unfortunately, the compilation on arm64 M1 Mac is a headache. Until this gets better, please use the intel builds. I have also yanked all the arm64 builds on PyPi. You should not be able to install the arm64 builds using pip.

Thanks for your reply. I've been able to install the latest version fine. But my issue has ben building an older custom rdkit from source via cmake.

**Comment by kuelumbus** [comment] 2021-08-16 15:40
> > > > Seems to have problems:
> > > > ```
> > > > (py39_pypi) Marder:~ glandrum$ python -c 'import rdkit'
> > > > Traceback (most recent call last):
> > > >   File "<string>", line 1, in <module>
> > > >   File "/Users/glandrum/miniforge3/envs/py39_pypi/lib/python3.9/site-packages/rdkit/__init__.py", line 2, in <module>
> > > >     from .rdBase import rdkitVersion as __version__
> > > > ImportError: dynamic module does not define module export function (PyInit_rdBase)
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > That's running on an M1 mac mini and installing in a fresh conda environment. Using the intel version I didn't have problems, so it's probably not the conda env that's causing this
> > > 
> > > 
> > > D'you have any ideas how to resolve this manually on an M1 Macbook? I've tried symbolic links, DYLD_LIBRARY_PATHS and install_name_tool but I keep getting the same error :/
> > 
> > 
> > Unfortunately, the compilation on arm64 M1 Mac is a headache. Until this gets better, please use the intel builds. I have also yanked all the arm64 builds on PyPi. You should not be able to install the arm64 builds using pip.
> 
> Thanks for your reply. I've been able to install the latest version fine. But my issue has ben building an older custom rdkit from source via cmake.

 What version do you need? I can try to compile it and put on pypi.

**Comment by brndnsy** [comment] 2021-08-16 16:11
> > > > > Seems to have problems:
> > > > > ```
> > > > > (py39_pypi) Marder:~ glandrum$ python -c 'import rdkit'
> > > > > Traceback (most recent call last):
> > > > >   File "<string>", line 1, in <module>
> > > > >   File "/Users/glandrum/miniforge3/envs/py39_pypi/lib/python3.9/site-packages/rdkit/__init__.py", line 2, in <module>
> > > > >     from .rdBase import rdkitVersion as __version__
> > > > > ImportError: dynamic module does not define module export function (PyInit_rdBase)
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > That's running on an M1 mac mini and installing in a fresh conda environment. Using the intel version I didn't have problems, so it's probably not the conda env that's causing this
> > > > 
> > > > 
> > > > D'you have any ideas how to resolve this manually on an M1 Macbook? I've tried symbolic links, DYLD_LIBRARY_PATHS and install_name_tool but I keep getting the same error :/
> > > 
> > > 
> > > Unfortunately, the compilation on arm64 M1 Mac is a headache. Until this gets better, please use the intel builds. I have also yanked all the arm64 builds on PyPi. You should not be able to install the arm64 builds using pip.
> > 
> > 
> > Thanks for your reply. I've been able to install the latest version fine. But my issue has ben building an older custom rdkit from source via cmake.
> 
> Which version do you need? I can try to compile it and put it on pypi.

I would really appreciate that. I'm trying to use a modified version for compatibility with a toolkit :  
 
https://github.com/connorcoley/rdkit/tree/master/rdkit

**Comment by j3mdamas** [comment] 2021-12-13 16:09
@kuelumbus thanks a lot for your effort on making RDKit available on PyPi.

Following the conversation [here](https://github.com/kuelumbus/rdkit-pypi/issues/20) between you and @greglandrum , is it established that kuelumbus/rdkit-pypi is a fully functional version of RDKit installable by pip? If not, is it possible to create some small documentation on what does not work?

**Comment by kuelumbus** [comment] 2021-12-13 20:57
@j3mdamas I believe the wheels are fully functional (at least I don't know of any issue). In case you find something not working, please open an issue. I would try to fix issues rather than documenting.

**Comment by bp-kelley** [comment] 2021-12-13 21:11
The wheels are missing quite a few data files and don’t have the full cohort of descriptors, they are missing about half.

**Comment by kuelumbus** [comment] 2021-12-13 21:22
@bp-kelley Can you please point out the missing files?

**Comment by j3mdamas** [comment] 2021-12-13 21:58
OK, that is fair, @kuelumbus.

I phrase it differently then: is there a possibility of kuelumbus/rdkit-pypi to be included as part of the official releases of RDKit?

**Comment by kuelumbus** [comment] 2021-12-14 02:23
What I am doing right now is to compile a new RDKit version and push to PyPi for each new version tag in the RDKit repo, as you can see at https://pypi.org/project/rdkit-pypi/#history.  So, in that sense, you have a PyPi version for each RDKit release.

**Comment by greglandrum** [comment] 2021-12-14 03:41
> The wheels are missing quite a few data files and don’t have the full cohort of descriptors, they are missing about half.

I don't think this is the case any more. I believe it's now complete.

**Comment by greglandrum** [comment] 2021-12-14 03:42
> 
> I phrase it differently then: is there a possibility of kuelumbus/rdkit-pypi to be included as part of the official releases of RDKit?

What would that mean for you? At the moment the only "official releases" that the core team does are the source releases. The various binary releases, like the ones on conda-forge or pypi, are done by other volunteers.

**Comment by j3mdamas** [comment] 2021-12-14 11:03
@greglandrum I thought the conda releases were also done by the core team. I was just looking for more core support around the PyPi releases. I think your answer clarifies it though, thanks!

**Comment by bp-kelley** [comment] 2021-12-14 13:27
@Greg Landrum ***@***.***> I'll double check the descriptors,
this was true a few weeks ago at least.

**Comment by bp-kelley** [comment] 2021-12-14 17:25
Greg and I looked at the descriptors, and it does look like the latest
release solves the Data problem.  Congrats on that.

**Comment by skearnes** [comment] 2022-06-12 07:49
> > I phrase it differently then: is there a possibility of kuelumbus/rdkit-pypi to be included as part of the official releases of RDKit?
> 
> What would that mean for you? At the moment the only "official releases" that the core team does are the source releases. The various binary releases, like the ones on conda-forge or pypi, are done by other volunteers.

Are there plans to update https://www.rdkit.org/docs/Install.html to include `rdkit-pypi`, or are there still reasons to prefer conda that should be articulated here?

**Comment by greglandrum** [comment] 2022-06-12 10:45
> Are there plans to update https://www.rdkit.org/docs/Install.html to include `rdkit-pypi`, or are there still reasons to prefer conda that should be articulated here?

Pull request are welcome. ;-)

**Closed** 2022-06-18 02:50 UTC
