### ISSUE TITLE
MMFF optimization converts Pyridine geometry from planar to non-planar

### ISSUE THREAD

**Issue by venkata-ramaswamy-cresset** [rdkit/rdkit#7970] opened 2024-10-29 13:44 UTC
**Describe the bug**
The optimization of pyridine changes its planar conformation to that of non-planar.

**To Reproduce**
```
import pathlib
from rdkit import Chem
from rdkit.Chem import AllChem

# Helper functions
def run_mmff_minimisation(input_file: str):
    """
    Run a quick minimisation
    """
    input_ftype = pathlib.PurePath(input_file).suffix
    if input_ftype == ".sdf":
        rdmol = Chem.rdmolfiles.SDMolSupplier(input_file, sanitize=False, removeHs=False, 
        strictParsing=True)[0]
    if rdmol is None:
        raise RuntimeError("Unable to construct valid RDKit molecule from the input")

    mp = AllChem.MMFFGetMoleculeProperties(rdmol)
    ff = AllChem.MMFFGetMoleculeForceField(rdmol, mp)
    ff.Minimize()

    return rdmol
    
# MMFF optimization 
input_file = "pyridine.sdf"
fixed_opt = run_mmff_minimisation(input_file)
with Chem.SDWriter(str(input_file)[:-4]+"_MMFF_opt.sdf") as w:
    w.write(fixed_opt)
```
**Expected behavior**
The pyridine is expected to be planar even after optimization. 

**Screenshots**
![image](https://github.com/user-attachments/assets/ee43fd33-7e0c-4f62-8f13-bbe137064504)

**Configuration (please complete the following information):**
 - RDKit version: 2024.03.5
 - OS: Ubuntu 22.04
 - Python version (if relevant): 3.12
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge
 - If you are not using conda: how did you install the RDKit?

**Additional context**
Here are the sdf files of both the molecules 
[pyridine.sdf.txt](https://github.com/user-attachments/files/17557667/pyridine.sdf.txt)
[pyridine_MMFF_opt.sdf.txt](https://github.com/user-attachments/files/17557668/pyridine_MMFF_opt.sdf.txt)

Could you please help fixing this behaviour. Also, is this related to the reported issue:  https://github.com/rdkit/rdkit/issues/7961

**Comment by phonglam3103** [comment] 2024-11-25 08:58
Hi, I also confronted this problem and did a research on this. I believe this is a forcefield error and many software that used the original MMFF94s would have the same problem. I think that RDKit has done well in perceiving the atom type, thereby assigning the correct potential. I would suggest adding some constraints to either dihedral, angles to make it planar back. Hopefully it helps ;)

**Comment by ptosco** [comment] 2024-11-25 09:57
@venkata-ramaswamy-cresset I am unable to reproduce the problem with current RDKit, because if I run your code I get

```python
Cell In[6], line 6, in run_mmff_minimisation(rdmol, mmff_variant)
      2 def run_mmff_minimisation(rdmol, mmff_variant=None):
      3     """
      4     Run a quick minimisation
      5     """
----> 6     mp = AllChem.MMFFGetMoleculeProperties(rdmol, mmffVariant=(mmff_variant or "MMFF94"))
      7     ff = AllChem.MMFFGetMoleculeForceField(rdmol, mp)
      8     ff.Minimize()

RuntimeError: Pre-condition Violation
	RingInfo not initialized
	Violation occurred on line 28 in file Code/GraphMol/RingInfo.cpp
	Failed Expression: df_init
	RDKIT: 2023.09.3
	BOOST: 1_82
```

If I run with the default `sanitize=True` the pyridine ring stays planar as expected.
It could be that you get this with an older RDKit version which does not throw an exception.
Anyway, I believe the problem depends on the fact that you are using `sanitize=False`. In general, this is not the right thing to do when you wish to use a molecule in RDKit for purposes other than as-is visualization, since a non-sanitized molecule will lack crucial information (e.g., ring perception, aromaticity, implicit H perception, etc.) which is required to correctly assign MMFF94 atom types.
@phonglam3103 MMFF94 may pucker out-of-plane trigonal delocalized nitrogens (e.g., aniline `NH2`). You may avoid this behavior using the MMFF94s (static) variant of the forcefield, which may be selected in RDKit by setting `mmffVariant` to `'MMFF94s`.

I am closing this as I believe it is not a bug; feel free to reopen if needed.

**Closed by ptosco** 2024-11-25 09:57 UTC
Labels: bug

**Comment by phonglam3103** [comment] 2024-11-25 10:21
Hi @ptosco, I am aware of the availability of MMFF94s, which aims to planarize the trigonal delocalized nitrogen. But I believe that the problem that @venkata-ramaswamy-cresset  would like to point out is the off planar of the aromatic ring itself,. In fact, this happens for the substituted-N-heterocycles upon being minimized using MMFF94s.

This chunk of code will exemplify my mean:
```
from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit.Chem.Draw import IPythonConsole
IPythonConsole.ipython_3d = True
smiles = "CCc1c(c(nn1c2ccccc2c3cccc(c3)OCC(=O)[O-])c4ccccc4)c5ccccc5"
mol = Chem.MolFromSmiles(smiles)
mol = Chem.AddHs(mol)
AllChem.EmbedMolecule(mol)
mol_before = Chem.Mol(mol)
mol_before
```

The molecule shows planarity. It seems that ETKDGv3 has done a good job

![image](https://github.com/user-attachments/assets/3555fd59-df73-445c-aee7-93fba26f94c7)

Upon minimized:
```
AllChem.MMFFOptimizeMolecule(mol, mmffVariant="MMFF94s")
mol
```

As you can see, the aromatic ring now is puckered.

![image](https://github.com/user-attachments/assets/c0d0746c-2630-4f6f-8256-cb02bc5cadb5)

I have tested with different program that used MMFF94s, like OpenBabel, and LigandScout, and the problem persists. So I think this is a forcefield error.

**Comment by ptosco** [comment] 2024-11-25 13:57
@phonglam3103 Thank you for sharing this example, which however is quite different from what originally reportedby @venkata-ramaswamy-cresset.
In your example the small degree of puckering of the pyrazole ring appears to be mostly driven by the strong edge-to-face intramolecular interaction between the 3-phenyl substituent on the pyrazole and the carboxymethyloxysubstituted phenyl ring.

Instead, I cannot reproduce the puckering on the pyridine ring as described by @venkata-ramaswamy-cresset, which I believe is due to lack of sanitization.
