### ISSUE TITLE
Include tautomers to substructure search

### ISSUE THREAD

**Issue by ivannnnnnnnnn** [rdkit/rdkit#6246] opened 2023-03-29 20:35 UTC
### Discussed in https://github.com/rdkit/rdkit/discussions/6245

<div type='discussions-op-text'>

<sup>Originally posted by **ivannnnnnnnnn** March 29, 2023</sup>
Hello, I am using rdkit 2022.9.3 and postgresql cartridge.  

When I make substructure search for this molecule I recieve many results in my database
SMILES: c1ccn2cnnc2c1
![image](https://user-images.githubusercontent.com/58053056/228559971-0fcfe854-1d96-44d8-a943-a5dbd56c4584.png)

But when I search by this molecule I dont receive any results
SMILES: N/N=c1/cccc[nH]1
![image](https://user-images.githubusercontent.com/58053056/228560366-ab358eb7-6bf2-4138-90d9-e37dce8483a6.png)

These molecules are tautomers and I would like to get the same results for the second molecule as I did for the first one. 

The search in ISIS base works like this

Can rdkit be configured so that the search works the same way?

Thank you
  

</div>

**Comment by greglandrum** [comment] 2023-03-30 03:09
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.

**Closed by greglandrum** 2023-03-30 03:09 UTC
