### ISSUE TITLE
rooted atom fingerprint non identical for the same molecules

### ISSUE THREAD

**Issue by nisti74** [rdkit/rdkit#811] opened 2016-03-14 21:40 UTC
When I calculate the rooted atom torsion fingerprint for various molecules that should be identical the fingerprints are not identical. Here is a simplified example

```python
m0 = Chem.MolFromMolBlock("""C6H6BN3
     RDKit          3D

 10 11  0  0  0  0  0  0  0  0999 V2000
   -0.0000   -0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.4000   -0.0000    0.0000 B   0  0  0  0  0  0  0  0  0  0  0  0
    2.9037   -3.0062    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.5722   -3.4388    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.5318   -2.5020    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    3.1948   -1.6368    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.1544   -0.7000    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    0.8229   -1.1326    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.8229    1.1326    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.1544    0.7000    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  9 10  2  0
 10  7  1  0
  7  6  1  0
  7  8  1  0
  3  4  1  0
  3  6  2  0
  4  5  2  0
  5  8  1  0
  8  1  2  0
  1  9  1  0
M  END
""")

m1 = Chem.MolFromMolBlock("""C6H6BN3
     RDKit          2D

 10 11  0  0  0  0  0  0  0  0999 V2000
   -0.0000   -0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.4000   -0.0000    0.0000 B   0  0  0  0  0  0  0  0  0  0  0  0
    0.8229    1.1326    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.1544    0.7000    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    2.1544   -0.7000    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    3.1948   -1.6368    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.9037   -3.0062    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.5722   -3.4388    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.5318   -2.5020    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    0.8229   -1.1326    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  1  3  1  0
  3  4  2  0
  4  5  1  0
  6  7  2  0
  7  8  1  0
  8  9  2  0
  5  6  1  0
 10  1  2  0
 10  9  1  0
  5 10  1  0
M  END
""")

In [5]: print Chem.MolToSmiles(m0), Chem.MolToSmiles(m1)
Bc1cnn2cccnc12 Bc1cnn2cccnc12
```
When I now do a rooted fingerprint based on the boron atom I get:

```python
BQuery = Chem.MolFromSmarts('B')
match0 = m0.GetSubstructMatch(BQuery)
nfp0 = Torsions.GetHashedTopologicalTorsionFingerprint(m0,nBits=9192,targetSize=7,fromAtoms=match0)
    
match1 = m1.GetSubstructMatch(BQuery)
nfp1 = Torsions.GetHashedTopologicalTorsionFingerprint(m1,nBits=9192,targetSize=7,fromAtoms=match1)
print nfp0.GetNonzeroElements(), nfp1.GetNonzeroElements()
{6040: 1, 8805: 1, 8373: 1, 8182: 1, 8087: 1} {6040: 1, 8151: 1, 8373: 1, 8182: 1, 8087: 1}
```
As one can see the positions 8151 and 8805 do not match between the molecules

When the molecules are canonicalised differently things look better:

```python
rank1 = Chem.CanonicalRankAtoms(m0)
m0 = Chem.RenumberAtoms(m0, rank1)
rank1 = Chem.CanonicalRankAtoms(m1)
m1 = Chem.RenumberAtoms(m1, rank1)
​
match0 = m0.GetSubstructMatch(BQuery)
match1 = m1.GetSubstructMatch(BQuery)
nfp0 = Torsions.GetHashedTopologicalTorsionFingerprint(m0,nBits=9192,targetSize=7,fromAtoms=match0)
nfp1 = Torsions.GetHashedTopologicalTorsionFingerprint(m1,nBits=9192,targetSize=7,fromAtoms=match1)
a1 = nfp0.GetNonzeroElements()
a2 = nfp1.GetNonzeroElements() 
a1 == a2
Out[77]:
True
```
This time also the FPs look better:

```python
print a1, a2
{6040: 1, 8805: 1, 8373: 1, 8182: 1, 8087: 1} {6040: 1, 8805: 1, 8373: 1, 8182: 1, 8087: 1}
```
but it is nothing I would think that I need to do.
Thx
NIk

**Comment by greglandrum** [comment] 2016-03-14 22:24
Confirmed.
This doesn't start until length of 7:
```
In [40]: rdMolDescriptors.GetHashedTopologicalTorsionFingerprint(m0, nBits=9192, targetSize=5, fromAtoms=[1]).GetNonzeroElements()
Out[40]: {3308: 1, 5473: 1, 5505: 1, 5568: 1}

In [41]: rdMolDescriptors.GetHashedTopologicalTorsionFingerprint(m1, nBits=9192, targetSize=5, fromAtoms=[1]).GetNonzeroElements()
Out[41]: {3308: 1, 5473: 1, 5505: 1, 5568: 1}

In [42]: rdMolDescriptors.GetHashedTopologicalTorsionFingerprint(m0, nBits=9192, targetSize=6, fromAtoms=[1]).GetNonzeroElements()
Out[42]: {1001: 1, 1944: 1, 6184: 1, 6187: 1, 9112: 1}

In [43]: rdMolDescriptors.GetHashedTopologicalTorsionFingerprint(m1, nBits=9192, targetSize=6, fromAtoms=[1]).GetNonzeroElements()
Out[43]: {1001: 1, 1944: 1, 6184: 1, 6187: 1, 9112: 1}

In [44]: rdMolDescriptors.GetHashedTopologicalTorsionFingerprint(m0, nBits=9192, targetSize=7, fromAtoms=[1]).GetNonzeroElements()
Out[44]: {6040: 1, 8087: 1, 8182: 1, 8373: 1, 8805: 1}

In [45]: rdMolDescriptors.GetHashedTopologicalTorsionFingerprint(m1, nBits=9192, targetSize=7, fromAtoms=[1]).GetNonzeroElements()
Out[45]: {6040: 1, 8087: 1, 8151: 1, 8182: 1, 8373: 1}
```

**Comment by nisti74** [comment] 2016-03-15 07:17
Yes - i found it while I was reusing some code from the work published on the fluorine fps. If it helps I should also be able to provide more sample pairs - just need to check for the non proprietary ones.

**Comment by greglandrum** [comment] 2016-03-15 08:36
No, I think that one should be adequate. Thanks.

**Comment by greglandrum** [comment] 2016-03-15 09:04
And the bit to show that it's in the underlying path hashing code:
```python
In [7]: rdMolDescriptors.GetTopologicalTorsionFingerprint(m0,targetSize=7,fromAtoms=[1]).GetNonzeroElements()
Out[7]: 
{740000472225829376: 1,
 740000472360047104: 1,
 740002739968299520: 1,
 758017069892784640: 1,
 1316498676643811840: 1}

In [8]: rdMolDescriptors.GetTopologicalTorsionFingerprint(m1,targetSize=7,fromAtoms=[1]).GetNonzeroElements()
Out[8]: 
{740000472225829376: 1,
 740000472360047104: 1,
 740002739968299520: 1,
 758052322849870336: 1,
 1316498676643811840: 1}
```

**Comment by greglandrum** [comment] 2016-03-15 09:49
Ok, found it: the bad bit in question is due to the "torsion" `BC1C=CNC=1' That's six atoms in total, but it adds up to seven when the closing carbon appears the second time.
The "canonicalization" code for the torsions does not deal with this properly.
Since these don't seem like they match the idea of what a torsion is at all, I think the right thing to do is just ignore them.
The fix is coming.

**Closed** 2016-03-18 11:36 UTC
Labels: bug
