### ISSUE TITLE
The calculated MCS is not the substructure of one parent SMILES

### ISSUE THREAD

**Issue by aqiph** [rdkit/rdkit#7580] opened 2024-07-02 07:05 UTC
I want to use the function rdFMCS.FindMCS() in rdkit to find the maximum common substructure of the following SMILES:
N=c1nc(N(Cc2ccc(C(F)(F)F)cc2)c2ccc(S(N)(=O)=O)cc2)cc[nH]1
N=c1nc(N(Cc2ccc(C(F)(F)F)cc2)c2ccc(S(N)(=O)=O)cc2)cc(Cl)[nH]1

The calculated MCS in SMARTS is N=C1:N:C:C:C(N(Cc2ccc(C(F)(F)F)cc2)c2ccc(S(N)(=O)=O)cc2):N:1

I want to plot the two molecules and highlight the MCS part.
However, 1. this SMARTS cannot be converted to SMILES; 2. when I try to match the MCS to the molecules, using mol.GetSubstructMatch(mcs_marts), the returned list of matched atoms is empty.

**To Reproduce**
Here is my code:

```
def cal_MCS_centroid(SMILESs):
    """
    Helper function to calculate the centroid defined as the MCS of the cluster
    :param SMILESs: list of str, list of SMILES
    :return: str, the centroid SMILES
    """
    # compute MCS
    mol_list = [Chem.MolFromSmiles(smiles) for smiles in SMILESs]
    mcs_SMARTS = rdFMCS.FindMCS(mol_list, ringMatchesRingOnly=True, completeRingsOnly=True,
                                bondCompare=rdFMCS.BondCompare.CompareOrderExact).smartsString

    # convert MCS from SMARTS format to SMILES format
    mcs_mol = Chem.MolFromSmarts(mcs_SMARTS)  # Not sanitize mol when coverting SMARTS to mol
    Chem.SanitizeMol(mcs_mol)
    mcs_SMILES = Chem.MolToSmiles(mcs_mol)
    try:
        mcs_SMILES = Chem.MolToSmiles(Chem.MolFromSmiles(mcs_SMILES, sanitize=True))
    except Exception:
        print('Error: Cannot convert pattern to proper SMILES, using pattern instead.')
    print(f'The MCS centroid is {mcs_SMILES}.')

    return mcs_SMILES

def plot_MCS_centroid(ID, SMILES, centroid):
    """
    Helper function for plotting
    :param ID: str, ID of the compound
    :param SMILES: str, compound SMILES
    :param centroid: str, MCS centroid SMARTS
    :return:
    """
    print(ID)
    mol = Chem.MolFromSmiles(SMILES)
    centroid_mol = Chem.MolFromSmarts(centroid)
    match_atoms = list(mol.GetSubstructMatch(centroid_mol))
    print(match_atoms)
    match_bonds = []
    for bond in centroid_mol.GetBonds():
        atom1 = match_atoms[bond.GetBeginAtomIdx()]
        atom2 = match_atoms[bond.GetEndAtomIdx()]
        match_bonds.append(mol.GetBondBetweenAtoms(atom1, atom2).GetIdx())

    # plot and save img
    d = rdMolDraw2D.MolDraw2DCairo(450, 400)
    rdMolDraw2D.PrepareAndDrawMolecule(d, mol, highlightAtoms=match_atoms, highlightBonds=match_bonds)
    d.FinishDrawing()
    filepath = Path(f'temp/{ID}.png')
    if not filepath.parent.exists():
        filepath.parent.mkdir()
    d.WriteDrawingText(f'temp/{ID}.png')
    print('Done')

if __name__ == '__main__':
    SMILESs = ['N=c1nc(N(Cc2ccc(C(F)(F)F)cc2)c2ccc(S(N)(=O)=O)cc2)cc[nH]1', 'N=c1nc(N(Cc2ccc(C(F)(F)F)cc2)c2ccc(S(N)(=O)=O)cc2)cc(Cl)[nH]1']
    mcs_SMILES =  cal_MCS_centroid(SMILESs)
    ID = 'test'
    SMILES = 'N=c1nc(N(Cc2ccc(C(F)(F)F)cc2)c2ccc(S(N)(=O)=O)cc2)cc[nH]1'
    plot_MCS_centroid(ID, SMILES, mcs_SMILES)
```

**Expected behavior**
I expect the code can calculate the MCS of the two SMILES, and plot the molecule with the MCS part highlighted

**Screenshots**

**Configuration (please complete the following information):**
 - RDKit version: 2023.09.05
 - OS: Sonoma 14.3
 - Python version (if relevant): 3.9
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge
 - If you are not using conda: how did you install the RDKit?

**Additional context**
I think the problem is related to the nitrogen in the aromatic ring. When the MSC is calculated, it looses the track of H position.

**Comment by greglandrum** [comment] 2024-07-02 10:59
I can't reproduce this with a recent RDKit release:
```
In [8]: rdkit.__version__
Out[8]: '2024.03.3'

In [9]: from rdkit.Chem import rdFMCS

In [10]: m1 = Chem.MolFromSmiles('N=c1nc(N(Cc2ccc(C(F)(F)F)cc2)c2ccc(S(N)(=O)=O)cc2)cc[nH]1')

In [11]: m2 = Chem.MolFromSmiles('N=c1nc(N(Cc2ccc(C(F)(F)F)cc2)c2ccc(S(N)(=O)=O)cc2)cc(Cl)[nH]1')

In [12]: mcs = rdFMCS.FindMCS([m1,m2],ringMatchesRingOnly=True, completeRingsOnly=True,
    ...: bondCompare=rdFMCS.BondCompare.CompareOrderExact)

In [13]: mcs.smartsString
Out[13]: '[#7&!R]=&!@[#6]1:&@[#7]:&@[#6](-&!@[#7&!R](-&!@[#6&!R]-&!@[#6]2:&@[#6]:&@[#6]:&@[#6]:&@[#6]:&@[#6]:&@2)-&!@[#6&!R](-&!@[#9&!R])(-&!@[#9&!R])-&!@[#9&!R])-&!@[#6]2:&@[#6]:&@[#6]:&@[#6](:&@[#6]:&@[#6]:&@2)-&!@[#16&!R](-&!@[#7&!R])(=&!@[#8&!R])=&!@[#8&!R]):&@[#6]:&@[#6]:&@[#7]:&@1'

In [15]: q = Chem.MolFromSmarts(mcs.smartsString)

In [17]: m1.HasSubstructMatch(q)
Out[17]: True

In [18]: m2.HasSubstructMatch(q)
Out[18]: True
```

In your code above you parse the SMARTS, sanitize the molecule (which generally doesn't make sense), and then convert to SMILES, thus losing *all* of the query information. It's not a big surprise to me that this doesn't work.

**Comment by greglandrum** [comment] 2024-07-02 11:00
I'm going to close this because I don't think it's a bug. Please let me know if I have misunderstood something.

**Closed by greglandrum** 2024-07-02 11:00 UTC

**Comment by aqiph** [comment] 2024-07-02 11:27
> I'm going to close this because I don't think it's a bug. Please let me know if I have misunderstood something.

Thanks for your reply.
Without sanitizing the molecule and converting to the SMILES, I can plot the molecule with MCS highlighted. Thanks! But can I somehow convert the SMARTS to SMILES? Because other softwares do not recognize the SMARTS format.

**Comment by greglandrum** [comment] 2024-07-03 03:43
> 
> Thanks for your reply. Without sanitizing the molecule and converting to the SMILES, I can plot the molecule with MCS highlighted. Thanks! But can I somehow convert the SMARTS to SMILES? Because other softwares do not recognize the SMARTS format.

There's no way to do this without information loss, often significant information loss. SMARTS includes features for expressing queries that cannot be encoded in SMILES. There's an explanation that you may find helpful here:
https://www.daylight.com/dayhtml/doc/theory/theory.smarts.html

**Comment by aqiph** [comment] 2024-07-03 03:54
> > Thanks for your reply. Without sanitizing the molecule and converting to the SMILES, I can plot the molecule with MCS highlighted. Thanks! But can I somehow convert the SMARTS to SMILES? Because other softwares do not recognize the SMARTS format.
> 
> There's no way to do this without information loss, often significant information loss. SMARTS includes features for expressing queries that cannot be encoded in SMILES. There's an explanation that you may find helpful here: https://www.daylight.com/dayhtml/doc/theory/theory.smarts.html

Thanks! I'll read through the material first.
