### ISSUE TITLE
AllChem.MolFromSmiles('F[Si-2](F)(F)(F)(F)F.[K+].[K+]') returns None

### ISSUE THREAD

**Issue by martinwk** [rdkit/rdkit#4326] opened 2021-07-12 14:22 UTC
**Describe the bug**
`AllChem.MolFromSmiles('F[Si-2](F)(F)(F)(F)F.[K+].[K+]')` does not return a Mol-object instance but None instead

**To Reproduce**
`AllChem.MolFromSmiles('F[Si-2](F)(F)(F)(F)F.[K+].[K+]') `

**Expected behavior**
would return a Mol-object

**Configuration (please complete the following information):**
 - RDKit version: 2021.03.4
 - OS: Win10 and CentOS
 - Python version 3.6:
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge
 - If you are not using conda: how did you install the RDKit?

**Comment by greglandrum** [comment] 2021-07-13 11:59
This is by design. The RDKit does not support sanitizing that hypervalent form of Si.
This could be changed, but we're going to have to think carefully about whether allowing the new valence state will create problems elsewhere.

In the meantime if you need to process molecules like this, you can disable sanitization on parsing the SMILES:
```
In [20]: m = Chem.MolFromSmiles('F[Si-2](F)(F)(F)(F)F.[K+].[K+]',sanitize=False)

In [21]: m.UpdatePropertyCache(strict=False)

In [22]: Chem.SanitizeMol(m,sanitizeOps=Chem.SANITIZE_ALL^Chem.SANITIZE_PROPERTIES)
Out[22]: rdkit.Chem.rdmolops.SanitizeFlags.SANITIZE_NONE
```

**Comment by martinwk** [comment] 2021-07-13 14:26
Ah I see. I am not a chemist so I cannot comprehend what this all implies. we are importing 100k smiles from the NORMANN suspect list (https://www.norman-network.com/?q=suspect-list-exchange) and will try to calculate descriptors of them. Is sanitizing of the SMILES always required to calculate the descriptors? I understand from [this blog](https://rdkit.blogspot.com/2016/09/avoiding-unnecessary-work-and.html) that partial sanitation is fine for some part of the rdkit functionality. But will rdkit raise an error when the required sanitation is not (yet) done?

Anyway, I will remove the bug label, as this is by design.

PS. the fact that the MOL object was not returned but a None instead, surprised me mostly because no error or warning was raised. But it turns out that the lack of raising a warning is a [known issue when using RDKit in windows](https://github.com/rdkit/rdkit/issues/2760). It took me some while to realize this though :)

**Comment by greglandrum** [comment] 2021-09-16 04:40
I'm closing this because it looks like the question is answered. Please reopen if necessary.

**Closed by greglandrum** 2021-09-16 04:40 UTC
