### ISSUE TITLE
Local energy minimization for hydrogens and bonds

### ISSUE THREAD

**Issue by haroldgrosjean** [rdkit/rdkit#4526] opened 2021-09-16 16:23 UTC
Hello,

For a QM simulation I have to extract a protein-ligand complex binding site residues. This will create breaks in the backbone with incorrect hybridization states. The way I am trying to correct that is by adding neighboring backbone atoms to the atom group (in MDanalysis) and generate a PDB from that:

[F126_BS_MOL_mda.pdb.txt](https://github.com/rdkit/rdkit/files/7179193/F126_BS_MOL_mda.pdb.txt)

Then, I plug this file into rdkit to change the nitrogens into carbons, modify hybridization states of these "fake" carbons to from SP2 to SP3 and add hydrogens to these atoms.

Here is the code:
```  
import rdkit as rdk
from rdkit import Chem
from rdkit.Chem import AllChem

F126_BS_mol_rdk = rdk.Chem.MolFromPDBFile('F126_BS_MOL_mda.pdb.txt', removeHs=False)
#This list was defined in MDAnalysis prior to the production of the above PDB
atoms_to_H = [384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403]
for atom in F126_BS_mol_rdk.GetAtoms():
    if atom.GetAtomicNum() == 7 and atom.GetIdx() in atoms_to_H::
        atom.SetAtomicNum(6)
        atom.SetHybridization(Chem.rdchem.HybridizationType.SP3)
        atom.SetNumExplicitHs(1)
F126_BS_mol_prot_rdk = Chem.AddHs(F126_BS_mol_rdk, addCoords=True, onlyOnAtoms=atoms_to_H)
Chem.MolToPDBFile(F126_BS_mol_prot_rdk, './F126_BS_H.pdb')
```
the molecule produced by this code is almost perfect but there one problem that I don't know how to address. The hydrogens seems to have been added in a semi-random way with non-optimal geometries which would create clashes during my calculation. See the images at the end. I tried to minimize the whole molecule with with:
```
AllChem.MMFFOptimizeMoleculeConfs(F126_BS_mol_prot_rdk, numThreads=12)
```
But this also distorts the rest of the correctly positioned atoms. Could you think of way to perform energy minimization on just the atoms listed in ```atoms_to_H``` and bonds with neighboring atoms whilst keeping the rest of the atoms frozen?

many thanks in advance for your help,

Regards,

Harold Grosjean

![Screenshot from 2021-09-16 17-13-27](https://user-images.githubusercontent.com/51821930/133647967-dfef4c64-b0b3-4814-b7c0-bf0e527aae80.png)

![Screenshot from 2021-09-16 17-16-24](https://user-images.githubusercontent.com/51821930/133648677-4d292719-4444-4932-9a77-41cb1997ca8f.png)

**Comment by greglandrum** [comment] 2021-09-16 16:41
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.

**Closed by greglandrum** 2021-09-16 16:41 UTC
Labels: bug
