### ISSUE TITLE
Errors calling AddConformer after RemoveAllConformers

### ISSUE THREAD

**Issue by maxentile** [rdkit/rdkit#5116] opened 2022-03-22 01:49 UTC
**Describe the bug**

When attempting to set all of a mol's conformers by removing its current conformers and adding new ones, two errors are encountered:
* Precondition error (`conf->getNumAtoms() != this->getNumAtoms()`) on first attempt to add a conformer
* Memory error on all subsequent attempts to add a conformer

**To Reproduce**

```python
import rdkit
print(f'RDKit version: {rdkit.__version__}')
from rdkit import Chem
from rdkit.Chem import AllChem

# make a random molecule and save multiple conformers
mol = Chem.AddHs(Chem.MolFromSmiles("C"))
AllChem.EmbedMultipleConfs(mol, numConfs=3)
all_conformers = list(mol.GetConformers())
print(f'# conformers: {len(all_conformers)}')

# double-check that all conformers have the correct number of atoms
n_atoms_in_mol = mol.GetNumAtoms()
for conf in all_conformers:
    n_atoms_in_conf = conf.GetNumAtoms()
    assert n_atoms_in_conf == n_atoms_in_mol
print(f'# atoms in each conf = {[conf.GetNumAtoms() for conf in all_conformers]}')
print(f'# atoms in mol = {n_atoms_in_mol}')

# remove all conformers
mol.RemoveAllConformers()  # NOTE: comment out this line to avoid subsequent errors

# add saved conformers
for i, conf in enumerate(all_conformers):
    print('-'*20)
    print(f'adding conformer {i}')
    
    try:
        mol.AddConformer(conf)
    except RuntimeError as e:
        print(f'RuntimeError\n{e}')  # conf->getNumAtoms() != this->getNumAtoms()
    except MemoryError as e:
        print(f'MemoryError\n{e}')
```

**Expected behavior**

`mol.AddConformer(conf)` adds a conformer to `mol` without error.

(Expected behavior can be recovered by commenting out `mol.RemoveAllConformers()` line above.)

**Configuration**
 - RDKit version: 2021.03.1 and 2021.09.5
 - OS: Ubuntu 20.04.2
 - Python version (if relevant):  3.7.12 and 3.9.10
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge
 - If you are not using conda: how did you install the RDKit? N/A

**Additional context**

Error message in RDKit version 2021.03.1:

<details>

```text
RDKit version: 2021.03.1
# conformers: 3
# atoms in each conf = [5, 5, 5]
# atoms in mol = 5
--------------------
adding conformer 0
[21:26:22] 

****
Pre-condition Violation
Number of atom mismatch
Violation occurred on line 627 in file /home/conda/feedstock_root/build_artifacts/rdkit_1616920161714/work/Code/GraphMol/ROMol.cpp
Failed Expression: conf->getNumAtoms() == this->getNumAtoms()
****

RuntimeError
Pre-condition Violation
	Number of atom mismatch
	Violation occurred on line 627 in file Code/GraphMol/ROMol.cpp
	Failed Expression: conf->getNumAtoms() == this->getNumAtoms()
	RDKIT: 2021.03.1
	BOOST: 1_74

--------------------
adding conformer 1
MemoryError

--------------------
adding conformer 2
MemoryError
```
</details>

Error message in RDKit version 2021.09.5:

<details>

```text
RDKit version: 2021.09.5
# conformers: 3
# atoms in each conf = [5, 5, 5]
# atoms in mol = 5
--------------------
adding conformer 0
[21:26:15] 

****
Pre-condition Violation
Number of atom mismatch
Violation occurred on line 654 in file /home/conda/feedstock_root/build_artifacts/rdkit_1646569108836/work/Code/GraphMol/ROMol.cpp
Failed Expression: conf->getNumAtoms() == this->getNumAtoms()
****

RuntimeError
Pre-condition Violation
	Number of atom mismatch
	Violation occurred on line 654 in file Code/GraphMol/ROMol.cpp
	Failed Expression: conf->getNumAtoms() == this->getNumAtoms()
	RDKIT: 2021.09.5
	BOOST: 1_74

--------------------
adding conformer 1
MemoryError

--------------------
adding conformer 2
MemoryError
```

</details>

**Comment by maxentile** [comment] 2022-03-22 01:52
(Possible duplicate of https://github.com/rdkit/rdkit/issues/3817)

**Comment by greglandrum** [comment] 2022-03-22 13:32
@maxentile this is a duplicate of that issue, so I'm going to close it.

**Closed by greglandrum** 2022-03-22 13:32 UTC
Labels: bug
