### ISSUE TITLE
DrawRDKitBits() fails due to kekulization errors on pyrazoles

### ISSUE THREAD

**Issue by tentrillion** [rdkit/rdkit#5971] opened 2023-01-13 22:05 UTC
**Describe the bug**
`DrawRDKitBits()` fails due to kekulization errors on pyrazoles.  I think this is very similar, probably identical, to https://github.com/rdkit/rdkit/issues/2164

**To Reproduce**
```
from rdkit import Chem
def rdkit_bit_drawer(mol):
    """
    Draws bit-index-labeled "submolecules" that illustrate the RDKit fingerprint of an rdkit mol
    """
    bit_info = {}   
    fp = Chem.RDKFingerprint(mol, bitInfo=bit_info)
    indices = fp.GetOnBits()
    list_bits = [(mol, idx, bit_info) for idx in indices]   # (mol, bit index, (atom and radius info))
    legends = [str(idx) for idx in indices]
    my_plot = Draw.DrawRDKitBits(list_bits, 
                                 molsPerRow=8,
                                 legends=legends,
                                 kekulize=False)
    return(my_plot)

rdkit_bit_drawer(Chem.MolFromSmiles('c1c(C)n[nH]c1'))
```

**Expected behavior**
I expected a plot similar to what is shown for this working example

```
def morgan_bit_drawer(mol, r):
    """
    Draws bit-index-labeled "submolecules" that illustrate the Morgan fingerprint of an rdkit mol
    """
    bit_info = {}   
    fp = AllChem.GetMorganFingerprintAsBitVect(mol, radius=r, bitInfo=bit_info)
    indices = fp.GetOnBits()
    list_bits = [(mol, idx, bit_info) for idx in indices]   # (mol, bit index, (atom and radius info))
    legends = [str(idx) for idx in indices]
    my_plot = Draw.DrawMorganBits(list_bits, 
                                  molsPerRow=8,
                                  legends=legends)   
    return(my_plot)

morgan_bit_drawer(Chem.MolFromSmiles('c1c(C)n[nH]c1'), 2)
```

**Screenshots**

**Configuration (please complete the following information):**
 - RDKit version: `2022.09.3`
 - OS: MacOS Monterey 12.1
 - Python version (if relevant): `'3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:25:29) [Clang 14.0.6 ]'`
 - Are you using conda? `yes`
 - If you are using conda, which channel did you install the rdkit from? `conda-forge`
 - If you are not using conda: how did you install the RDKit?

**Additional context**

**Comment by tentrillion** [comment] 2023-01-13 22:08
Additional context: I am trying to figure out why `RDKFingerprint()` gives a similarity of 1.0 for the following (to my eye, very similar) pyrazole tautomers, but `GetMorganFingerprint` doesn't, regardless of depth / radius.

```
smi_1 = 'c1c(C)n[nH]c1'
smi_2 = 'c1c(C)[nH]nc1'
smiles = [smi_1, smi_2]
mols = [Chem.MolFromSmiles(smi) for smi in smiles]

fps = [Chem.RDKFingerprint(mol) for mol in mols]
DataStructs.FingerprintSimilarity(fps[0], fps[1])
```

gives 1.0.

But:

```
morgans = [AllChem.GetMorganFingerprint(mol, 2) for mol in mols]
DataStructs.TanimotoSimilarity(morgans[0], morgans[1])
```
gives ~31% similarity.  I'm guessing this discrepancy is NOT related to this issue (but maybe?)

**Comment by greglandrum** [comment] 2023-01-14 04:41
As you suspected, this is a duplicate of #2164

**Closed by greglandrum** 2023-01-14 04:41 UTC
Labels: duplicate

**Comment by greglandrum** [comment] 2023-01-14 04:48
> Additional context: I am trying to figure out why `RDKFingerprint()` gives a similarity of 1.0 for the following (to my eye, very similar) pyrazole tautomers, but `GetMorganFingerprint` doesn't, regardless of depth / radius.
> 
> ```
> smi_1 = 'c1c(C)n[nH]c1'
> smi_2 = 'c1c(C)[nH]nc1'
> smiles = [smi_1, smi_2]
> mols = [Chem.MolFromSmiles(smi) for smi in smiles]
> 
> fps = [Chem.RDKFingerprint(mol) for mol in mols]
> DataStructs.FingerprintSimilarity(fps[0], fps[1])
> ```
> 
> gives 1.0.
> 
> But:
> 
> ```
> morgans = [AllChem.GetMorganFingerprint(mol, 2) for mol in mols]
> DataStructs.TanimotoSimilarity(morgans[0], morgans[1])
> ```
> 
> gives ~31% similarity. I'm guessing this discrepancy is NOT related to this issue (but maybe?)

This is expected behavior. The RDKit fingerprint does not look at the implicit H count on atoms, but the Morgan fingerprint does (because it takes the atom's overall degree into accout).

There's information about what the fingerprints consider here: https://www.rdkit.org/docs/RDKit_Book.html#additional-information-about-the-fingerprints.
