### ISSUE TITLE
2023-10-24 A confused bug

### ISSUE THREAD

**Issue by konglingjie2004** [rdkit/rdkit#6988] opened 2023-12-14 09:01 UTC
Sorry, I receiverd an error when I run "from rdkit import Chem". The error was copied below.
I have installed the RDKit using the conda command "conda install rdkit-pypi", and I run it successfully a few months ago. How can I solve it? Thank you for any help!

File D:\Anaconda\lib\site-packages\rdkit\__init__.py:22
     18 import sys
     20 # Need to import rdBase to properly wrap exceptions
     21 # otherwise they will leak memory
---> 22 from . import rdBase
     24 try:
     25   from .rdBase import rdkitVersion as __version__

ImportError: cannot import name 'rdBase' from partially initialized module 'rdkit' (most likely due to a circular import) (D:\Anaconda\lib\site-packages\rdkit\__init__.py)

**Comment by greglandrum** [comment] 2023-12-14 13:00
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.

**Closed by greglandrum** 2023-12-14 13:00 UTC
