### ISSUE TITLE
How to draw a molecular's highlight like this?

### ISSUE THREAD

**Issue by StefanIsSmart** [rdkit/rdkit#6143] opened 2023-02-28 01:31 UTC
Hi everyone!
I rencently find a figure like this:
It's so beautiful and I really want to konw how could I draw a moleluar like this:
1. Draw the highlighted atoms or bonds with the gradient color.
2. The shape of highlight is like this molecular

If you have an idea, Could you teach me ?

![image](https://user-images.githubusercontent.com/96673065/221728928-d35dfad2-80f6-4ca2-83e3-18ee0dccc33a.png)

**Comment by greglandrum** [comment] 2023-03-01 05:37
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.

**Closed by greglandrum** 2023-03-01 05:37 UTC
Labels: enhancement
