### ISSUE TITLE
CMake error: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object

### ISSUE THREAD

**Issue by hejops** [rdkit/rdkit#4456] opened 2021-08-30 11:10 UTC
**Describe the bug**

I am unable to compile RDKit with boost 1.71 (installed on Ubuntu as `libboost-all-dev`).

```
[ 14%] Linking CXX shared library ../../lib/libRDKitRDBoost.so
/usr/bin/ld: /usr/lib/python3.8/config-3.8-x86_64-linux-gnu/libpython3.8.a(call.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC

(many more errors of the same nature...)

collect2: error: ld returned 1 exit status
make[2]: *** [Code/RDBoost/CMakeFiles/RDBoost.dir/build.make:100: lib/libRDKitRDBoost.so.1.2021.09.1pre] Error 1
make[1]: *** [CMakeFiles/Makefile2:3885: Code/RDBoost/CMakeFiles/RDBoost.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```

Any advice would be much appreciated.

**To Reproduce**
```
RDBASE=~/rdkit
LD_LIBRARY_PATH=$RDBASE/lib:$LD_LIBRARY_PATH
PYTHONPATH=$RDBASE:$PYTHONPATH

cd "$RDBASE"
mkdir -p build
cd build

BOOST=/usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0

FLAGS=(

	-D BOOST_ROOT="$BOOST"
	-D Boost_NO_SYSTEM_PATHS=ON
	-D PYTHON_EXECUTABLE=/usr/bin/python3
	-D PYTHON_INCLUDE_DIRS=/usr/include/python3.8
)

cmake "${FLAGS[@]}" ..
```

**Configuration (please complete the following information):**
 - RDKit version: 69b143edd
 - OS: Ubuntu 20.04
 - Python version (if relevant): 3.8.10
 - Are you using conda? No
 - If you are not using conda: compiling from source

**Comment by greglandrum** [comment] 2021-09-02 03:36
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.

**Closed by greglandrum** 2021-09-02 03:36 UTC
Labels: bug
