### ISSUE TITLE
IPC Descriptor gives suspiciously large values

### ISSUE THREAD

**Issue by nhfechner** [rdkit/rdkit#1527] opened 2017-08-15 12:20 UTC
**Description:**

- RDKit Version: 2017.03.3
- Platform: macOS 10.12, Python 3.6

The IPC Descriptors (Descriptors.Ipc) returns extremely large values. The magnitude seems to be molecule size dependent. For instance [CHEMBL1688530](https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL1688530) gets an IPC result of 2.3821154332439293e+37 and the even larger [CHEMBL2104391](https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL2104391) gives 8.2105679140366688e+162 (all examples based on the smiles from ChEMBL).

I don't know if there is an actual problem with the implementation, but feature values in that magnitude might cause problems for data analysis (e.g. if single-precision floats are used for some reason), which is why I thought I bring it to attention.

Best,
Niko

**Comment by greglandrum** [comment] 2017-08-15 12:46
As implemented, the IPC descriptor does, indeed, have a significant size dependance, though this can be lessened by using the `avg=True` argument:
```
In [28]: for count in range(10):
    ...:     smi = 'C'*(5*count)
    ...:     print(count,GraphDescriptors.Ipc(Chem.MolFromSmiles(smi)),GraphDescriptors.Ipc(Chem.MolFromSmiles(smi),avg=True))
    ...:     
0 0.0 0.0
1 11.2451124978 1.4056390622295665
2 175.076747998 1.9671544718900458
3 2230.017479 2.2593895430561943
4 27005.6858313 2.4671739294114317
5 319037.012823 2.628133523535876
6 3715181.66 2.759613167945485
7 42861560.3341 2.8707669004771117
8 491284532.844 2.967049851976642
9 5604382120.02 3.0519772326603065
```
I no longer have access to a copy of the original article (http://aip.scitation.org/doi/abs/10.1063/1.434593), so I can't really comment as to whether or not the current behavior is correct.

**Comment by nhfechner** [comment] 2017-08-15 13:32
Thanks for point out the avg=True option. That could provide a workaround.

As a side note: I found in the scikit-learn [Random Forest docs](http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html#sklearn.ensemble.RandomForestClassifier.fit) the explicit hint, that the input data will be converted to float32. Thus, the default behaviour of the descriptor will cause problems with scikit-learn for larger molecules.

**Comment by greglandrum** [comment] 2017-08-15 13:49
Given that the descriptor is probably meaningless for such large molecules anyway, this seems unlikely to be thst serious of a problem. ;-)

**Comment by greglandrum** [comment] 2017-09-09 03:35
Closing this because I think that the question has been answered. Please re-open if that's not the case.

**Closed by greglandrum** 2017-09-09 03:35 UTC
Labels: wontfix

**Comment by Adel7776** [comment] 2022-12-13 11:50
I am using the following code, and I am still getting a high value of IPC. Maybe I used the avg=True in the wrong place. The code is below:
from rdkit.Chem import Descriptors
from rdkit import Chem
desc_list = [n[0] for n in Descriptors._descList]
print(len(desc_list))
print(desc_list)
from rdkit.ML.Descriptors import MoleculeDescriptors
smiles = ['CCC1C(C=C(C=CC(=O)C(CC(C(C(C(CC(=O)O1)O)C)OC2C(C(C(C(O2)C)OC3CC(C(C(O3)C)O)(C)O)N(C)C)O)CC=O)C)C)COC4C(C(C(C(O4)C)O)OC)OC']
mols = [Chem.MolFromSmiles(smi) for smi in smiles]
calc = MoleculeDescriptors.MolecularDescriptorCalculator(desc_list, avg=True)
rdkit_desc = [calc.CalcDescriptors(m) for m in mols]
print(len(rdkit_desc[0]))
print(rdkit_desc[0])

**Comment by thegodone** [comment] 2022-12-13 16:59
I had same issue last week and deactivated it. Can anyone tell me the exact definition IPC please?GuillaumeEnvoyé de mon iPhoneLe 13 déc. 2022 à 12:51, Adel7776 ***@***.***> a écrit :﻿
I am using the following code, and I am still getting a high value of IPC. Maybe I used the avg=True in the wrong place. The code is below:
from rdkit.Chem import Descriptors
from rdkit import Chem
desc_list = [n[0] for n in Descriptors._descList]
print(len(desc_list))
print(desc_list)
from rdkit.ML.Descriptors import MoleculeDescriptors
smiles = ['CCC1C(C=C(C=CC(=O)C(CC(C(C(C(CC(=O)O1)O)C)OC2C(C(C(C(O2)C)OC3CC(C(C(O3)C)O)(C)O)N(C)C)O)CC=O)C)C)COC4C(C(C(C(O4)C)O)OC)OC']
mols = [Chem.MolFromSmiles(smi) for smi in smiles]
calc = MoleculeDescriptors.MolecularDescriptorCalculator(desc_list, avg=True)
rdkit_desc = [calc.CalcDescriptors(m) for m in mols]
print(len(rdkit_desc[0]))
print(rdkit_desc[0])

**Comment by thegodone** [comment] 2022-12-13 17:17
Just exclude it in the for loop based on the descriptor name. I willCheck later the code in source code rdkit.Envoyé de mon iPhoneLe 13 déc. 2022 à 18:07, Adel7776 ***@***.***> a écrit :﻿
How to deactivate it?
IPC is the information content of the coefficients of the characteristic polynomial of the adjacency matrix of a hydrogen-suppressed graph of a molecule (the complexity of a compound).  You may find more details in this article (Quantitative structure-activity relationships for green algae growth inhibition by polymer particles).

**Comment by thegodone** [comment] 2022-12-14 04:53
```
from rdkit import Chem
from rdkit.Chem import GraphDescriptors
for count in range(10):
    smi = 'C'*(5*count)
    print(count,GraphDescriptors.Ipc(Chem.MolFromSmiles(smi)),GraphDescriptors.Ipc(Chem.MolFromSmiles(smi),avg=True))
```
if you do this instead of your code it works so the answer is change the code as Greg said. 

But I think the default value avg should be True.

**Comment by Adel7776** [comment] 2022-12-14 05:23
Now, we should call the IPC (the average IPC) as described by the original article (http://aip.scitation.org/doi/abs/10.1063/1.434593).

**Comment by thegodone** [comment] 2022-12-14 05:47
In molecular descriptors for Chemoinformatics: page 413 Ipc refer to total information content or negentropy and Ipc average is the mean information content also called Shannon's entropy
https://onlinelibrary.wiley.com/doi/book/10.1002/9783527628766

**Comment by greglandrum** [comment] 2022-12-24 07:33
The RDKit's implementation of IPC is based on the original paper from Bonchev and Trinajstić (http://aip.scitation.org/doi/abs/10.1063/1.434593). It's the information content of the coefficients of the characteristic polynomial for the molecular graph.
The nature of IPC is that it gets larger as a molecule gets more branched, so a large molecule with a lot of branches is going to lead to huge IPC values. This isn't a bug, it's just the definition of the descriptor.

I'm not comfortable making `avg=True` (which should make it so that the values for larger branched molecules don't explode) the default since that's calculating a different descriptor, but we can add a new descriptor, AvgIPC, which calls IPC with `avg=True`.

**Comment by greglandrum** [comment] 2022-12-24 07:45
In #5896 I've added a new descriptor, `AvgIpc`, which calculates the IPC value with `avg=True`:
```
In [4]: smiles = 'CCC1C(C=C(C=CC(=O)C(CC(C(C(C(CC(=O)O1)O)C)OC2C(C(C(C(O2)C)OC3CC(C(C(O3)C)O)(C)O)N(C)C)O)
   ...: CC=O)C)C)COC4C(C(C(C(O4)C)O)OC)OC'
   ...: m = Chem.MolFromSmiles(smiles)
   ...: GraphDescriptors.AvgIpc(m)
Out[4]: 3.2254186293085794
```
This will be in the 2023.03 release.

**Comment by Adel7776** [comment] 2022-12-24 07:52
I got IPc value of 5356.941 for Primidone (formula: C12H14N2O2) and 1876.09 for caffeine (formula: C8H10N4O2). I don't think that they should have such difference based on the branching.

**Comment by greglandrum** [comment] 2022-12-25 06:57
@Adel7776 As far as I can tell, the RDKit implementation of IPC does what is described in the original paper. It certainly reproduces the small number of example values which were given in that paper. I don't find the descriptor itself to be usefully interpretable, so I can't really comment on that.

**Comment by Adel7776** [comment] 2022-12-25 07:12
Thank you so much!

**Comment by Adel7776** [comment] 2023-03-21 12:17
Dear @greglandrum, I am wondering what is the difference between ATS and ATSC. I understand that ATS is the Moreau-Broto autocorrelation and ATSC is the **centered** Moreau-Broto autocorrelation. The computation of ATS is clear from the handbook of molecular descriptors. It would be great if you can explaining what the centered (c) adds to the calculation (i.e., ATSC). Thanks.
