### ISSUE TITLE
Test suite failures if eigen3 is not available

### ISSUE THREAD

**Issue by mbanck** [rdkit/rdkit#3740] opened 2021-01-17 16:55 UTC
**Describe the bug**

The testsuite testcase #85 fails like this for me:

```
 85/179 Test  #85: pyMolDescriptors .......................***Failed    0.52 sec
Traceback (most recent call last):
  File "/build/rdkit-vngW4C/rdkit-202009.1/Code/GraphMol/Descriptors/Wrap/testMolDescriptors.py", line 5, in <module>
    from rdkit.Chem import rdMolDescriptors as rdMD, Descriptors
  File "/build/rdkit-vngW4C/rdkit-202009.1/obj-x86_64-linux-gnu/rdkit/Chem/Descriptors.py", line 222, in <module>
    _du.VectorDescriptorWrapper(_rdMolDescriptors.BCUT2D, names=names, version="1.0.0", namespace=locals())
AttributeError: module 'rdkit.Chem.rdMolDescriptors' has no attribute 'BCUT2D'
```

**To Reproduce**

Run the test suite

**Expected behavior**

Testsuite testcase #85 succeeds.

**Configuration (please complete the following information):**
 - RDKit version: 202009.1
 - OS: Debian unstable
 - Python version (if relevant): 3.9.1
 - Are you using conda? no
 - If you are not using conda: how did you install the RDKit? from source

**Comment by ricrogz** [comment] 2021-01-17 19:18
@mbanck I think this might have been fixed in PRs #3512 and/or #3513. It should work in Release 2020_09_2, but I'd recommend you to try to the last available patch version in the 2020_09 branch, [Release 2020_09_3](https://github.com/rdkit/rdkit/releases/tag/Release_2020_09_3)

**Comment by mbanck** [comment] 2021-01-17 19:19
Oh, I should've double-checked about newer point releases, sorry.

Will check out the 202009.3 release, thanks

**Comment by mbanck** [comment] 2021-01-17 21:25
I'm still getting that failure with 202009.3

**Comment by ricrogz** [comment] 2021-01-19 14:05
> I'm still getting that failure with 202009.3

I cannot reproduce the problem, I'm sorry. I think there might be something wrong with your build or your test environment.

**Comment by mbanck** [comment] 2021-01-19 14:13
You can also see it here: https://buildd.debian.org/status/fetch.php?pkg=rdkit&arch=amd64&ver=202009.3-1&stamp=1610926128&raw=0 if you search for `BCUT2D`

**Comment by ricrogz** [comment] 2021-01-19 14:28
Aha. I think I see the problem:

```
-- Could NOT find Eigen3 (missing: EIGEN3_INCLUDE_DIR EIGEN3_VERSION_OK) (Required is at least version "2.91.0")
Eigen3 not found, disabling the Descriptors3D build.
```

BCUT descriptors, apparently, only build if EIGEN is available:
https://github.com/rdkit/rdkit/blob/aa6524e148633d148d62560e13b7140225813531/Code/GraphMol/Descriptors/BCUT.cpp#L10

... but even if they haven't been built, the Python module tries to load them. I'll give it a look. In the mean time, you might want to add Eigen3 to the build :)

**Comment by mbanck** [comment] 2021-01-19 14:42
Ah, good catch, thanks!

**Comment by bp-kelley** [comment] 2021-01-19 17:21
It’s still a bug, the test shouldn’t be run without eigen.  I’ll fix it.

**Comment by bp-kelley** [comment] 2021-01-19 17:21
Ah, @ricrogz already assigned it.  Nice.

**Closed** 2021-01-26 04:14 UTC
Labels: bug
