### ISSUE TITLE
neutralizing molecules

### ISSUE THREAD

**Issue by kovasap** [rdkit/rdkit#1012] opened 2016-08-09 19:33 UTC
I've been using the method linked [here](http://www.rdkit.org/docs/Cookbook.html#neutralizing-charged-molecules) for a while to neutralize charged molecules with success.  However, I recently ran into the following molecule:

InChI=1S/C15H22N6O5S/c1-27(3-2-7(16)15(24)25)4-8-10(22)11(23)14(26-8)21-6-20-9-12(17)18-5-19-13(9)21/h5-8,10-11,14,22-23H,2-4,16H2,1H3,(H2-,17,18,19,24,25)/q+1

, which I can't seem to neutralize.  I think the best solution would be to add another 'reaction' to the method I linked above, but I'm having a hard time figuring out what to add.  Specifically, I'm looking at the charged nitrogen in the ring with a double bond to it.  What SMARTS/SMILES pair would help me do this?  Also, if a better way to neutralize molecules has been added to RDKit that would be great to know!  

Thanks!

**Comment by greglandrum** [comment] 2016-08-10 06:58
I would assume that the problem is that the charged nitrogen in that molecule has a radical:

![image](https://cloud.githubusercontent.com/assets/540511/17544493/ee360f12-5ed7-11e6-8744-d388f6484813.png)

The missing electron that gives rise to the radical is the source of the positive charge.

The patterns that Hans provided just don't address radicals at all.

I'll put a bit of thought into it and see if I can come up with a reasonable hack to deal with these as well.

**Comment by kovasap** [comment] 2016-08-10 17:22
Oh that makes sense!  I didn't see the dot...  Is there a way to address this by looking for radical containing atoms and just removing their radical property?

**Comment by kovasap** [comment] 2016-08-10 17:50
This is a slightly different problem, but is there a way to add a term to Hans' script to neutralize charges on something like this?

![image](https://cloud.githubusercontent.com/assets/8763010/17564335/fd3ab0a2-5ee7-11e6-8220-73bb612834cd.png)
InChI=1S/H4O7P2/c1-8(2,3)7-9(4,5)6/h(H2,1,2,3)(H2,4,5,6)/p-4



Would the chemical equivalence of the oxygens get in the way?

Thanks for your help!

**Comment by greglandrum** [comment] 2016-08-11 06:22
Here's a small function that neutralizes positive charges caused by radicals:
```
def neutralizeRadicals(mol):
     for a in mol.GetAtoms():
         if a.GetNumRadicalElectrons()==1 and a.GetFormalCharge()==1:
             a.SetNumRadicalElectrons(0)         
             a.SetFormalCharge(0)
```
Note that this is very conservative about the case it handles.

Here's usage on your example:
```
In [2]: m =Chem.MolFromInchi('InChI=1S/C15H22N6O5S/c1-27(3-2-7(16)15(24)25)4-8-10(22)11(23)14(26-8)21-6-20-9-12(17)18-5-19-13(9)21/h5-8,10-11,14,22-23H,2-4,16H2,1H3,(H2-,17,18,19,24,25)/q+1')

In [3]: Chem.MolToSmiles(m,True)
Out[3]: 'C[S+](CCC(N)C(=O)[O-])CC1OC(N2C=[N+]c3c(N)ncnc32)C(O)C1O'

In [6]: neutralizeRadicals(m)

In [7]: Chem.SanitizeMol(m)
Out[7]: rdkit.Chem.rdmolops.SanitizeFlags.SANITIZE_NONE

In [8]: Chem.MolToSmiles(m,True)
Out[8]: 'C[S+](CCC(N)C(=O)[O-])CC1OC(n2cnc3c(N)ncnc32)C(O)C1O'
```

**Comment by greglandrum** [comment] 2016-08-11 06:29
On the phosphate question: I believe that Hans' code should handle that already.
Here's the rule:
```
        # Carboxylic acids and alcohols
        ('[$([O-]);!$([O-][#7])]','O'),
```
and it does seem to work:
```
In [5]: neutralize.NeutraliseCharges('[O-]P([O-])(=O)OP(=O)([O-])[O-]')
Out[5]: ('O=P(O)(O)OP(=O)(O)O', True)
```

**Comment by kovasap** [comment] 2016-08-18 19:17
Ok everything works now!  Thanks for your help.  I had modified Hans script to take in a mol object and work directly on that (instead of an inchi or smiles string), but I think the mols I fed into it were not very well standardized.

**Comment by greglandrum** [comment] 2016-08-19 04:46
Cool, closing this. If anything else comes up here feel free to reopen it.

**Closed by greglandrum** 2016-08-19 04:46 UTC
Labels: question
