### ISSUE TITLE
MolFromMolBlock loses stereochemistry information in molfile

### ISSUE THREAD

**Issue by adelinepetersen** [rdkit/rdkit#5720] opened 2022-11-01 22:11 UTC
**Describe the bug**
We've noticed that some stereochemistry information is lost when using `MolFromMolBlock`. Specifically, it looks like if there is an atom with both a wedged and dashed bond coming from it, RDKit will make one of these bonds "normal" and will lose the stereochemical information. It seems that the relevant geometry information needed to correctly assign stereochemistry is still present, but the molfile loses stereochemistry information and affects its rendering. This might be related to [this filed `WedgeMolBonds` issue](https://github.com/rdkit/rdkit/issues/5067).

**To Reproduce**
```
In [9]: print(molfile_with_correct_bonds)

  MJ211100                      

 10 10  0  0  1  0  0  0  0  0999 V2000
    1.0286    0.6100    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.2161    0.7533    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0660    1.5286    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.3141    0.1213    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8444    0.7533    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.4003   -0.2911    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.4003   -1.1161    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.3141   -1.5286    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.0286   -1.1161    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.0286   -0.2911    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  2  0  0  0  0
  2  3  1  0  0  0  0
  4  2  1  1  0  0  0
  4  5  1  6  0  0  0
  4  6  1  0  0  0  0
  6  7  1  0  0  0  0
  7  8  1  0  0  0  0
  8  9  1  0  0  0  0
  9 10  1  0  0  0  0
  4 10  1  0  0  0  0
M  END

In [10]: rdkit_molecule = Chem.MolFromMolBlock(molfile_with_correct_bonds)

In [11]: molfile_with_incorrect_bonds = Chem.MolToMolBlock(rdkit_molecule)

In [12]: print(molfile_with_incorrect_bonds)

     RDKit          2D

 10 10  0  0  1  0  0  0  0  0999 V2000
    1.0286    0.6100    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.2161    0.7533    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0660    1.5286    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.3141    0.1213    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8444    0.7533    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.4003   -0.2911    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.4003   -1.1161    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.3141   -1.5286    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.0286   -1.1161    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.0286   -0.2911    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  2  0
  2  3  1  0
  4  2  1  0
  4  5  1  6
  4  6  1  0
  6  7  1  0
  7  8  1  0
  8  9  1  0
  9 10  1  0
  4 10  1  0
M  END
```

**Expected behavior**
I would expect that `MolFromMolBlock` would preserve all stereocenters. Specifically, when we compared the molfiles before and after transformation with `MolFromMolBlock`, we can see that the `1` in the 3rd row and 4th column of the bond matrix in the molfile before transformation becomes `0` after transformation. 

**Screenshots**
The first screenshot represents the first molfile, with all stereochemistry information. 
![image](https://user-images.githubusercontent.com/35797714/199351382-cbb7d050-5f2d-4132-88e9-63b34aa52c3b.png)

The second screenshot represents the second molfile, which has been parsed through `MolFromMolBlock` and has lost stereochemistry information.
![image](https://user-images.githubusercontent.com/35797714/199351613-cf0d7a38-0839-47e1-92ee-2c4b31fa2b95.png)

**Comment by greglandrum** [comment] 2022-11-02 03:50
I do not believe that this is a bug. 
Those two molecules are the same: you do not need two wedged bonds to indicate the stereochemistry of an atom unambiguously.

The RDKit makes no attempt to exactly preserve the input wedging you provide when it generates output mol blocks. The wedging in the input structure is used to assign stereochemistry to the atom and then that stereochemistry is used to wedge the bonds which are written to an output mol file. The output wedging may be completely different, but the structure should still be correct.

As I mentioned in the comments on #5067 : we do plan to add support for adding multiple wedges for people who would like to follow IUPAC drawing guidelines, but it's not clear when that will happen.

**Comment by greglandrum** [comment] 2022-11-02 03:52
@adelinepetersen I'm closing this since I believe that it's not a bug. If you disagree, please feel free to provide additional explanation and re-open the issue.

**Closed by greglandrum** 2022-11-02 03:52 UTC
Labels: not a bug
