### ISSUE TITLE
InChI/SMILES conversion issues for InChI=1/C3H2/c1-3-2/h1-2H

### ISSUE THREAD

**Issue by pierrelb** [rdkit/rdkit#542] opened 2015-07-20 19:27 UTC
Here is the structure according to NIST (InChI trust certified).
http://webbook.nist.gov/cgi/cbook.cgi?ID=C2008197&Units=SI

When the SMILES `[CH]C#C` is used to make a molecule, the correct InChI is generated `InChI=1/C3H2/c1-3-2/h1-2H`.
When the reverse is done, the generated SMILES is the charged species `[CH-]=C=[CH3+]`.

**Comment by greglandrum** [comment] 2015-07-20 19:58
Confirmed: that's a bug.

**Comment by greglandrum** [comment] 2015-07-21 14:39
some more info for tracking this down.

here are a few where things are fine:
```
In [8]: Chem.MolToInchi(Chem.MolFromSmiles('CC#[C]'))
Out[8]: 'InChI=1S/C3H3/c1-3-2/h1H3'
In [9]: Chem.MolToSmiles(Chem.MolFromInchi(_8))
Out[9]: '[C]#CC'
```
```
In [15]: Chem.MolToInchi(Chem.MolFromSmiles('CC=[C]'))
Out[15]: 'InChI=1S/C3H4/c1-3-2/h3H,1H3'
In [16]: Chem.MolToSmiles(Chem.MolFromInchi(_15))
Out[16]: '[C]=CC'
```
```
In [23]: Chem.MolToInchi(Chem.MolFromSmiles('CC=[CH]'))
Out[23]: 'InChI=1S/C3H5/c1-3-2/h1,3H,2H3'
In [24]: Chem.MolToSmiles(Chem.MolFromInchi(_23))
Out[24]: '[CH]=CC'
```
And some breakage:
```
In [18]: Chem.MolToInchi(Chem.MolFromSmiles('[CH]C=C'))
Out[18]: 'InChI=1S/C3H4/c1-3-2/h1,3H,2H2'
In [19]: Chem.MolToSmiles(Chem.MolFromInchi(_18))
Out[19]: '[CH-]=C[CH4+]'
```
```
In [25]: Chem.MolToInchi(Chem.MolFromSmiles('[CH]=CC=[CH]'))
Out[25]: 'InChI=1S/C4H4/c1-3-4-2/h1-4H'
In [26]: Chem.MolToSmiles(Chem.MolFromInchi(_25))
Out[26]: '[CH-]=CC=[CH3+]'
```

**Comment by greglandrum** [comment] 2015-07-22 13:58
After spending some time on this, I'm changing my opinion on this one.

Here's some output from using the InChI code.

Using AuxInfo things are ok:
```
~/RDKit_git/External/INCHI-API > cat test_data/github542.1.mol

  Mrv0541 07221508262D          

  3  2  0  0  0  0            999 V2000
   -5.4804    3.0938    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -4.6554    3.0938    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -3.8304    3.0938    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  2  3  3  0  0  0  0
M  RAD  1   1   1
M  END
~/RDKit_git/External/INCHI-API > /tmp/INCHI-1-API/INCHI/gcc/inchi-1/inchi-1 test_data/github542.1.mol
InChI version 1, Software version 1.04 Build of September 9, 2011
Opened log file 'test_data/github542.1.mol.log'
Opened input file 'test_data/github542.1.mol'
Opened output file 'test_data/github542.1.mol.txt'
Opened problem file 'test_data/github542.1.mol.prb'
The command line used:
"/tmp/INCHI-1-API/INCHI/gcc/inchi-1/inchi-1 test_data/github542.1.mol"
Generating standard InChI
Input format: MOLfile
Output format: Plain text
Full Aux. info
Timeout per structure: 60.000 sec
Up to 1024 atoms per structure

End of file detected after structure #1.   
Finished processing 1 structure: 0 errors, processing time 0:00:00.00
~/RDKit_git/External/INCHI-API > cat test_data/github542.1.mol.txt
* Input_File: "test_data/github542.1.mol"
Structure: 1
InChI=1S/C3H2/c1-3-2/h1-2H
AuxInfo=1/0/N:1,3,2/E:(1,2)/CRV:1t/rA:3nC.3CC/rB:s1;t2;/rC:-5.4804,3.0938,0;-4.6554,3.0938,0;-3.8304,3.0938,0;
~/RDKit_git/External/INCHI-API > /tmp/INCHI-1-API/INCHI/gcc/inchi-1/inchi-1 -STDIO -OutputSDF -InpAux < test_data/github542.1.mol.txt
InChI version 1, Software version 1.04 Build of September 9, 2011
Log file not specified. Using standard error output.
Input file not specified. Using standard input.
Output file not specified. Using standard output.
The command line used:
"/tmp/INCHI-1-API/INCHI/gcc/inchi-1/inchi-1 -STDIO -OutputSDF -InpAux"
Output SDfile only without stereochemical information and atom coordinates
Input format: InChI AuxInfo (plain)
Output format: SDfile only
Timeout per structure: 60.000 sec
Up to 1024 atoms per structure

Structure #1
  InChIV10                                     

  3  2  0  0  0  0  0  0  0  0  2 V2000
   -5.4804    3.0938    0.0000 C   0  0  0     0  0  0  0  0  0
   -4.6554    3.0938    0.0000 C   0  0  0     0  0  0  0  0  0
   -3.8304    3.0938    0.0000 C   0  0  0     0  0  0  0  0  0
  1  2  1  0  0  0  0
  2  3  3  0  0  0  0
M  RAD  1   1   3
M  END
$$$$
End of file detected after structure #1.   
Finished processing 1 structure: 0 errors, processing time 0:00:00.00
```

But if you leave the original AuxInfo out, the InChI code does the same thing the RDKit does:
```
~/RDKit_git/External/INCHI-API > /tmp/INCHI-1-API/INCHI/gcc/inchi-1/inchi-1 -AuxNone test_data/github542.1.mol
InChI version 1, Software version 1.04 Build of September 9, 2011
Opened log file 'test_data/github542.1.mol.log'
Opened input file 'test_data/github542.1.mol'
Opened output file 'test_data/github542.1.mol.txt'
Opened problem file 'test_data/github542.1.mol.prb'
The command line used:
"/tmp/INCHI-1-API/INCHI/gcc/inchi-1/inchi-1 -AuxNone test_data/github542.1.mol"
Generating standard InChI
Input format: MOLfile
Output format: Plain text
Aux. info suppressed
Timeout per structure: 60.000 sec
Up to 1024 atoms per structure

End of file detected after structure #1.   
Finished processing 1 structure: 0 errors, processing time 0:00:00.00
~/RDKit_git/External/INCHI-API > cat test_data/github542.1.mol.txt
* Input_File: "test_data/github542.1.mol"
Structure: 1
InChI=1S/C3H2/c1-3-2/h1-2H
~/RDKit_git/External/INCHI-API > /tmp/INCHI-1-API/INCHI/gcc/inchi-1/inchi-1 -InChI2Struct test_data/github542.1.mol.txt 
InChI version 1, Software version 1.04 Build of September 9, 2011
Opened log file 'test_data/github542.1.mol.txt.log'
Opened input file 'test_data/github542.1.mol.txt'
Opened output file 'test_data/github542.1.mol.txt.txt'
Opened problem file 'test_data/github542.1.mol.txt.prb'
The command line used:
"/tmp/INCHI-1-API/INCHI/gcc/inchi-1/inchi-1 -InChI2Struct test_data/github542.1.mol.txt"
Converting InChI(s) to structure(s) in aux. info format
Input format: InChI (plain identifier)
Output format: Plain text
Full Aux. info
Timeout per structure: 60.000 sec
Up to 1024 atoms per structure

1: Structure: 1
End of file detected after structure 1.    
Finished processing 1 structure: 0 errors, processing time 0:00:00.00
~/RDKit_git/External/INCHI-API > ls -l test_data/github542.1.mol.txt.txt
-rw-r--r--  1 landrgr1  landrgr1  153 Jul 22 09:37 test_data/github542.1.mol.txt.txt
~/RDKit_git/External/INCHI-API > cat test_data/github542.1.mol.txt.txt
* Input_File: "test_data/github542.1.mol.txt"
Structure: 1
InChI=1S/C3H2/c1-3-2/h1-2H
AuxInfo=1/0/N:1,2,3/E:(1,2)/CRV:1+1,2-1/rA:3C+C-C/rB:;d1d2;/rC:;;;
~/RDKit_git/External/INCHI-API > /tmp/INCHI-1-API/INCHI/gcc/inchi-1/inchi-1 -STDIO -OutputSDF -InpAux < test_data/github542.1.mol.txt.txt
InChI version 1, Software version 1.04 Build of September 9, 2011
Log file not specified. Using standard error output.
Input file not specified. Using standard input.
Output file not specified. Using standard output.
The command line used:
"/tmp/INCHI-1-API/INCHI/gcc/inchi-1/inchi-1 -STDIO -OutputSDF -InpAux"
Output SDfile only without stereochemical information and atom coordinates
Input format: InChI AuxInfo (plain)
Output format: SDfile only
Timeout per structure: 60.000 sec
Up to 1024 atoms per structure

Structure #1
  InChIV10                                     

  3  2  0  0  0  0  0  0  0  0  2 V2000
    0.0000    0.0000    0.0000 C   0  3  0     0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  5  0     0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0     0  0  0  0  0  0
  1  3  2  0  0  0  0
  2  3  2  0  0  0  0
M  CHG  2   1   1   2  -1
M  END
$$$$
End of file detected after structure #1.   
Finished processing 1 structure: 0 errors, processing time 0:00:00.00
```

The situation is ugly, but I think it indicates that the problem is not really the RDKit; in order to handle this correctly we would need to include the AuxInfo in the InChI->molecule conversion.

Given that InChI is not really intended to be a molecule interchange format, and that dealing with the AuxInfo would be a large amount of work, I'm going to mark this as "WontFix"

**Comment by bp-kelley** [comment] 2016-02-14 02:39
@greglandrum perhaps close this?

**Closed** 2016-02-14 04:34 UTC
Labels: wontfix
