### ISSUE TITLE
KekulizeException when enumerating tautomers

### ISSUE THREAD

**Issue by sdecesco** [rdkit/rdkit#6020] opened 2023-01-26 13:51 UTC
**Describe the bug**
I am encountering a KekulizeException when enumerating tautomers. 

**To Reproduce**
``` 
from rdkit import Chem
from rdkit.Chem.MolStandardize import rdMolStandardize

mol = Chem.MolFromSmiles("Cc1nc2n(c(=O)c1CCN1CCC(C3NOc4cc(F)ccc43)CC1)CCCC2") 
```

![image](https://user-images.githubusercontent.com/36763600/214848552-4de565cb-8379-4740-9aa8-d2d015e34da7.png)

``` 
enumerator = rdMolStandardize.TautomerEnumerator()

tautomers = enumerator.Enumerate(mol)
```

```
[14:33:18] Can't kekulize mol.  Unkekulized atoms: 3 7

---------------------------------------------------------------------------
KekulizeException                         Traceback (most recent call last)
<ipython-input-73-c032e66b3645> in <module>
      6 enumerator = rdMolStandardize.TautomerEnumerator()
      7 
----> 8 tautomers = enumerator.Enumerate(mol)

KekulizeException: Can't kekulize mol.  Unkekulized atoms: 3 7
```
For info : 

![image](https://user-images.githubusercontent.com/36763600/214850004-8031be9b-267f-47ad-aade-8767f076926d.png)

**Expected behavior**
Using MolVS it is able to generate the tautomers 

```
import molvs

taut = molvs.tautomer.TautomerEnumerator()

canon = taut.enumerate(mol)
```
![image](https://user-images.githubusercontent.com/36763600/214852548-b5cd39ec-8635-4792-a36f-a35a8fa88fe7.png)

**Configuration:**
 - RDKit version: 2022.09.1     
 - OS:  Ubuntu 20.04.4 LTS
 - Python version (if relevant):  3.7.12  
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge

**Comment by greglandrum** [comment] 2023-01-26 16:25
This is a duplicate of #5784, which was fixed in v2022.09.3

**Closed by greglandrum** 2023-01-26 16:25 UTC
Labels: bug
