### ISSUE TITLE
MolFileParser fails to identify a V2000 format file

### ISSUE THREAD

**Issue by MikeDenison** [rdkit/rdkit#6192] opened 2023-03-13 14:09 UTC
-----------------------------------------

**Describe the bug**
The following string is a valid counts line. It agrees with the ctfile2020 specification page43 where there are 11 numric fields of width 3 and a final text field of width 6 that contains V2000. The specification document says nothing about left or right justifcation as far as I can see.
'41 44 0  0  0  0  0  0  0  0  999V2000 '
The 'V' occurs at index 33 (indexed for 0). 
MolFileParser (line 3408) checks for a V at index 34. 
Under strict parsing the code should check the field is either "V2000 " or " V2000" or "V3000 " or " V3000". Note the spaces.
Neither is it enough to check if (tempStr.substr(34, 5) != "V2000")  since this would pass "...............xV2000".
Also under strict parsing a line of less than 36 chars is also an error. 

**To Reproduce**
Modify an SDF manually to move the V.
Note: RDKIT did not produce my input file which is why the V is not where rdkit expects it.

**Expected behavior**
No error message since file is compliant with SDF spec.

**Screenshots**
**Configuration (please complete the following information):**
 - RDKit version:  rdkit-2022.03.5
 - Are you using conda? yes

**Additional context**
I am running a remote service and have limited info about the environment but behaviour is consistent with latest git source code in 
https://github.com/rdkit/rdkit/blob/286cb213026242a78b4563b60763382df0297810/Code/GraphMol/FileParsers/MolFileParser.cpp

**Comment by greglandrum** [comment] 2023-03-14 06:01
@MikeDenison I believe that with fortran77 formatted IO (which this format is a relic of) the location of the spaces is indeed significant and that fields are right justified. So " V2000" is correct and "V2000 " incorrect just as " 99" is correct and "99 " incorrect.
If you set `strictParsing` to false, the error will be converted to a warning and you will get an output molecule since `V2000` is the default

**Comment by greglandrum** [comment] 2023-03-14 06:02
I'm closing this because I think it's not a bug. If you can find documentation that the current behavior is indeed a bug, we can certainly reopen it.

**Closed by greglandrum** 2023-03-14 06:02 UTC
Labels: not a bug
