### ISSUE TITLE
SMILE parsing error

### ISSUE THREAD

**Issue by ivannnnnnnnnn** [rdkit/rdkit#6261] opened 2023-03-31 10:57 UTC
I receive SMILE parse error when try to create molecule from smiles

Code:
`mol = Chem.MolFromSmiles("c1ccc(Sc2cccc3c2-c2nc-3nc3c4c(Sc5ccccc5)cccc4c4nc5nc(nc6c7c(Sc8ccccc8)cccc7c(n2)n6[al+]n43)-c2cccc(Sc3ccccc3)c2-5)cc1")`

Output:
`SMILES Parse Error: syntax error while parsing: c1ccc(Sc2cccc3c2-c2nc-3nc3c4c(Sc5ccccc5)cccc4c4nc5nc(nc6c7c(Sc8ccccc8)cccc7c(n2)n6[al+]n43)-c2cccc(Sc3ccccc3)c2-5)cc1`

What is wrong with this smiles?

I tried to get a molecule from these smiles on these sites and there were no errors

https://pubchem.ncbi.nlm.nih.gov//edit3/index.html
https://www.rcsb.org/chemical-sketch

**Comment by greglandrum** [comment] 2023-03-31 17:11
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.

**Closed by greglandrum** 2023-03-31 17:11 UTC
Labels: bug
