### ISSUE TITLE
Support pentavalent nitrogen as per SMILES

### ISSUE THREAD

**Issue by merkys** [rdkit/rdkit#4195] opened 2021-06-01 14:48 UTC
**Describe the bug**
Pentavalent nitrogen in SMILES is not supported (related to #358).

**To Reproduce**
```python
> from rdkit import Chem
> m = Chem.MolFromSmiles('FC1=C(F)C(SCC[NH3]Cl)=C(F)C(F)=C1S(=O)(NC)=O')
[09:35:56] Explicit valence for atom # 8 N, 5, is greater than permitted
```

**Expected behavior**
Pentavalent nitrogen seems OK according to [OpenSMILES v1.0 specification](http://opensmiles.org/opensmiles.html#orgsbst), so I would expect to get the properly constructed molecule object.

**Configuration (please complete the following information):**
 - RDKit version: 202009.5-1 (as packaged in Debian, installed via `apt-get install`)
 - OS: Debian unstable
 - Python version (if relevant): 3.9.2

**Comment by greglandrum** [comment] 2021-06-01 16:29
This is by design. The SMILES syntactically legal but the molecule itself is chemically unreasonable. If you want to read it in anyway you need to turn off sanitizer ion. There’s a lot of information out there on how to do this and what the consequences are.

**Comment by greglandrum** [comment] 2021-06-03 08:13
I'm closing this because it looks like the question is answered. Please reopen if necessary.

**Closed by greglandrum** 2021-06-03 08:13 UTC
Labels: not a bug

**Comment by merkys** [comment] 2021-06-07 09:04
Thanks for prompt response. I will look into turning off the sanitization.
