### ISSUE TITLE
rdkit.Chem.rdMolDescriptors.CalcNumRotatableBonds wrong results for acetone

### ISSUE THREAD

**Issue by jasonyz-isolabs** [rdkit/rdkit#6381] opened 2023-05-18 13:56 UTC
-----------------------------------------

If you have a question about the RDKit or aren't sure if what you're seeing is the right behavior please use the Discussions tab above (https://github.com/rdkit/rdkit/discussions) instead of posting it here.

Please help us help you: We normally need the information below in order to answer questions or understand bug reports. If you do not provide the information requested we may not be able to help you and will probably close the issue.

PLEASE DELETE THIS SECTION AFTER YOU HAVE READ IT

-----------------------------------------

**Describe the bug**

https://www.rdkit.org/docs/source/rdkit.Chem.rdMolDescriptors.html#rdkit.Chem.rdMolDescriptors.CalcNumRotatableBonds
produces 2 for acetone under strict mode, 0 under non-strict mode

**Comment by greglandrum** [comment] 2023-05-22 04:28
@jasonyz-isolabs I cannot reproduce this with the current release version of the RDKit:
```
In [11]: print(rdkit.__version__)
2023.03.1

In [12]: m = Chem.MolFromSmiles('CC(=O)C')

In [13]: rdMolDescriptors.CalcNumRotatableBonds(m,strict=rdMolDescriptors.NumRotatableBondsOptions.Strict)
Out[13]: 0

In [14]: rdMolDescriptors.CalcNumRotatableBonds(m,strict=rdMolDescriptors.NumRotatableBondsOptions.NonStrict)
Out[14]: 0
```
Given that, and the fact that you haven't provided the information requested in the issue template to allow us to reproduce problems and help, I'm closing this.

Feel free to add the requested information and reopen.

**Closed by greglandrum** 2023-05-22 04:28 UTC
Labels: bug
