### ISSUE TITLE
get atom chirality from wedge bond

### ISSUE THREAD

**Issue by averyhugebug** [rdkit/rdkit#4041] opened 2021-04-15 20:15 UTC
How can I compute the chirality of a given atom by adding a wedge bond.

I start from the following molecule 
`m = Chem.MolFromSmiles('C(C)(N)C(=[O])[OH]')`

When I try to set the bond to wedge
`m.GetBondBetweenAtoms(1, 0).SetBondDir(rdkit.Chem.BEGINWEDGE)`
then the wedge points in the wrong direction and the chirality of the atom 0 does not change (CHI_UNSPECIFIED).
even after
`Chem.rdmolops.AssignChiralTypesFromBondDirs(m)`

How can I
1. change the wedge orientation of the bond between atom 0 and 1
2. recompute the chirality of atom 0 (to that it is CHI_TETRAHEDRAL_CCW for DASH and CHI_TETRAHEDRAL_CW for WEDGE)

**Comment by stas-sl** [comment] 2021-04-16 11:36
I also wish I had better understanding how to go from bond wedges to chirality, but what I realized so far is that calling `Chem.Draw.rdDepictor.Compute2DCoords(m)` before `AssignChiralTypesFromBondDirs` helps. 

Another option is to call `AllChem.EmbedMolecule(mol)`, but in this case you'll get randomly R or S chirality.

**Comment by jasondbiggs** [comment] 2021-04-16 12:20
The connection between the bond direction (wedge/hash) and chirality has to come through the depiction.  What does it even mean to say a particular bond is wedged if it has 2D coordinates?

Without reference to a specific set of coordinates, the way to set the stereo on an atom is with the `SetChiralTag` method. This is a bit tricky in and of itself, because the 'clockwise' and 'counterclockwise' in the tag refers to the bonds coming off the atom in question, and specifically it depends on the *order* of the bonds in the bond list.  So if you have a molecule and you shuffle the bonds in the bond list, then it could have the effect of inverting the chirality of an atom.

I think it would be nice if this dependency on the ordering of the bond list.  An atom could have a field to hold the list of ligands in the same way that bonds do, with the `dp_stereoAtoms` field.

**Comment by stas-sl** [comment] 2021-04-16 12:51
@jasondbiggs thanks! I didn't realize that atom connections and bond directions are not enough, and you need 2D coordinates as well. 

![image](https://user-images.githubusercontent.com/4602302/115025991-a42e1d00-9eca-11eb-8ef3-c849467f9d67.png)

![image](https://user-images.githubusercontent.com/4602302/115026128-caec5380-9eca-11eb-8df5-91d21cbecfbd.png)

Do you know if it possible to manually assign those coordinates before `AssignChiralTypesFromBondDirs`, not using `Compute2DCoords`?

**Comment by averyhugebug** [comment] 2021-04-16 12:56
Exactly!, So what is the code to get from 
`m = Chem.MolFromSmiles('C(C)(N)C(=[O])[OH]')`
to these pictures?

**Comment by stas-sl** [comment] 2021-04-16 13:06
@averyhugebug I drew those pictures manually in editor and then moved wedged bonds to different positions to see how it affects chirality. If I moved wedged bond up - it assigned `R`, if I moved it down - it assigned `S`. So the idea is that you need coordinates set before calling `AssignChiralTypesFromBondDirs`, the question is how you set them. There could be different options: you can either ask rdkit to do it for you by calling `Compute2DCoords`, or somehow provide them manually, which is I don't know how to do yet.

**Comment by averyhugebug** [comment] 2021-04-16 13:20
I agree, I would also prefer to set them manually, al least the 2d coords for the non-H atoms.
From there, I would like to set wedge/dash bonds and `AssignChiralTypesFromBondDirs` as you suggested.

**Comment by greglandrum** [comment] 2021-04-16 14:05
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.

**Closed by greglandrum** 2021-04-16 14:05 UTC
