### ISSUE TITLE
Partial representation of aromatic compounds in SMARTS notation

### ISSUE THREAD

**Issue by okikosuke** [rdkit/rdkit#4469] opened 2021-09-02 08:02 UTC
**Describe the bug**
I want to get partial representation of aromatic compounds in SMARTS notation.

**Code**

```python
Chem.MolFromSmarts('ccO')
```

**Error**

```python
---------------------------------------------------------------------------
AtomKekulizeException                     Traceback (most recent call last)
~\Anaconda3\lib\site-packages\IPython\core\formatters.py in __call__(self, obj)
    343             method = get_real_method(obj, self.print_method)
    344             if method is not None:
--> 345                 return method()
    346             return None
    347         else:

~\Anaconda3\lib\site-packages\rdkit\Chem\Draw\IPythonConsole.py in _toPNG(mol)
    107   kekulize = kekulizeStructures
    108   return Draw._moltoimg(mol, molSize, highlightAtoms, "", returnPNG=True, kekulize=kekulize,
--> 109                         drawOptions=drawOptions)
    110 
    111 

~\Anaconda3\lib\site-packages\rdkit\Chem\Draw\__init__.py in _moltoimg(mol, sz, highlights, legend, returnPNG, drawOptions, **kwargs)
    443     bondHighlights = kwargs.get('highlightBonds', None)
    444     d2d.DrawMolecule(mc, legend=legend or "", highlightAtoms=highlights or [],
--> 445                      highlightBonds=bondHighlights or [])
    446     d2d.FinishDrawing()
    447     if returnPNG:

AtomKekulizeException: non-ring atom 0 marked aromatic

<rdkit.Chem.rdchem.Mol at 0x1a2f02ce120>
```

I think of the following as sources of error.
"cc" stands for carbon in aromatics, but does not specify an aromatic ring.

**Complement**

```python
m = Chem.MolFromSmiles('c1ccccc1O')
patt = Chem.MolFromSmarts('ccO')
m.HasSubstructMatch(patt)
```

```python
True
```

This suggests that 'ccO' is correctly recognized as a SMARTS notation.
However, I want to write 'cco' as a substructure. How can I do this?

**Configuration**

- RDKit version: 2020.09.1.0
- OS: Win10
- Python: version 3.7.10
- Are you using conda?: Yes

**Comment by ptosco** [comment] 2021-09-02 08:56
@okikosuke This works as expected in release 2021.03.1:
```
import rdkit
from rdkit import Chem

rdkit.__version__
'2021.03.1'
Chem.MolFromSmarts('ccO')
```
![image](https://user-images.githubusercontent.com/5244385/131811369-d90dbf6a-2396-4b68-844e-6dacf207b748.png)

It also works in 2020.09.3, even though the depiction is slightly different:
```
import rdkit
from rdkit import Chem

rdkit.__version__
'2020.09.3'
Chem.MolFromSmarts("ccO")
```
![image](https://user-images.githubusercontent.com/5244385/131814397-29d58c2a-64e7-474c-81b5-f6a6f9a7ba36.png)

Closing as this is not a bug in the currently released version.

**Closed by ptosco** 2021-09-02 08:56 UTC
Labels: bug

**Comment by okikosuke** [comment] 2021-09-02 13:26
@ptosco 
Thank you for your answer. How can I upgrade RDKit using conda? The environment is as follows.

- RDKit version: 2020.09.1.0
- conda 4.10.3
- python 3.7.10

I tried to run "conda update rdkit" in Anaconda Prompt, but the rdkit version is not updated.

**Comment by okikosuke** [comment] 2021-09-03 01:25
@ptosco 
I was able to get version '2021.03.1' by typing `conda install -c conda-forge rdkit` and specifying the version. Thank you very much.
