### ISSUE TITLE
RDKit can't parse non-standard smiles, but chemdraw can parse it

### ISSUE THREAD

**Issue by autodataming** [rdkit/rdkit#3179] opened 2020-05-21 02:56 UTC
**Configuration:**

- RDKit Version: 2020.03
- Operating system: linux
- Python version (if relevant): python 3.7
- Are you using conda? yes
- If you are using conda, which channel did you install the rdkit from? rdkit
- If you are not using conda: how did you install the RDKit?

**Description:**

RDKit can't parse non-standard smiles, but chemdraw can parse it.

the non-stand smiles is :
```
O=C(C)c1cc2N(CCC[N+H]3CCN(CCO)CC3)c3c(Sc2cc1)cccc3
```
the smiles could be pastd to ChemDraw but can't be parsed by rdkit.

the standard smiles is
```
O=C(c1ccc2c(N(c3ccccc3S2)CCC[NH+]4CCN(CC4)CCO)c1)C
```

```py
smi = 'O=C(C)c1cc2N(CCC[N+H]3CCN(CCO)CC3)c3c(Sc2cc1)cccc3'
Chem.MolFromSmiles(smi)
smi='O=C(C)c1cc2N(CCC[NH+]3CCN(CCO)CC3)c3c(Sc2cc1)cccc3'
Chem.MolFromSmiles(smi)
```
output:
![图片](https://user-images.githubusercontent.com/7656130/82518321-b637fc00-9b51-11ea-8614-c85b5eaae6b2.png)

**Comment by bp-kelley** [comment] 2020-05-21 15:32
This is a duplicate of this issue:

#2632

My understanding is that [N+H] is valid but uncommon, it looks like this just fell off our radar.

**Closed** 2020-05-25 00:56 UTC
Labels: duplicate
