### ISSUE TITLE
Fragments descriptors no more available in Descriptor listing

### ISSUE THREAD

**Issue by thegodone** [rdkit/rdkit#1362] opened 2017-03-09 13:23 UTC
I compile the last Head and I try an existing code that look for "fr_COO" descriptor but I cannot find it anymore.

2017.03.1.dev1
1_61
['Asphericity', 'BalabanJ', 'BertzCT', 'Chem', 'Chi0', 'Chi0n', 'Chi0v', 'Chi1', 'Chi1n', 'Chi1v', 'Chi2n', 'Chi2v', 'Chi3n', 'Chi3v', 'Chi4n', 'Chi4v', 'EState_VSA1', 'EState_VSA10', 'EState_VSA11', 'EState_VSA2', 'EState_VSA3', 'EState_VSA4', 'EState_VSA5', 'EState_VSA6', 'EState_VSA7', 'EState_VSA8', 'EState_VSA9', 'Eccentricity', 'ExactMolWt', 'FractionCSP3', 'HallKierAlpha', 'HeavyAtomCount', 'HeavyAtomMolWt', 'InertialShapeFactor', 'Ipc', 'Kappa1', 'Kappa2', 'Kappa3', 'LabuteASA', 'MaxAbsEStateIndex', 'MaxAbsPartialCharge', 'MaxEStateIndex', 'MaxPartialCharge', 'MinAbsEStateIndex', 'MinAbsPartialCharge', 'MinEStateIndex', 'MinPartialCharge', 'MolLogP', 'MolMR', 'MolWt', 'NHOHCount', 'NOCount', 'NPR1', 'NPR2', 'NumAliphaticCarbocycles', 'NumAliphaticHeterocycles', 'NumAliphaticRings', 'NumAromaticCarbocycles', 'NumAromaticHeterocycles', 'NumAromaticRings', 'NumHAcceptors', 'NumHDonors', 'NumHeteroatoms', 'NumRadicalElectrons', 'NumRotatableBonds', 'NumSaturatedCarbocycles', 'NumSaturatedHeterocycles', 'NumSaturatedRings', 'NumValenceElectrons', 'PEOE_VSA1', 'PEOE_VSA10', 'PEOE_VSA11', 'PEOE_VSA12', 'PEOE_VSA13', 'PEOE_VSA14', 'PEOE_VSA2', 'PEOE_VSA3', 'PEOE_VSA4', 'PEOE_VSA5', 'PEOE_VSA6', 'PEOE_VSA7', 'PEOE_VSA8', 'PEOE_VSA9', 'PMI1', 'PMI2', 'PMI3', 'PropertyFunctor', 'RadiusOfGyration', 'RingCount', 'SMR_VSA1', 'SMR_VSA10', 'SMR_VSA2', 'SMR_VSA3', 'SMR_VSA4', 'SMR_VSA5', 'SMR_VSA6', 'SMR_VSA7', 'SMR_VSA8', 'SMR_VSA9', 'SlogP_VSA1', 'SlogP_VSA10', 'SlogP_VSA11', 'SlogP_VSA12', 'SlogP_VSA2', 'SlogP_VSA3', 'SlogP_VSA4', 'SlogP_VSA5', 'SlogP_VSA6', 'SlogP_VSA7', 'SlogP_VSA8', 'SlogP_VSA9', 'SpherocityIndex', 'TPSA', 'VSA_EState1', 'VSA_EState10', 'VSA_EState2', 'VSA_EState3', 'VSA_EState4', 'VSA_EState5', 'VSA_EState6', 'VSA_EState7', 'VSA_EState8', 'VSA_EState9', '_ChargeDescriptors', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '_descList', '_isCallable', '_rdMolDescriptors', '_setupDescriptors', '_test', 'collections', 'descList', 'rdMolDescriptors', 'rdPartialCharges']
[('Asphericity', <function <lambda> at 0x104972410>), ('BalabanJ', <function BalabanJ at 0x103fd9488>), ('BertzCT', <function BertzCT at 0x103fd96e0>), ('Chi0', <function Chi0 at 0x103fd26e0>), ('Chi0n', <function <lambda> at 0x103fd91b8>), ('Chi0v', <function <lambda> at 0x103fd2e60>), ('Chi1', <function Chi1 at 0x103fd2758>), ('Chi1n', <function <lambda> at 0x103fd9230>), ('Chi1v', <function <lambda> at 0x103fd2ed8>), ('Chi2n', <function <lambda> at 0x103fd92a8>), ('Chi2v', <function <lambda> at 0x103fd2f50>), ('Chi3n', <function <lambda> at 0x103fd9320>), ('Chi3v', <function <lambda> at 0x103fd9050>), ('Chi4n', <function <lambda> at 0x103fd9398>), ('Chi4v', <function <lambda> at 0x103fd90c8>), ('EState_VSA1', <function EState_VSA1 at 0x104972d70>), ('EState_VSA10', <function EState_VSA10 at 0x10497c230>), ('EState_VSA11', <function EState_VSA11 at 0x10497c2a8>), ('EState_VSA2', <function EState_VSA2 at 0x104972de8>), ('EState_VSA3', <function EState_VSA3 at 0x104972e60>), ('EState_VSA4', <function EState_VSA4 at 0x104972ed8>), ('EState_VSA5', <function EState_VSA5 at 0x104972f50>), ('EState_VSA6', <function EState_VSA6 at 0x10497c050>), ('EState_VSA7', <function EState_VSA7 at 0x10497c0c8>), ('EState_VSA8', <function EState_VSA8 at 0x10497c140>), ('EState_VSA9', <function EState_VSA9 at 0x10497c1b8>), ('Eccentricity', <function <lambda> at 0x104972398>), ('ExactMolWt', <function <lambda> at 0x103fa80c8>), ('FractionCSP3', <function <lambda> at 0x1049689b0>), ('HallKierAlpha', <function <lambda> at 0x103fd2500>), ('HeavyAtomCount', <function HeavyAtomCount at 0x104968938>), ('HeavyAtomMolWt', <function <lambda> at 0x103fa8050>), ('InertialShapeFactor', <function <lambda> at 0x104972320>), ('Ipc', <function Ipc at 0x103fd2320>), ('Kappa1', <function <lambda> at 0x103fd2578>), ('Kappa2', <function <lambda> at 0x103fd25f0>), ('Kappa3', <function <lambda> at 0x103fd2668>), ('LabuteASA', <function <lambda> at 0x104968230>), ('MaxAbsEStateIndex', <function MaxAbsEStateIndex at 0x103fa8758>), ('MaxAbsPartialCharge', <function MaxAbsPartialCharge at 0x103fa8398>), ('MaxEStateIndex', <function MaxEStateIndex at 0x103fa8668>), ('MaxPartialCharge', <function MaxPartialCharge at 0x103fa82a8>), ('MinAbsEStateIndex', <function MinAbsEStateIndex at 0x103fa87d0>), ('MinAbsPartialCharge', <function MinAbsPartialCharge at 0x103fa8410>), ('MinEStateIndex', <function MinEStateIndex at 0x103fa86e0>), ('MinPartialCharge', <function MinPartialCharge at 0x103fa8320>), ('MolLogP', <function <lambda> at 0x103fd9c08>), ('MolMR', <function <lambda> at 0x103fd9c80>), ('MolWt', <function <lambda> at 0x1026e6f50>), ('NHOHCount', <function <lambda> at 0x104968848>), ('NOCount', <function <lambda> at 0x1049687d0>), ('NPR1', <function <lambda> at 0x1049721b8>), ('NPR2', <function <lambda> at 0x104972230>), ('NumAliphaticCarbocycles', <function <lambda> at 0x104968de8>), ('NumAliphaticHeterocycles', <function <lambda> at 0x104968d70>), ('NumAliphaticRings', <function <lambda> at 0x104968cf8>), ('NumAromaticCarbocycles', <function <lambda> at 0x104968b90>), ('NumAromaticHeterocycles', <function <lambda> at 0x104968b18>), ('NumAromaticRings', <function <lambda> at 0x104968a28>), ('NumHAcceptors', <function <lambda> at 0x104968500>), ('NumHDonors', <function <lambda> at 0x104968410>), ('NumHeteroatoms', <function <lambda> at 0x1049685f0>), ('NumRadicalElectrons', <function NumRadicalElectrons at 0x103fa81b8>), ('NumRotatableBonds', <function <lambda> at 0x1049686e0>), ('NumSaturatedCarbocycles', <function <lambda> at 0x104968c80>), ('NumSaturatedHeterocycles', <function <lambda> at 0x104968c08>), ('NumSaturatedRings', <function <lambda> at 0x104968aa0>), ('NumValenceElectrons', <function NumValenceElectrons at 0x103fa8140>), ('PEOE_VSA1', <function <lambda> at 0x104964aa0>), ('PEOE_VSA10', <function <lambda> at 0x104964ed8>), ('PEOE_VSA11', <function <lambda> at 0x104964f50>), ('PEOE_VSA12', <function <lambda> at 0x104968050>), ('PEOE_VSA13', <function <lambda> at 0x1049680c8>), ('PEOE_VSA14', <function <lambda> at 0x104968140>), ('PEOE_VSA2', <function <lambda> at 0x104964b18>), ('PEOE_VSA3', <function <lambda> at 0x104964b90>), ('PEOE_VSA4', <function <lambda> at 0x104964c08>), ('PEOE_VSA5', <function <lambda> at 0x104964c80>), ('PEOE_VSA6', <function <lambda> at 0x104964cf8>), ('PEOE_VSA7', <function <lambda> at 0x104964d70>), ('PEOE_VSA8', <function <lambda> at 0x104964de8>), ('PEOE_VSA9', <function <lambda> at 0x104964e60>), ('PMI1', <function <lambda> at 0x104972050>), ('PMI2', <function <lambda> at 0x1049720c8>), ('PMI3', <function <lambda> at 0x104972140>), ('RadiusOfGyration', <function <lambda> at 0x1049722a8>), ('RingCount', <function <lambda> at 0x1049688c0>), ('SMR_VSA1', <function <lambda> at 0x104964050>), ('SMR_VSA10', <function <lambda> at 0x104964488>), ('SMR_VSA2', <function <lambda> at 0x1049640c8>), ('SMR_VSA3', <function <lambda> at 0x104964140>), ('SMR_VSA4', <function <lambda> at 0x1049641b8>), ('SMR_VSA5', <function <lambda> at 0x104964230>), ('SMR_VSA6', <function <lambda> at 0x1049642a8>), ('SMR_VSA7', <function <lambda> at 0x104964320>), ('SMR_VSA8', <function <lambda> at 0x104964398>), ('SMR_VSA9', <function <lambda> at 0x104964410>), ('SlogP_VSA1', <function <lambda> at 0x104964500>), ('SlogP_VSA10', <function <lambda> at 0x104964938>), ('SlogP_VSA11', <function <lambda> at 0x1049649b0>), ('SlogP_VSA12', <function <lambda> at 0x104964a28>), ('SlogP_VSA2', <function <lambda> at 0x104964578>), ('SlogP_VSA3', <function <lambda> at 0x1049645f0>), ('SlogP_VSA4', <function <lambda> at 0x104964668>), ('SlogP_VSA5', <function <lambda> at 0x1049646e0>), ('SlogP_VSA6', <function <lambda> at 0x104964758>), ('SlogP_VSA7', <function <lambda> at 0x1049647d0>), ('SlogP_VSA8', <function <lambda> at 0x104964848>), ('SlogP_VSA9', <function <lambda> at 0x1049648c0>), ('SpherocityIndex', <function <lambda> at 0x104972488>), ('TPSA', <function <lambda> at 0x104968398>), ('VSA_EState1', <function VSA_EState_bin at 0x1049728c0>), ('VSA_EState10', <function VSA_EState_bin at 0x104972cf8>), ('VSA_EState2', <function VSA_EState_bin at 0x104972938>), ('VSA_EState3', <function VSA_EState_bin at 0x1049729b0>), ('VSA_EState4', <function VSA_EState_bin at 0x104972a28>), ('VSA_EState5', <function VSA_EState_bin at 0x104972aa0>), ('VSA_EState6', <function VSA_EState_bin at 0x104972b18>), ('VSA_EState7', <function VSA_EState_bin at 0x104972b90>), ('VSA_EState8', <function VSA_EState_bin at 0x104972c08>), ('VSA_EState9', <function VSA_EState_bin at 0x104972c80>)]

any idea why this change ?

**Comment by gedeck** [comment] 2017-03-09 14:46
I have a look at it.

**Comment by gedeck** [comment] 2017-03-09 15:01
I cannot reproduce your issue. On the latest `rdkit/rdkit master`, the following test function passes:
```
  def testGithub1362(self):
    descriptors = [d[0] for d in Descriptors._descList]
    self.assertIn('fr_COO', descriptors)

    m = Chem.MolFromSmiles('CCC(=O)O')
    self.assertEqual(Descriptors.fr_COO(m), 1)
``` 
The fragment descriptors are created from a pattern file in `rdkit.Chem.Fragments`:
```
defaultPatternFileName = os.path.join(RDConfig.RDDataDir, 'FragmentDescriptors.csv'
```
Can you check that this file exists and that the variable `defaultPatternFileName` is correct?

**Comment by thegodone** [comment] 2017-03-10 09:22
Dear Peter,

I have a wrong RDConfig.RDDataDir it still map on a brew installation.

I will let you know if I can fix the bug on my installation.

BR,

Guillaume

2017-03-09 16:01 GMT+01:00 gedeck <notifications@github.com>:

**Comment by greglandrum** [comment] 2017-03-22 07:06
@thegodone : is it ok to close this?

**Closed** 2024-08-13 13:35 UTC
