### ISSUE TITLE
How to check if two different molecules represent the same molecule?

### ISSUE THREAD

**Issue by DaShenZi721** [rdkit/rdkit#4529] opened 2021-09-17 00:49 UTC
In the dataset ‘USPTO’，we can get some product smiles from reaction like:
`[NH2:1][CH2:2][CH2:3][CH2:4][CH2:5][C@@H:6]([C:7]([O:8][CH3:9])=[O:10])[NH:11][C:12](=[O:13])[NH:14][c:15]1[cH:16][c:17]([O:18][CH3:19])[cH:20][c:21]([C:22]([CH3:23])([CH3:24])[CH3:25])[c:26]1[OH:27]`

And its CanonSmiles is 
`COC(=O)[C@H](CCCCN)NC(=O)Nc1cc(OC)cc(C(C)(C)C)c1O`

I try to use `Chem.CanonSmiles()` to solve it, but it doesn't work.

**Comment by greglandrum** [comment] 2021-09-17 03:04
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.

**Closed by greglandrum** 2021-09-17 03:04 UTC
Labels: enhancement
