### ISSUE TITLE
Logp calculation error

### ISSUE THREAD

**Issue by Crispae** [rdkit/rdkit#3721] opened 2021-01-12 17:42 UTC
I am trying to calculate Logp value using PyBiomed library which uses  Rdkit as depenedency, while calculating it throw a filenotfound error

 **File "C:\Users\XXX\.conda\envs\Rdkit-env\lib\site-packages\rdkit\Chem\Crippen.py", line 137, in _pyMolLogP
    _patternOrder, _smartsPatterns = _ReadPatts(defaultPatternFileName)
  File "C:\Users\XXX\.conda\envs\Rdkit-env\lib\site-packages\rdkit\Chem\Crippen.py", line 40, in _ReadPatts
    with open(fileName, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\RDKit\\Data\\Crippen.txt'**

**Comment by ptosco** [comment] 2021-01-12 17:53
@Crispae It looks like the environment variable `RDBASE` is set to `C:\RDKit` but your RDKit installation does not live there.
Most likely the `Crippen.txt` file is located here on your system: `C:\Users\XXX.conda\envs\Rdkit-env\share\RDKit\Data\Crippen.txt`.
Check if the file is indeed in that path, and if so set `RDBASE` to the correct location, i.e. `C:\Users\XXX.conda\envs\Rdkit-env\share\RDKit`.
The LogP calculation should then succeed.
Closing as this is not caused by an RDKit bug but by an incorrect configuration on your system.

**Closed by ptosco** 2021-01-12 17:53 UTC
Labels: bug

**Comment by Crispae** [comment] 2021-01-12 18:16
After changing the environment variable i am still facing the issue , as currently  i am working in conda environment ,is it due to conda or anything else?
