### ISSUE TITLE
How to separate the mixture of diastereoisomers (labeled with "AND") from enantiopure isomers (labeled with "OR") in RDKit

### ISSUE THREAD

**Issue by Emily23King** [rdkit/rdkit#6805] opened 2023-10-16 09:25 UTC
I am processing hundreds of molecules saved as Mol V3000 format. I plan to separate the mixture of diastereoisomers (labeled with "AND") from enantiopure isomers (labeled with "OR") in RDKit. Could anyone give me a hint? 

Thank you very much in advance! 
@greglandrum

**Comment by bp-kelley** [comment] 2023-10-16 12:05
One way is to use GetStereoisomerCount:

```
from rdkit.Chem import EnumerateStereoisomers
num_stereo = EnumerateStereoisomers.GetStereoisomerCount(m)
```

To see how it retrieves the AND,OR markings, you can look at the source
code here:

https://github.com/rdkit/rdkit/blob/568b9db0cb68043d629088cb02defb4a9011ad1f/rdkit/Chem/EnumerateStereoisomers.py#L81

**Comment by greglandrum** [comment] 2023-10-30 05:39
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.

**Closed by greglandrum** 2023-10-30 05:39 UTC
