### ISSUE TITLE
Error with rdMolStandardize - KekulizeException: Can't kekulize mol.  

### ISSUE THREAD

**Issue by Limmiche** [rdkit/rdkit#5965] opened 2023-01-12 11:19 UTC
Hello,

I get an `KekulizeException` error using `rdMolStandardize` for some molecules.

```markdown
KekulizeException                         Traceback (most recent call last)
Cell In [24], line 1
----> 1 rdMolStandardize.TautomerEnumerator().Enumerate(molecule)[0]

KekulizeException: Can't kekulize mol.  Unkekulized atoms: 3 7

```
Here's code to reproduce the issue:

```markdown
from rdkit import Chem
from rdkit.Chem.MolStandardize import rdMolStandardize


smiles="Cc1nc2n(c(=O)c1CCN1CCC(c3noc4cc(F)ccc34)CC1)CCCC2"
molecule=Chem.MolFromSmiles(smiles)

rdMolStandardize.TautomerEnumerator().Enumerate(molecule)[0]

```

Configuration: 
 - RDKit version: 2022.09.1
 - OS: macOS 11.6 (20G165)

**Comment by greglandrum** [comment] 2023-01-19 05:54
I believe that this is a duplicate of #5784, which was fixed for the 2022.09.3 release.

**Closed by greglandrum** 2023-01-19 05:54 UTC
Labels: bug, duplicate
