### ISSUE TITLE
RDKitJS RuntimeError: Aborted(OOM)  abortOnCannotGrowMemory

### ISSUE THREAD

**Issue by PigUnderRoof** [rdkit/rdkit#5321] opened 2022-05-23 08:09 UTC
I am building an interactive page with RDKitJS and React - dynamically plot molecules. When I switch really fast, the app would crash. I think it is related to how .wam file is built.

![image](https://user-images.githubusercontent.com/24292200/169773388-b0d6e744-d7e3-4886-be51-4aa0ab501c88.png)

**Comment by ptosco** [comment] 2022-05-23 08:45
@PigUnderRoof This is almost certainly not a bug.
Whenever you instantiate a `JSMol`, you must explicitly call `delete()` when you are done with it, e.g.:
```
const mol = RDKitModule.get_mol('CCC');
[...]
mol.delete();
```
The garbage collector will _not_ automatically free the memory associated to object created by the WASM library, so you will keep leaking memory until you get an OOM.
I am closing this - feel free to reopen if needed.

**Closed by ptosco** 2022-05-23 08:45 UTC
Labels: bug

**Comment by PigUnderRoof** [comment] 2022-05-23 23:50
My bad, thank you very much!
