### ISSUE TITLE
Highlighting Specific Atoms

### ISSUE THREAD

**Issue by KGrewal1** [rdkit/rdkit#5667] opened 2022-10-19 21:31 UTC
Is it possible to highlight specific atoms by number and specify the color of the hihglight? The code given in the cookbook appears outdated and results in NoneType:
`from rdkit.Chem.Draw import rdMolDraw2D`

`smi = 'c1cc(F)ccc1Cl'`

`mol = Chem.MolFromSmiles(smi)`

`patt = Chem.MolFromSmarts('ClccccF')`

`hit_ats = list(mol.GetSubstructMatch(patt))`

`hit_bonds = []`

`for bond in patt.GetBonds():`

   `aid1 = hit_ats[bond.GetBeginAtomIdx()]`

   `aid2 = hit_ats[bond.GetEndAtomIdx()]`

`   hit_bonds.append(mol.GetBondBetweenAtoms(aid1,aid2).GetIdx())`

`d = rdMolDraw2D.MolDraw2DCairo(500, 500) # or MolDraw2DCairo to get PNGs`

`rdMolDraw2D.PrepareAndDrawMolecule(d, mol, highlightAtoms=hit_ats,`

                                   `highlightBonds=hit_bonds)`

**Comment by greglandrum** [comment] 2022-10-20 02:41
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.

**Closed by greglandrum** 2022-10-20 02:41 UTC
Labels: bug
