### ISSUE TITLE
How to correct the smile structure aromaticity?

### ISSUE THREAD

**Issue by ankit1-iitbhu** [rdkit/rdkit#3827] opened 2021-02-19 08:32 UTC
This my smile structure 'C1(=[C][C]=C([C]=[C]1)[C]N1[C][C][C][C][C]1)C1=[N]=C2C(=[C][C]=[C][C]2)O1' and when I a calculating the molecular descriptors the following error ocurs for Descriptors.BalabanJ(m) : 

ArgumentError: Python argument types in
    rdkit.Chem.rdmolops.GetDistanceMatrix(NoneType)
did not match C++ signature:
    GetDistanceMatrix(class RDKit::ROMol {lvalue} mol, bool useBO=False, bool useAtomWts=False, bool force=False, char const * __ptr64 prefix='')

When I have checked my smile by drawing on chem draw I observed the incorrect placement of aromatic bonds:

![untitled](https://user-images.githubusercontent.com/37747800/108478809-f849c600-72ba-11eb-93e9-ef6b9cc06c98.jpg)

Kindly help me in this matter? I am using pybel in jupyter notebook.

**Comment by greglandrum** [comment] 2021-02-22 05:09
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.

**Closed by greglandrum** 2021-02-22 05:09 UTC
Labels: bug
