### ISSUE TITLE
Build conda packages via CI

### ISSUE THREAD

**Issue by mwojcikowski** [rdkit/rdkit#1127] opened 2016-10-28 05:28 UTC
As in title. That way we can get consistent and timely builds

I can be self-assign to this, since I've done similar thing for OB lately. What do you think?

**Comment by greglandrum** [comment] 2016-10-28 07:29
In principle I think this is a great idea, but I have some questions/concerns that come from ignorance:
- Do the builds produced by this become the default that will be installed by conda? (I think this would be "unfortunate")
- Is there some way to also automatically cleanup old versions on the anaconda servers?

It's also important to note that this will only do 64bit linux builds at the moment, no 32bit linux, mac, or windows.

**Comment by mwojcikowski** [comment] 2016-10-28 07:42
Re 1. The idea is to have a separate repo for conda recipes not to pollute the CI on main repo. That way you manually increment the package version pointing to a git tag. Either way you build only for git tags, which is one build per "release". It's possible to build every commit from master and put it in a "devel" (or whatever) label in conda, which would require user to point to that label (which is not the default one).

Re 2. There is really no need. You collect the tagged versions as you would without CI. I don't know any way to clean the packages in bulk, but in general you can force anaconda to overwrite same versions of a package, so I think you have **one** devel package which gets overwritten on every commit.

I'm not convinced that the devel package will be of use for anyone, though it's still possible to have and may ba a fast way of delivering fixes to users.

**Comment by mwojcikowski** [comment] 2016-10-28 07:47
Considering the target platforms:

- Linux is built on Travis in docker containers (I ussualy use the Conda Forge one) and I think 32 and 64bits are both possible
- Mac is also built on Travis
- Windows is built on Appveyor using both 32 and 64bits

All of those are done for a range of Python version, I think going for 2.7, 3.4 and 3.5 is enough.

**Comment by bp-kelley** [comment] 2016-10-30 18:24
I submitted the travis osx build matrix a while ago, I can resurrect this.

I agree that these shouldn't become the "default" builds, but we could at least make these builds generally available for testing.  I'm looking for some monetary support for making full  windows builds on AppVeyor that perhaps we could donate to the cause.

**Comment by mwojcikowski** [comment] 2016-10-30 19:02
I must apologise for a bit of ignorance as I didn't notice the rdkit/conda-rdkit repo, though I created this issue just before the UGMs Workshops...

I would much more prefer to have CI builds as default, but you're pulling the strings and ultimately it's your decision. I can do them on my fork and we can look at their behavior through the next release, and then you could decide.

The windows builds are quite easy [see [here](https://github.com/openbabel/conda-openbabel/blob/master/appveyor.yml)] vs the manual ones, since Appveyor has all the dependencies in place (especially MSVC). Same with OSX on travis. The most tricky one is running Docker on Travis, but it's widely used and has been deployed with much success (conda-forge, bioconda, etc.).

**Closed** 2021-06-07 07:25 UTC
