### ISSUE TITLE
DrawMorganBits using multiple molecules

### ISSUE THREAD

**Issue by Laurianne50** [rdkit/rdkit#4684] opened 2021-11-10 16:04 UTC
Hi,

I am trying to draw specific Morgan Fingerprints Bits considering several molecules. The bits are not shared by all the molecules in my set. Thus when I draw them, they are not aligned because they are drawn considering the position in space they had in the molecules. 

I'm using AllChem.GetMorganFingerprintAsBitVect and Draw.DrawMorganBits.

Here is an example snapshot of the resulting figure: ![image](https://user-images.githubusercontent.com/54038643/141146407-27f8ec95-1183-4418-a6e9-82b71313ae60.png)

Is there a way to align the bits images and unify their sizes?

My configuration :
 - RDKit version: 2021.03.5
 - OS: Linux
 - Python version: 3.8.12
 - I'm using conda
 - rdkit was installed using conda-forge

Many thanks!

**Comment by greglandrum** [comment] 2021-11-11 05:16
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.

**Closed by greglandrum** 2021-11-11 05:16 UTC
Labels: bug
