### ISSUE TITLE
NameError: global name 'drawingOptions' is not defined

### ISSUE THREAD

**Issue by yccai** [rdkit/rdkit#1394] opened 2017-04-06 02:38 UTC
When I run my code as followed, an error is thrown.
'''
from rdkit import Chem
from rdkit.Chem import Draw
import matplotlib.pyplot as plt

smi = "C1CC2=C3C(=CC=C2)C(=CN3C1)[C@H]4[C@@H](C(=O)NC4=O)C5=CNC6=CC=CC=C65"
mol = Chem.MolFromSmiles(smi)
Draw.MolToMPL(mol,size=(500, 500), fitImage=True)
plt.show()
'''
But if I set the option "fitImage" as False, it works.
What is the solution? Help!

**Comment by gedeck** [comment] 2017-04-06 06:21
I cannot reproduce your error. Can you report what you see? It would also be useful if you give information about your rdkit version and operating system.
```
import rdkit
rdkit.__version__
```

The code that is shown above doesn't work as is. The variable `new_mol` is not defined and Github messes up the SMILES string. I assume the following is what you meant:
```
from rdkit import Chem
from rdkit.Chem import Draw
import matplotlib.pyplot as plt

smi = "C1CC2=C3C(=CC=C2)C(=CN3C1)[C@H]4[C@@H](C(=O)NC4=O)C5=CNC6=CC=CC=C65"
mol = Chem.MolFromSmiles(smi)
Draw.MolToMPL(mol, size=(500, 500), fitImage=True)
plt.show()
```
This works for me with `fitImage=True` or `False`.

**Comment by yccai** [comment] 2017-04-06 06:27
Thanks you!
This is the whole error below:
`Traceback (most recent call last):
  File "C:\Users\yccai\Desktop\try.py", line 7, in <module>
    Draw.MolToMPL(mol,size=(500, 500), fitImage=True)
  File "D:\Python27\Lib\site-packages\RDKit_2016_03_1\rdkit\Chem\Draw\__init__.py", line 233, in MolToMPL
    drawingOptions.dotsPerAngstrom = int(min(size) / 10)
NameError: global name 'drawingOptions' is not defined`

**Comment by gedeck** [comment] 2017-04-06 06:34
I can see that you run a rather old version of RDkit 2016.3. The part of the code that causes the problem is:
```
  if options is None:
    options = DrawingOptions()
    options.bgColor=None
  if fitImage:
      drawingOptions.dotsPerAngstrom = int(min(size) / 10)
  options.wedgeDashedBonds=wedgeBonds
  drawer = MolDrawing(canvas=canvas, drawingOptions=options)
```
There is indeed a bug in this version which was fixed in RDkit 2016.9. If you cannot update to a newer version, make the following change in your code.
```
  if fitImage:
      options.dotsPerAngstrom = int(min(size) / 10)
```
That should fix it.

**Comment by gedeck** [comment] 2017-04-06 07:04
While this fixes the error, I suggest you still look into updating your RDkit version.

**Comment by yccai** [comment] 2017-04-06 07:48
Thank you very much.  I fix it as what you say. 
OK. I am going to update my RDkit version.

**Comment by gedeck** [comment] 2017-04-06 08:06
If the change fixes the issue, then please close it.

**Closed** 2017-04-07 02:17 UTC
