### ISSUE TITLE
Building fragment db and save it in pkl for later use.

### ISSUE THREAD

**Issue by yuzie0314** [rdkit/rdkit#6176] opened 2023-03-07 02:09 UTC
Dear Authors,
I am a newcomer to use your tool, and may need some suggestions from all of you.
### Description my project, which has two main parts:

- Building db:

I want to use rdkit to generate a nonredundant fragment catalogue as well as fingerprints for each compounds based on these fragments from our inhouse small molecule compounds in 3-D.
Base on these fragments, we will split each molecule into fragments.

- Query molecule mapping:

A query mol writen in 3-D will first spilit into fragment based on our prepared fragment catalogue, also be split into fragments.
Each fragment will align to the mapped fragment in the catalogue.

- The following is the snippet codes from my understanding with your tools. (I mainly used **FragmentCatalog**)

```
def build_sdf_catalogue(self):
        self.logger.info(f"building sdf catalogue inside {self.outdir}")
        sdf_list = glob.glob(
            os.path.join(self.sdf_folder_to_glob, "*.sdf")
        ) 
        
        suppl_list = [Chem.SDMolSupplier(f) for f in sdf_list]
        for suppl in suppl_list:
            for x in suppl:
                self.mols.append(x)

        fName = os.path.join( RDConfig.RDDataDir, 'FunctionalGroups.txt')
        params = FragmentCatalog.FragCatParams( 1, 6, fName )
        self.fcat = FragmentCatalog.FragCatalog(params)
        fcgen = FragmentCatalog.FragCatGenerator()
        for mol in self.mols:
            fcgen.AddFragsFromMol(mol, self.fcat)
        
        with open(f"{self.outdir}/{self.sdf_folder_to_glob}_catalog.pkl", "wb") as f:
            pickle.dump(self.fcat, f)
```

1. Because my compounds datasets are a little big (> 30000, namely we can expect my fragments db will be a little big), if make use of Chem.SDMolSupplier(f) as input, which is a little slow, so can I use multithreadedsdmolsupplier() instead?
2. another thing is that, each mol is stored in a sdf file, then how to load them and merge them to a suppl object, or maybe we don't need to? I can only save these mol into a big list **self.mols.append(x)**, any suggestions?
3. Based on my understanding, the **FragmentCatalog.FragCatParams( 1, 6, fName )** seems to only have four params to define, am I wrong? but I still want to define my hevay atom number something like this, how to do?
4. what is the output from  FragmentCatalog.FragCatalog(params) when we use FragmentCatalog.FragCatGenerator() to generate fragments? Initially, I previously expected a dictionary: **Dict[ fragments_smile_string , List[ molecule_id ] ]** which is what I need, but when I glanced over your documents, I don't know how to make use of this catalogue object.
5. how do I store the catalogue? I first thought that we should pickle all of them, but still don't have any idea.

**Comment by greglandrum** [comment] 2023-03-07 05:34
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.

**Closed by greglandrum** 2023-03-07 05:34 UTC
