### ISSUE TITLE
Draw.DrawMorganBit sometimes only works for SVGs

### ISSUE THREAD

**Issue by JanoschMenke** [rdkit/rdkit#4057] opened 2021-04-19 12:27 UTC
So the `Draw.DrawMorganBit` produces an error when plotting specific bits.
The error is  `AtomKekulizeException: non-ring atom 1 marked aromatic`
This is only happens when `useSVG=False`

```
mol = Chem.MolToSmiles("Clc1ccccc1C(c1ccccc1)(c1ccccc1)n1ccnc1)
bi ={}
fp = AllChem.GetMorganFingerprintAsBitVect(mol_ll[count], radius=2, bitInfo=bi)
Draw.DrawMorganBit(mol_ll[count], most_important_bits[count], bi)
```
The RDKit version that I am using is `2020.09.1`

**Comment by greglandrum** [comment] 2021-04-19 12:43
duplicate of: #3796

**Closed by greglandrum** 2021-04-19 12:43 UTC
Labels: bug
