### ISSUE TITLE
R-group RXN V2000 reaction handling

### ISSUE THREAD

**Issue by goraj** [rdkit/rdkit#2527] opened 2019-07-03 18:44 UTC
Hello,

while working with MarvinJS RXN exports I was surprised by how RDKit handles R groups.
I prepared a few simple amide coupling examples to illustate:

`Using R-group with atom mapping`
<img width="323" alt="rxn_r_map4" src="https://user-images.githubusercontent.com/28098212/60616337-353c0e80-9d9f-11e9-8350-b047ec284883.png">

`R group with no mapping or atom label`
<img width="335" alt="rxn_r_no_map" src="https://user-images.githubusercontent.com/28098212/60616455-84823f00-9d9f-11e9-9b13-4d9cd5a4a467.png">

`R group with atom label and atom mapping`
<img width="335" alt="rxn_r4_map4" src="https://user-images.githubusercontent.com/28098212/60616471-8ba94d00-9d9f-11e9-917a-ccd3d733a0aa.png">

`R group with atom label`
<img width="336" alt="rxn_r4" src="https://user-images.githubusercontent.com/28098212/60616459-877d2f80-9d9f-11e9-8b73-5a6b7c4f2de1.png">

Surprisingly only the RXN export with `R group with atom label and atom mapping` work correctly and gives the expected products. I have attached code to illustrate this behavior. I am not quite sure if this is actually the correct expected behavior or a bug?

Please note that atom mapping information is lost on re-importing RXN files (that contain atom labels and atom mappings) to MarvinJS.

Best,
Jacob
```
import rdkit
import os
import numpy as np
from pathlib import Path
from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit.Chem.rdchem import Mol
from dataclasses import dataclass, fields

from rdkit.Chem.rdmolops import FastFindRings
from rdkit.Chem.rdChemReactions import PreprocessReaction
from rdkit.Chem.rdChemReactions import ReactionFromRxnBlock, ReactionFromRxnFile, ReactionFromSmarts, ReactionToSmarts
from rdkit.Chem.Draw import IPythonConsole
from rdkit.Chem.Draw.MolDrawing import MolDrawing, DrawingOptions

def create_reaction_from_rxn(rxn_content):
    return ReactionFromRxnBlock(rxn_content)

def create_reaction_from_rxn_file(reaction_path):
    rxn_content = open(reaction_path).read()
    return create_reaction_from_rxn(rxn_content)


def create_reaction_from_smarts_file(reaction_path):
    reaction_pattern = open(reaction_path).read()
    return ReactionFromSmarts(reaction_pattern)

def render_smiles(smiles):
    display(Chem.MolFromSmiles(smiles))
    
def render(molobj):
    display(molobj)
    
def mol_to_smiles(molobj):
    return Chem.MolToSmiles(molobj, isomericSmiles=True)

def smiles_to_mol(smiles):
    return Chem.MolFromSmiles(smiles)

rxn_r_map4 = """$RXN

      Mrv1902  070320191331

  2  1
$MOL

  Mrv1902 07031913312D          

  3  2  0  0  0  0            999 V2000
   -4.5670   -0.2063    0.0000 C   0  0  0  0  0  0  0  0  0  2  0  0
   -5.2815    0.2062    0.0000 O   0  0  0  0  0  0  0  0  0  1  0  0
   -3.8525    0.2063    0.0000 O   0  0  0  2  0  0  0  0  0  0  0  0
  1  2  2  0  0  0  0
  1  3  1  0  0  0  0
M  MRV SMA   3 [#8H1]
M  END
$MOL

  Mrv1902 07031913312D          

  2  1  0  0  0  0            999 V2000
   -1.1418    0.0687    0.0000 N   0  0  0  0  0  0  0  0  0  3  0  0
   -1.9668    0.0687    0.0000 R   0  0  0  0  0  0  0  0  0  4  0  0
  1  2  1  0  0  0  0
M  END
$MOL

  Mrv1902 07031913312D          

  4  3  0  0  0  0            999 V2000
    4.4565   -0.3572    0.0000 C   0  0  0  0  0  0  0  0  0  2  0  0
    5.2815   -0.3572    0.0000 O   0  0  0  0  0  0  0  0  0  1  0  0
    4.0439    0.3572    0.0000 N   0  0  0  0  0  0  0  0  0  3  0  0
    3.2190    0.3572    0.0000 R   0  0  0  0  0  0  0  0  0  4  0  0
  1  2  2  0  0  0  0
  1  3  1  0  0  0  0
  3  4  1  0  0  0  0
M  END
"""

rxn_r_no_map = """$RXN

      Mrv1902  070320191336

  2  1
$MOL

  Mrv1902 07031913362D          

  3  2  0  0  0  0            999 V2000
   -4.5670   -0.2063    0.0000 C   0  0  0  0  0  0  0  0  0  2  0  0
   -5.2815    0.2062    0.0000 O   0  0  0  0  0  0  0  0  0  1  0  0
   -3.8525    0.2063    0.0000 O   0  0  0  2  0  0  0  0  0  0  0  0
  1  2  2  0  0  0  0
  1  3  1  0  0  0  0
M  MRV SMA   3 [#8H1]
M  END
$MOL

  Mrv1902 07031913362D          

  2  1  0  0  0  0            999 V2000
   -1.1418    0.0687    0.0000 N   0  0  0  0  0  0  0  0  0  3  0  0
   -1.9668    0.0687    0.0000 R   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
M  END
$MOL

  Mrv1902 07031913362D          

  4  3  0  0  0  0            999 V2000
    4.4565   -0.3572    0.0000 C   0  0  0  0  0  0  0  0  0  2  0  0
    5.2815   -0.3572    0.0000 O   0  0  0  0  0  0  0  0  0  1  0  0
    4.0439    0.3572    0.0000 N   0  0  0  0  0  0  0  0  0  3  0  0
    3.2190    0.3572    0.0000 R   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  2  0  0  0  0
  1  3  1  0  0  0  0
  3  4  1  0  0  0  0
M  END
"""

rxn_r4_map4 = """$RXN

      Mrv1902  070320191339

  2  1
$MOL

  Mrv1902 07031913392D          

  3  2  0  0  0  0            999 V2000
   -4.5670   -0.2063    0.0000 C   0  0  0  0  0  0  0  0  0  2  0  0
   -5.2815    0.2062    0.0000 O   0  0  0  0  0  0  0  0  0  1  0  0
   -3.8525    0.2063    0.0000 O   0  0  0  2  0  0  0  0  0  0  0  0
  1  2  2  0  0  0  0
  1  3  1  0  0  0  0
M  MRV SMA   3 [#8H1]
M  END
$MOL

  Mrv1902 07031913392D          

  2  1  0  0  0  0            999 V2000
   -1.1418    0.0687    0.0000 N   0  0  0  0  0  0  0  0  0  3  0  0
   -1.9668    0.0687    0.0000 R#  0  0  0  0  0  0  0  0  0  4  0  0
  1  2  1  0  0  0  0
M  RGP  1   2   4
M  END
$MOL

  Mrv1902 07031913392D          

  4  3  0  0  0  0            999 V2000
    4.4565   -0.3572    0.0000 C   0  0  0  0  0  0  0  0  0  2  0  0
    5.2815   -0.3572    0.0000 O   0  0  0  0  0  0  0  0  0  1  0  0
    4.0439    0.3572    0.0000 N   0  0  0  0  0  0  0  0  0  3  0  0
    3.2190    0.3572    0.0000 R#  0  0  0  0  0  0  0  0  0  4  0  0
  1  2  2  0  0  0  0
  1  3  1  0  0  0  0
  3  4  1  0  0  0  0
M  RGP  1   4   4
M  END
"""

rxn_r4 = """$RXN

      Mrv1902  070320191340

  2  1
$MOL

  Mrv1902 07031913402D          

  3  2  0  0  0  0            999 V2000
   -4.5670   -0.2063    0.0000 C   0  0  0  0  0  0  0  0  0  2  0  0
   -5.2815    0.2062    0.0000 O   0  0  0  0  0  0  0  0  0  1  0  0
   -3.8525    0.2063    0.0000 O   0  0  0  2  0  0  0  0  0  0  0  0
  1  2  2  0  0  0  0
  1  3  1  0  0  0  0
M  MRV SMA   3 [#8H1]
M  END
$MOL

  Mrv1902 07031913402D          

  2  1  0  0  0  0            999 V2000
   -1.1418    0.0687    0.0000 N   0  0  0  0  0  0  0  0  0  3  0  0
   -1.9668    0.0687    0.0000 R#  0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
M  RGP  1   2   4
M  END
$MOL

  Mrv1902 07031913402D          

  4  3  0  0  0  0            999 V2000
    4.4565   -0.3572    0.0000 C   0  0  0  0  0  0  0  0  0  2  0  0
    5.2815   -0.3572    0.0000 O   0  0  0  0  0  0  0  0  0  1  0  0
    4.0439    0.3572    0.0000 N   0  0  0  0  0  0  0  0  0  3  0  0
    3.2190    0.3572    0.0000 R#  0  0  0  0  0  0  0  0  0  0  0  0
  1  2  2  0  0  0  0
  1  3  1  0  0  0  0
  3  4  1  0  0  0  0
M  RGP  1   4   4
M  END
"""

aminoacetamide_smiles = 'NCC(N)=O'
aminoacetamide_molobj = smiles_to_mol(carboxylic_acid_smiles)

cbz_2_hydroxy_proline = 'C1C(CN(C1C(=O)O)C(=O)OCC2=CC=CC=C2)O'
cbz_2_hydroxy_proline_molobj = smiles_to_mol(cbz_2_hydroxy_proline)

render(carboxylic_acid_molobj)
render(cbz_2_hydroxy_proline_molobj)

args = (cbz_2_hydroxy_proline_molobj, aminoacetamide_molobj)

rxn_reactions = {
    'rxn_r_map4': rxn_r_map4,
    'rxn_r_no_map': rxn_r_no_map, 
    'rxn_r4_map4': rxn_r4_map4,
    'rxn_r4': rxn_r4
}


for rxn_name, rxn_content in rxn_reactions.items():
    reaction = create_reaction_from_rxn(rxn_content)
    
    reaction.Initialize()
    n_warnings, n_errors, n_reactants, n_products, labels = PreprocessReaction(reaction)
    if n_errors != 0:
        print(f'reaction initialization failed: {rxn_name}')
        continue
        
        
    product = reaction.RunReactants(args)
    
    print(f'reaction: {rxn_name}')
    render(reaction)
    if len(product):
        for molobj in np.ravel(product):
            render(molobj)
```

**Comment by bp-kelley** [comment] 2019-07-03 19:00
Out of curiosity, could you try SanitizeRxn on these examples?  There are a
plethora of different reaction types in the wild and we standardize on the
MDL definition.

In fact, this should really always be done unless you are using Smarts
based reactions as kekule structures are not aromatized without this.

Cheers,
 Brian

**Comment by bp-kelley** [comment] 2019-07-03 19:07
This fixes #2 (AllChem.SanitizeRxn)

 #1 is odd, but I won't get a chance to look at it properly until this
weekend.

**Comment by goraj** [comment] 2019-07-03 19:07
Hey Brian,

This fixed the issue for every reaction except the one without any R mapping/atom label.
```
    reaction = create_reaction_from_rxn(rxn_content)
    SanitizeRxn(reaction)
    reaction.Initialize()
    
    n_warnings, n_errors, n_reactants, n_products, labels = PreprocessReaction(reaction)
```
Thanks!

**Comment by greglandrum** [comment] 2019-07-04 04:18
Here's what's going on for the case without any R-mapping/atom labels:
When the RDKit encounters an `R` as an atomic symbol in a Mol block it creates a query atom that matches dummy atoms (i.e. a query for atomic number=0). This, of course, doesn't match anything in your reactants. 

Since `R` isn't described in the CTAB spec, but it does appear frequently in mol/rxn files, I just made up a behavior for it. In this case that behavior isn't leading to what you would expect to see. If you replace `R` with `*` you get an `AtomNullQuery()` and everything works fine.

If you provide an `R#` and the `M  RGP` line later, the dummy-query atom is replaced with an `AtomNullQuery()`, which matches anything, and everything works fine.

I think there's a case to be made here for changing the way that the symbol `R` in a mol block is handled and treating it the same as a `*` atom. It changes behavior, but leads to something that is, I believe, closer to what the user likely intends. It would have the side effect of making it difficult/impossible to express a query that matches only dummy atoms in a mol block, but I don't think this is likely to be that much of a problem. What do you think @bp-kelley?

**Comment by greglandrum** [comment] 2019-07-04 04:46
(sorry, I made an earlier comment that was incorrect... deleted that and trying it again)

For some reason I haven't tracked down yet, the reactants that come from the RXN parser have had the `R` atoms converted into query atoms that only match dummies (i.e. they are querying for atoms with atomic number 0). The default behavior of the Mol file parser is to have `R` atoms actually be dummy atoms (i.e. the atomic number is zero, but they don't have a query). Once I figure out why this is happening, we can think about solutions.

**Comment by greglandrum** [comment] 2019-07-04 04:59
Ok, here's the block of code that's doing this:
https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/ChemReactions/MDLParser.cpp#L340

At the core the problem is the way the atom symbol `R` is handled. Since R isn't described in the CTAB spec, but it does appear frequently in mol/rxn files, I just made up a behavior for it. So the Mol file parser adds an atom with atomic number 0. The RXN parser then converts that to a query for an atom with atomic number 0. That's leading to the strange results you are seeing. If you replace R with * you get an AtomNullQuery() from the beginning and everything works fine.

Similarly, if you provide an R# and the M RGP line later, the dummy-query atom is replaced with an AtomNullQuery(), which matches anything, and everything works fine.

I think there's a case to be made here for changing the way that the symbol R in a mol block is handled and treating it the same as a * atom. It changes behavior, but leads to something that is, I believe, closer to what the user likely intends. It would have the side effect of making it difficult/impossible to express a query that matches only dummy atoms in a mol block, but I don't think this is likely to be that much of a problem. What do you think @bp-kelley?

**Comment by bp-kelley** [comment] 2019-09-12 01:29
We had a separate discussion about this issue that was resolved in the merge above.

**Closed by bp-kelley** 2019-09-12 01:29 UTC
