### ISSUE TITLE
Incorrect 3D embedding for Quercetin Dihydrate

### ISSUE THREAD

**Issue by MagicPF** [rdkit/rdkit#4797] opened 2021-12-15 13:52 UTC
smiles = "C1=CC(=C(C=C1C2=C(C(=O)C3=C(C=C(C=C3O2)O)O)O)O)O.O.O"
mol = Chem.MolFromSmiles(smiles)
AllChem.Compute2DCoords(mol)
m3 = Chem.AddHs(m2)
AllChem.EmbedMolecule(m3)
pos = Chem.MolToMolBlock(m3)

According to the visualization result based on pos, the structure was not respect to the real structure, may I ask for the reason and solution?

**Comment by greglandrum** [comment] 2021-12-15 13:58
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.

**Closed by greglandrum** 2021-12-15 13:58 UTC
Labels: bug
