### ISSUE TITLE
Morgan fingerprints generated by rdkit are not consistent with the ones in the ECFP paper

### ISSUE THREAD

**Issue by janeyin600** [rdkit/rdkit#2018] opened 2018-08-30 23:02 UTC
Hi, 

I was trying to reproduce the fingerprint examples provided by the ECFP paper (J. Chem. Inf. Model. 2010, 50, 742–754)

My code is like this:

from rdkit.Chem import AllChem
from rdkit import Chem

str = 'CCCC(=O)N'

mol = Chem.MolFromSmiles(str)
fp = AllChem.GetMorganFingerprint(mol, 2)
print(list(fp.GetNonzeroElements().keys()))

The output is:
[474023245, 847957139, 864942730, 1167322652, 1173125914, 1510328189, 2231929377, 2245384272, 2246699815, 2246728737, 2591432844, 3328145258, 3542456614, 4112692162]

Which is not close to what was provided in Figure 8 of the ECFP paper (J. Chem. Inf. Model. 2010, 50, 742–754 ). The link of this paper is:
https://pubs.acs.org/doi/abs/10.1021/ci100050t

Thanks for your help!

**Comment by zealseeker** [comment] 2018-08-31 01:27
Hi @janeyin600 , as far as I know, comparing the number is not a good way since the hash algorithm may differ. Have you found that the numbers generated by RDkit are all positive number, while negative number is allowed in the paper.

To check and reproduce, you can explain the fingerprint by http://rdkit.org/docs/GettingStartedInPython.html#explaining-bits-from-morgan-fingerprints .
Since the figure 7 in the paper has shown the details of each fragment, it is not difficult to check whether they are the same.

**Comment by janeyin600** [comment] 2018-08-31 21:46
Thanks @zealseeker! Makes sense.
Below is my code of highlighting a molecular fragment using fingerprints. Hopefully it's useful to other users as well.

from rdkit.Chem import Draw

size = (300, 300)
env = Chem.FindAtomEnvironmentOfRadiusN(mol,1,2) # centered around atom 1 with a radius of 2
amap={}
submol=Chem.PathToSubmol(mol,env,atomMap=amap)
matching = mol.GetSubstructMatch(submol)
fig = Draw.MolToMPL(mol, size=size,highlightAtoms=matching)

**Comment by greglandrum** [comment] 2018-09-04 10:09
I'm closing this because it looks like the question is answered. Please reopen if necessary.

**Closed** 2018-09-04 10:10 UTC
Labels: question

**Comment by Mrqeoqqt** [comment] 2021-03-16 07:11
Hi @zealseeker , 

I have a follow-up question since this issue mentioned consistency.

When using morgan fp as input for neural networks, it matters that the same bit should represent the same substructure for different molecules. 

@janeyin600 mentioned that rdkit generates differently from the original ECFP paper.  I wonder whether rdkit is able to generate morgan fingerprints exactly the same all the time.

Thanks a lot

**Comment by greglandrum** [comment] 2021-03-16 09:40
@Mrqeoqqt  As long as you keep the RDKit version the same you should always get the same bits for the same molecule.

Bug fixes could cause changes to the computed Morgan fingerprints from one version of the RDKit to the next though.
