### ISSUE TITLE
Stereo information not included when importing a CDXML

### ISSUE THREAD

**Issue by davidmartos96** [rdkit/rdkit#5877] opened 2022-12-16 12:28 UTC
**Describe the bug**
Hello,
I'm trying to import a CDXML, but when doing so I encountered that properties like BondDir are lost in the imported molecule. 
Drawing the molecule clearly shows the error.

Is there something I'm missing?

**To Reproduce**
### Python script
```python
from rdkit import Chem
from rdkit.Chem import Draw

def main():
    mols = Chem.MolsFromCDXMLFile('mol.cdxml')
    mol = mols[0]
    Draw.MolToFile(mol, 'cdxml.png')

main()
```

### ChemDraw molecule 
![image](https://user-images.githubusercontent.com/22084723/208097523-1eedd553-4bbb-43c1-a58f-801b1363b25e.png)

### RDKit drawing
![cdxml](https://user-images.githubusercontent.com/22084723/208097636-d18a82cf-ed9b-41e3-8d39-8fcdb01d7192.png)

### CDXML file
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE CDXML SYSTEM "http://www.cambridgesoft.com/xml/cdxml.dtd" >
<CDXML
 CreationProgram="ChemDraw JS 2.0.0.9"
 Name="ACS Document 1996"
 BoundingBox="691.17 269.17 707.39 284.17"
 WindowPosition="0 0"
 WindowSize="0 0"
 FractionalWidths="yes"
 InterpretChemically="yes"
 ShowAtomQuery="yes"
 ShowAtomStereo="no"
 ShowAtomEnhancedStereo="yes"
 ShowAtomNumber="no"
 ShowResidueID="no"
 ShowBondQuery="yes"
 ShowBondRxn="yes"
 ShowBondStereo="no"
 ShowTerminalCarbonLabels="no"
 ShowNonTerminalCarbonLabels="no"
 HideImplicitHydrogens="no"
 Magnification="666"
 LabelFont="24"
 LabelSize="10"
 LabelFace="96"
 CaptionFont="24"
 CaptionSize="10"
 HashSpacing="2.50"
 MarginWidth="1.60"
 LineWidth="0.60"
 BoldWidth="2"
 BondLength="14.40"
 BondSpacing="18"
 ChainAngle="120"
 LabelJustification="Auto"
 CaptionJustification="Left"
 AminoAcidTermini="HOH"
 ShowSequenceTermini="yes"
 ShowSequenceBonds="yes"
 ShowSequenceUnlinkedBranches="no"
 ResidueWrapCount="40"
 ResidueBlockCount="10"
 ResidueZigZag="yes"
 NumberResidueBlocks="no"
 PrintMargins="36 36 36 36"
 MacPrintInfo="0003000001200120000000000B6608A0FF84FF880BE309180367052703FC0002000001200120000000000B6608A0000100000064000000010001010100000001270F000100010000000000000000000000000002001901900000000000400000000000000000000100000000000000000000000000000000"
 ChemPropName=""
 ChemPropFormula="Chemical Formula: "
 ChemPropExactMass="Exact Mass: "
 ChemPropMolWt="Molecular Weight: "
 ChemPropMOverZ="m/z: "
 ChemPropAnalysis="Elemental Analysis: "
 ChemPropBoilingPt="Boiling Point: "
 ChemPropMeltingPt="Melting Point: "
 ChemPropCritTemp="Critical Temp: "
 ChemPropCritPres="Critical Pres: "
 ChemPropCritVol="Critical Vol: "
 ChemPropGibbs="Gibbs Energy: "
 ChemPropLogP="Log P: "
 ChemPropMR="MR: "
 ChemPropHenry="Henry&apos;s Law: "
 ChemPropEForm="Heat of Form: "
 ChemProptPSA="tPSA: "
 ChemPropID=""
 ChemPropFragmentLabel=""
 color="0"
 bgcolor="1"
 RxnAutonumberStart="1"
 RxnAutonumberConditions="no"
 RxnAutonumberStyle="Roman"
 RxnAutonumberFormat="(#)"
><colortable>
<color r="1" g="1" b="1"/>
<color r="0" g="0" b="0"/>
<color r="1" g="0" b="0"/>
<color r="1" g="1" b="0"/>
<color r="0" g="1" b="0"/>
<color r="0" g="1" b="1"/>
<color r="0" g="0" b="1"/>
<color r="1" g="0" b="1"/>
</colortable><fonttable>
<font id="24" charset="utf-8" name="Arial"/>
</fonttable><page
 id="20"
 BoundingBox="0 0 1639.33 748.67"
 Width="1639.33"
 Height="748.67"
 HeaderPosition="36"
 FooterPosition="36"
 PageOverlap="0"
 PrintTrimMarks="yes"
 HeightPages="1"
 WidthPages="1"
 DrawingSpace="poster"
><fragment
 id="10"
 BoundingBox="691.17 269.17 707.39 284.17"
 Z="4"
><n
 id="7"
 p="691.47 269.47"
 Z="1"
 AS="N"
/><n
 id="9"
 p="691.47 283.87"
 Z="3"
 AS="N"
/><n
 id="11"
 p="705.87 283.87"
 Z="5"
 AS="N"
/><n
 id="13"
 p="705.87 269.47"
 Z="7"
 AS="N"
/><b
 id="15"
 Z="9"
 B="7"
 E="9"
 Order="2"
 BS="N"
 BondCircularOrdering="18 0 0 16"
/><b
 id="16"
 Z="10"
 B="9"
 E="11"
 BS="N"
/><b
 id="17"
 Z="11"
 B="11"
 E="13"
 Display="WedgeBegin"
 BS="N"
/><b
 id="18"
 Z="12"
 B="13"
 E="7"
 BS="N"
/></fragment></page></CDXML>

```

**Expected behavior**
The BondDir property is kept.

**Configuration (please complete the following information):**
 - RDKit version: 2022_09_3
 - OS: Fedora 37
 - Are you using conda? No
 - If you are not using conda: how did you install the RDKit? From source in the specific version

**Comment by greglandrum** [comment] 2022-12-16 15:18
The RDKit always removes bond wedging, particularly from non-chiral centers, when you read in a molecule.
@bp-kelley will need to confirm, but I assume that the CDXML parser will correctly use the wedging information to assign stereochemistry when it's appropriate.

**Comment by greglandrum** [comment] 2022-12-27 06:23
I'm closing this because it looks like the question is answered. Please reopen if necessary.

**Closed by greglandrum** 2022-12-27 06:23 UTC
Labels: not a bug

**Comment by bp-kelley** [comment] 2022-12-27 15:21
I’ll check if sanitize can be turned off here, this might keep the wedging at least.

**Comment by davidmartos96** [comment] 2023-01-20 12:28
@bp-kelley Could this be kept open? 
If this is not a bug, what would be the steps/workaround needed to generate the same image?

**Comment by bp-kelley** [comment] 2023-01-20 13:10
The RDKit simply doesn't retain that information in these systems.

**Comment by Alesapo-py** [comment] 2024-11-06 14:56
i have the same problem. i think that is caused by 'Chem.MolsFromCDXMLFile' function.
i'm trying to change the function, but i don't find the RDkit function's code yet.
if someone will find it, can send me the source?
thanks a lot.

**Comment by greglandrum** [comment] 2024-11-07 08:37
@Alesapo-py the information is retained in the molecule and you can reapply the original wedging to the molecule (whether it makes sense or not), using the function `Chem.ReapplyMolBlockWedging()`

**Comment by Alesapo-py** [comment] 2024-11-07 10:20
Thank you so much Greg.
I have another problem: rdkit recognize all bonds as STEREONONE, But some bonds of my molecule are chiral.
So i would like to know, how rdkit can identify these bonds as STEREOANY.
There is a function? Or i need to change the code of MolsFromCDXMLFile?

**Comment by greglandrum** [comment] 2024-11-07 13:18
> Thank you so much Greg. I have another problem: rdkit recognize all bonds as STEREONONE, But some bonds of my molecule are chiral. So i would like to know, how rdkit can identify these bonds as STEREOANY. There is a function? Or i need to change the code of MolsFromCDXMLFile?

I'm not sure what you mean, could you please provide a concrete example?

**Comment by Alesapo-py** [comment] 2024-11-07 13:39
````
mol = Chem.rdmolfiles.MolsFromCDXMLFile('/content/molecole formato cdx da convertire/11169_9.cdxml', sanitize=True, removeHs=False)[0]
for bond in mol.GetBonds():
    bond_idx = bond.GetIdx()
    atom1_idx = bond.GetBeginAtomIdx()
    atom2_idx = bond.GetEndAtomIdx()
    bond_stereo = bond.GetStereo()
    bond_dir = bond.GetBondDir()
    print(f"Bond_index: {bond_idx}")
    print(f"  Atom_index: {atom1_idx}, {atom2_idx}")
    print(f"  Stereo: {bond_stereo}")
    print(f"  Dir: {bond_dir}")
    print("##" * 20)
```
with this code i can obtain information about bond stereo and bond direction.
In my molecule i have 2 bonds that are STEREOANY, but rdkit classify them as STEREONONE.
also using your function suggested.
So i'm thinking about to modify the source code of the function 'MolsFromCDXMLFile'.
i'm using python... my aim is: define new function that read also stereobonds.
Thanks a lot Mr.Greg.
