### ISSUE TITLE
Does the java wrapper have a similar rdkit.Chem.QED module in the python API

### ISSUE THREAD

**Issue by miracle1111111** [rdkit/rdkit#3839] opened 2021-02-22 06:32 UTC
I need rdkit.Chem.QED.QEDproperties (MW, ALOGP, HBA, HBD, PSA, ROTB, AROM, ALERTS) in python. Then there is no quantitative estimate of drug similarity in the java wrapper. Where is it located?
Thank you very much！

**Comment by greglandrum** [comment] 2021-02-22 06:58
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.

**Closed by greglandrum** 2021-02-22 06:58 UTC
