### ISSUE TITLE
Character used for a single bond is the same as that for a negative charge.

### ISSUE THREAD

**Issue by pv-is-nrt** [rdkit/rdkit#5724] opened 2022-11-03 06:07 UTC
I see that the character used for a single bond is the same as that for a negative charge. This is presenting problems while parsing a smiles string correctly that contains both. Is there a reason why the characters cannot be different? 

If this isn't a problem for anyone else, can someone please help me with a solution where I can define my own different character for a negative charge while using the ```Chem.MolToSmiles(mol, isomericSmiles=True, allBondsExplicit=True)``` method?

 - RDKit version: 2022.9.1
 - OS: [e.g. Ubuntu 20.04] Windows 10
 - Python version (if relevant): 3.10.6
 - Are you using conda? No
 - If you are using conda, which channel did you install the rdkit from?
 - If you are not using conda: how did you install the RDKit? pip

**Comment by greglandrum** [comment] 2022-11-03 06:58
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.

**Closed by greglandrum** 2022-11-03 06:58 UTC
