### ISSUE TITLE
Non-unique hash values of atom and bond features

### ISSUE THREAD

**Issue by jangerit** [rdkit/rdkit#7146] opened 2024-02-07 13:00 UTC
**Describe the bug**
Different atom and bond features have the same hash, which results in strange object comparison behaviour. 

**To Reproduce**
Simple example: 
```
from rdkit.Chem.rdchem import BondType, HybridizationType
BondType.SINGLE == HybridizationType.S
# True
```

Example with molecule (rather artifical case but behaviour is not intuitive):
```
import rdkit.Chem
from rdkit.Chem.rdchem import BondType, HybridizationType, BondStereo
mol = rdkit.Chem.MolFromSmiles("CC=C")
for a in mol.GetAtoms():
    hybr = a.GetHybridization()
    print(hybr)
    print(hybr == BondType.TRIPLE)
# SP3
# False
# SP2
# True
# SP2
# True
```

Exemplary hash values (counting for hash seems to start at 0/1 for each feature):
```
from rdkit.Chem.rdchem import BondType, HybridizationType, BondStereo, ChiralType
feature_dict = {
    'HybridizationType.UNSPECIFIED' : hash(HybridizationType.UNSPECIFIED),
    'HybridizationType.S' : hash(HybridizationType.S),
    'HybridizationType.SP' : hash(HybridizationType.SP),
    'HybridizationType.SP2' : hash(HybridizationType.SP2),
    'HybridizationType.SP3' : hash(HybridizationType.SP3),
    'HybridizationType.SP3D' : hash(HybridizationType.SP3D),
    'HybridizationType.SP3D2' : hash(HybridizationType.SP3D2),
    'HybridizationType.OTHER' : hash(HybridizationType.OTHER),
    'ChiralType.CHI_UNSPECIFIED' : hash(ChiralType.CHI_UNSPECIFIED),
    'ChiralType.CHI_TETRAHEDRAL_CW' : hash(ChiralType.CHI_TETRAHEDRAL_CW),
    'ChiralType.CHI_TETRAHEDRAL_CCW' : hash(ChiralType.CHI_TETRAHEDRAL_CCW),
    'ChiralType.CHI_OTHER' : hash(ChiralType.CHI_OTHER),
    'BondType.SINGLE' : hash(BondType.SINGLE),
    'BondType.DOUBLE' : hash(BondType.DOUBLE),
    'BondType.TRIPLE' : hash(BondType.TRIPLE),
    'BondType.AROMATIC' : hash(BondType.AROMATIC),
    'BondStereo.STEREONONE' : hash(BondStereo.STEREONONE),
    'BondStereo.STEREOANY' : hash(BondStereo.STEREOANY),
    'BondStereo.STEREOZ' : hash(BondStereo.STEREOZ),
    'BondStereo.STEREOE' : hash(BondStereo.STEREOE),
    'BondStereo.STEREOCIS' : hash(BondStereo.STEREOCIS),
    'BondStereo.STEREOTRANS' : hash(BondStereo.STEREOTRANS),
}
feature_dict
# {
#   'HybridizationType.S': 1
#   'HybridizationType.SP': 2
#   'HybridizationType.SP2': 3
#   'HybridizationType.SP3': 4
#   'HybridizationType.SP3D': 6
#   'HybridizationType.SP3D2': 7
#   'HybridizationType.OTHER': 8
#   'ChiralType.CHI_UNSPECIFIED': 0
#   'ChiralType.CHI_TETRAHEDRAL_CW': 1
#   'ChiralType.CHI_TETRAHEDRAL_CCW': 2
#   'ChiralType.CHI_OTHER': 3
#   'BondType.SINGLE': 1
#   'BondType.DOUBLE': 2
#   'BondType.TRIPLE': 3
#   'BondType.AROMATIC': 12
#   'BondStereo.STEREONONE': 0
#   'BondStereo.STEREOANY': 1
#   'BondStereo.STEREOZ': 2, 
#   'BondStereo.STEREOE': 3, 
#   'BondStereo.STEREOCIS': 4, 
#   'BondStereo.STEREOTRANS': 5
# }
```

I noticed this when trying to create a mapping (dict) to save features in string format to json/yaml:
```
from rdkit.Chem.rdchem import BondType, HybridizationType
feature_dict = {
    HybridizationType.S: 'HybridizationType.S',
    BondType.SINGLE: 'BondType.SINGLE', 
}
feature_dict
# {rdkit.Chem.rdchem.HybridizationType.S: 'BondType.SINGLE'}
print(len(feature_dict))
# 1
```

**Expected behavior**
Each feature has unique hash value, e.g., 
```
from rdkit.Chem.rdchem import BondType, HybridizationType
BondType.SINGLE == HybridizationType.S
# False
```

**Configuration**
 - RDKit version: 2023.9.2
 - OS: Rocky Linux 8.9
 - Python version: 3.9.13
 - If you are not using conda: how did you install the RDKit? pypi

Thanks a lot for your help in advance.

**Comment by greglandrum** [comment] 2024-02-09 07:30
I understand what you are looking for, but this is not the idea of those constants and it's not something we can do in a straightforward manner. Those types are the equivalent of python `enum` objects and we cannot globally set the indices to be unique.

You can easily make things unique by using something like `(Chem.ChiralType,Chem.ChiralType.CHI_TETRAHEDRAL)` as your dictionary keys.

**Comment by greglandrum** [comment] 2024-02-09 12:07
I'm going to close this since it's not a bug and is not a feature that we could implement.
If you're interested in discussing possible alternative solutions or workarounds, please start a new topic in the discussions tab.

**Closed by greglandrum** 2024-02-09 12:07 UTC

**Comment by jangerit** [comment] 2024-02-09 13:12
Thanks a lot for the fast and helpful answer as well as the suggestion.
