### ISSUE TITLE
Request for GetsubstructMatches without ionization state.

### ISSUE THREAD

**Issue by ohjaekyun** [rdkit/rdkit#4250] opened 2021-06-16 03:09 UTC
I want to take substructure match without consideration of ionization state.
In detail, if atom symbol and bond type is equal, I want to tuple of match_index.
Can it be?
![imgformatch](https://user-images.githubusercontent.com/75828080/122152055-9af60800-ce9b-11eb-832c-b0bfafd4775e.png)

**Comment by greglandrum** [comment] 2021-06-16 09:09
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.

**Closed by greglandrum** 2021-06-16 09:09 UTC
Labels: enhancement
