### ISSUE TITLE
parameters for ACS1996 drawing mode 

### ISSUE THREAD

**Issue by jaechang-hits** [rdkit/rdkit#7518] opened 2024-06-14 02:50 UTC
I'd like to know the parameter of ACS1996 drawing mode to set the parameter in RDKIT JS drawing mode

**Comment by greglandrum** [comment] 2024-06-14 03:51
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.

**Closed by greglandrum** 2024-06-14 03:51 UTC
Labels: enhancement
