### ISSUE TITLE
Can I choose the format specification for generating mol files?

### ISSUE THREAD

**Issue by niuzhenjiang** [rdkit/rdkit#4377] opened 2021-08-02 11:34 UTC
Can rdkit choose to output chemdraw format when generating mol file? Or is there any way to generate mol files in chemdraw format.please help me,thanks~,generate mol2000 file can include "M  STY...M  SLB ...M  SAL..."
```text
Untitled Document-1
  ChemDraw08022107362D

  7  6  0  0  0  0  0  0  0  0999 V2000
   -2.1435    0.2063    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.4290   -0.2063    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7145    0.2063    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000   -0.2063    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.7145    0.2063    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.4290   -0.2063    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    2.1435    0.2063    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  6  7  1  0      
  5  6  1  0      
  1  2  1  0      
  2  3  1  0      
  3  4  1  0      
  4  5  1  0      
M  STY  1   1 SUP
M  SLB  1   1   1
M  SAL   1  2   6   7
M  SBL   1  1   2
M  SMT   1 OMe
M  SBV   1   2   -0.7145    0.4125
M  END


```

**Comment by greglandrum** [comment] 2021-08-02 12:44
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.

**Closed by greglandrum** 2021-08-02 12:44 UTC
Labels: bug
