### ISSUE TITLE
Release of 2023.09.1 on pypi

### ISSUE THREAD

**Issue by wjm41** [rdkit/rdkit#6828] opened 2023-10-24 22:22 UTC
Hiya! I wanted to install the new `2023.09.1` release of rdkit to utilise some of the new features, and realised that it is released on [conda-forge](https://anaconda.org/conda-forge/rdkit/files) but not on [PyPi](https://pypi.org/project/rdkit/#history). Is this intentional?

**Comment by greglandrum** [comment] 2023-10-25 02:56
I assume it's because @kuelumbus hasn't had time to do it yet.

**Comment by greglandrum** [comment] 2023-10-25 02:57
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.

**Closed by greglandrum** 2023-10-25 02:57 UTC

**Comment by kuelumbus** [comment] 2023-10-25 06:28
Sorry for the delay. The PyPi wheels are delayed because compiling on MacOS fails due to the incomplete C++17 implementation. I am currently looking for a workaround. https://github.com/kuelumbus/rdkit-pypi/pull/85

**Comment by rvianello** [comment] 2023-10-25 07:01
@kuelumbus would your build environment support using a workaround similar to what conda-forge suggests here: https://conda-forge.org/docs/maintainer/knowledge_base.html#newer-c-features-with-old-sdk ?

**Comment by kuelumbus** [comment] 2023-10-25 07:09
Configuring the development target as 10.15 (or 10.14) should be effective, but it also constrains the compatibility of the RDKIt package to macOS versions above 10.15 (or 10.14).

**Comment by greglandrum** [comment] 2023-10-25 07:23
> Configuring the development target as 10.15 (or 10.14) should be effective, but it also constrains the compatibility of the RDKIt package to macOS versions above 10.15 (or 10.14). 

Technically it only constrains newer versions of the RDKit. And 10.14 came out in 2019.
It's your call how much work you want to invest to allow people who won't update there operating system to update their RDKit version

**Comment by kuelumbus** [comment] 2023-10-25 07:27
Good point @greglandrum. :)

**Comment by wjm41** [comment] 2023-10-25 11:41
Wow that was quick! Thanks @kuelumbus!
