### ISSUE TITLE
ModuleNotFoundError: No module named 'rdkit' 

### ISSUE THREAD

**Issue by poppy7675** [rdkit/rdkit#2574] opened 2019-07-29 18:38 UTC
**Description:**

Hello, 
I installed rdkit using conda but upon using the "import rdkit" function in python, I recieve a ModuleNotFoundError error. 

I am using Python 3.6, RDKit 2019.03.3.0, Windows 10. 

After running conda list in the environment where I installed the rdkit, here is a part of the output: 
https://imgur.com/BreM8cW 

I am extremely new to coding. Any help will be appreciated. 

Here is the error I am receiving:
`Traceback (most recent call last):
  File "D:\Junior Year\SIR\rdkit sad.py", line 1, in <module>
    import rdkit
ModuleNotFoundError: No module named 'rdkit'`

**Comment by greglandrum** [comment] 2019-07-30 04:51
Are you sure that the environment where you installed the RDKit has been activated when you call the script?

**Comment by poppy7675** [comment] 2019-07-31 20:35
@greglandrum  Thank you for your reply. I think I was able to activate the environment by typing "activate my-rdkit-env" in the command prompt. However, after opening python and trying to import rdkit again, I recieve the same modulenotfound error.

**Comment by greglandrum** [comment] 2019-08-01 02:43
if you are using a recent install of conda, then the correct activation function is:
`conda activate my-rdkit-env`
If that doesn't work, please do these two commands right after another in the same windows shell and include the output :
```
conda list
python -c "import rdkit"
```

**Comment by poppy7675** [comment] 2019-08-04 02:36
hello, "conda activate my-rdkit" does not seem to work on my windows device, as it leads to this commandnotfounderror: Your shell has not been properly configured to use 'conda activate.' After using conda list I get this result: https://imgur.com/a/X45l3id 

python -c "import rdkit" does not seem to do anything, as shown here: https://imgur.com/a/DwELLvj

I was able to installed rdkit using the "conda install -c rdkit rdkit" command available on anaconda cloud (https://anaconda.org/rdkit/rdkit), so I think that's why rdkit shows up after I use the "conda list" function. However, when I open python in my my-rdkit-env environment, I recieve the notification "Warning: This python interpreter is in a conda environment, but the environment has not been activated." Therefore, I don't think my-rdkit-env has been successfully activated, and perhaps why I still can not import rdkit in my recently installed 3.7 python interpreter or my 3.6 python interpreter. 

This is what shows up after I write the command "activate-my-rdkit-env" as instructed by https://www.rdkit.org/docs/Install.html: https://imgur.com/a/Zo7nsRF     

Is having (my-rdkit-env) the only thing that's supposed to change?

**Comment by greglandrum** [comment] 2019-08-05 13:10
This sounds like you have a problem with your anaconda installation, not an RDKit problem. As much as I'd like to help out here, I just don't have the capacity to support anaconda.
Once you have a working anaconda install, please check back in here if the problem is still there.

**Comment by bp-kelley** [comment] 2019-09-11 20:17
I'm going to close this issue.  @poppy7675 please reopen or submit a new one if you have an rdkit specific anaconda issue.

**Closed by bp-kelley** 2019-09-11 20:17 UTC

**Comment by asmelzene** [comment] 2019-12-05 22:56
(my-rdkit-env) Melihs-MacBook-Pro:~ melih$ conda list|grep rdkit
# packages in environment at /Users/melih/opt/anaconda3/envs/my-rdkit-env:
rdkit                     2019.09.2.0      py37h65625ec_1    rdkit
(my-rdkit-env) Melihs-MacBook-Pro:~ melih$ python -c "import rdkit"
(my-rdkit-env) Melihs-MacBook-Pro:~ melih$ 

I installed anaconda and rdkit without an error. Jupyter notebook works fine without rdkit but once I want to use rdkit, it can't find the package:

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-7-5ec767bace17> in <module>
      2 smiles_df.info()
      3 
----> 4 import rdkit
      5 from rdkit import Chem
      6 import rdkit.Chem.rdMolDescriptors as rdMolDesc

ModuleNotFoundError: No module named 'rdkit'

I reinstalled everything but it didn't help and I can't find a clear explanation related to that subject. Is there any way you can recommend to fix this error?

**Comment by Lirain21** [comment] 2022-03-12 00:57
You can run it in the terminal. It is helpful for me.

**Comment by mainguyenanhvu** [comment] 2023-04-28 08:42
Please try the solution in [this link](https://stackoverflow.com/questions/37242189/rdkit-installation-issues-with-anaconda/76127780#76127780)
