### ISSUE TITLE
Fragmentation of PROTAC molecules

### ISSUE THREAD

**Issue by JIBSN** [rdkit/rdkit#6586] opened 2023-07-31 12:18 UTC
### Discussed in https://github.com/rdkit/rdkit/discussions/6585

<div type='discussions-op-text'>

<sup>Originally posted by **JIBSN** July 31, 2023</sup>
Hi all,

I want to build a PROTAC database, and currently, I have a large set of structurally diverse PROTAC molecules from patents. I intend to use RDKit to fragment them into warhead, linker, and ligand components. I have worked for it a few days but little progress. I mainly tried substrucuture match, but it's no easy to find the correct bond to fragment on. I am seeking guidance from anyone who has experience with similar fragmentation tasks. Any assistance or advice would be appreciated.</div>

**Comment by greglandrum** [comment] 2023-08-03 16:50
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.

**Closed by greglandrum** 2023-08-03 16:50 UTC
